---
permalink: get-started/formatting-rules-for-script-commands.html 
sidebar: sidebar 
keywords: format, rules, script, commands 
summary: Sintaxe exclusiva para um comando de script específico é explicada na seção Notas no final de cada descrição de comando de script. 
---
= Formate regras para comandos de script
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sintaxe exclusiva para um comando de script específico é explicada na seção Notas no final de cada descrição de comando de script.

*Sensibilidade do caso* -- os comandos de script não são sensíveis a maiúsculas e minúsculas. Você pode digitar os comandos de script em minúsculas, maiúsculas ou minúsculas. (Nas descrições de comandos a seguir, o caso misto é usado como um auxílio para ler os nomes dos comandos e entender a finalidade do comando.)

*Spaces* -- você deve inserir espaços nos comandos de script como eles são mostrados nas descrições dos comandos.

* Suportes quadrados * -- suportes quadrados são usados de duas maneiras:

* Como parte da sintaxe de comando.
* Para indicar que os parâmetros são opcionais. A descrição de cada parâmetro indica se você precisa incluir um valor de parâmetro entre colchetes.


*Parênteses* -- parênteses mostrados na sintaxe do comando incluem escolhas específicas para um parâmetro. Ou seja, se você quiser usar o parâmetro, você deve inserir um dos valores entre parênteses. Geralmente, você não inclui parênteses em um comando de script; no entanto, em alguns casos, quando você insere listas, você deve incluir a lista entre parênteses. Essa lista pode ser uma lista de valores de ID da bandeja e valores de ID do slot. A descrição de cada parâmetro indica se você precisa incluir um valor de parâmetro entre parênteses.

* Barras verticais* -- barras verticais em um comando de script indicam "'or'" e separam os valores válidos para o parâmetro. Por exemplo, a sintaxe para o `raidLevel` parâmetro na descrição do comando aparece da seguinte forma:

[listing]
----
 raidLevel=(0 | 1 | 3 | 5 | 6)
----
Para usar o `raidLevel` parâmetro para definir RAID nível 5, digite este valor:

[listing]
----
 raidLevel=5
----
*Locais de unidades* -- os comandos CLI que identificam locais de unidades suportam bandejas de unidades de alta capacidade e bandejas de unidades de baixa capacidade. Uma bandeja de unidades de alta capacidade tem gavetas que prendem as unidades. As gavetas deslizam para fora da bandeja de unidades para fornecer acesso às unidades. Uma bandeja de unidades de baixa capacidade não tem gavetas. Para uma bandeja de unidades de alta capacidade, você deve especificar o identificador (ID) da bandeja de unidades, o ID da gaveta e o ID do slot no qual uma unidade reside. Para uma bandeja de unidades de baixa capacidade, você precisa especificar apenas o ID da bandeja de unidades e o ID do slot em que uma unidade reside. Para uma bandeja de unidades de baixa capacidade, um método alternativo para identificar um local para uma unidade é especificar a ID da bandeja de unidades, definir a ID da gaveta como 0 e especificar a ID do slot em que uma unidade reside. Separe os valores de ID com uma vírgula. Se você inserir mais de um conjunto de valores de ID, separe cada conjunto de valores com um espaço.

Existem duas convenções para especificar unidades na CLI. A convenção que você deve usar é especificada em cada comando. Uma convenção usa um sinal igual e parênteses:

[listing]
----

        drive=\(trayID,[drawerID,]slotID\)
----
A segunda convenção não usa nenhum sinal igual, mas um par de chaves em torno das unidades especificadas:

[listing]
----

        drive \[trayID,[drawerID,]slotID\]
----
Aqui estão alguns exemplos usando parênteses:

[listing]
----
(1,1 1,2 1,3 1,4 2,1 2,2 2,3 2,4)
----
ou, para uma bandeja de unidades de alta capacidade, este exemplo:

[listing]
----
(1,1,1 1,2,2 1,3,3 1,4,4 2,1,1 2,2,2 2,3,3 2,4,4)
----
*Termos em itálico* -- termos em itálico no comando indicam um valor ou informação que você precisa fornecer. Por exemplo, quando você encontra o termo itálico:

[listing]
----

          *numberOfDrives*
----
Substitua o termo em itálico por um valor para o número de unidades que você deseja incluir com o comando script.

*Ponto e vírgula* -- os comandos de script devem terminar com um ponto e vírgula (`;`). Você pode inserir mais de um comando de script na linha de comando ou em um arquivo de script. Por exemplo, um ponto e vírgula é usado para separar cada comando de script no arquivo de script a seguir.

[listing]
----
create volume drives=(0,2 0,3 1,4 1,5 2,6 2,7) raidLevel=5 userLabel=”v1” capacity=2gb owner=a;
create volume volumeGroup=2 userLabel=”v2” capacity=1gb owner=b;
create volume volumeGroup=2 userLabel=”v3” capacity=1gb owner=a;
----
[listing]
----
create volume drives=(0,4 0,5 1,6 1,7 2,8 2,9) raidLevel=5 userLabel=”v4” capacity=2gb owner=b;
create volume volumeGroup=3 userLabel=”v5” capacity=1gb owner=a;
create volume volumeGroup=3 userLabel=”v6” capacity=1gb owner=b;
----