---
permalink: get-started/interactive-mode.html 
sidebar: sidebar 
keywords: interactive mode 
summary: 'Se você inserir `SMcli` e um nome de storage array, mas não especificar parâmetros CLI, comandos de script ou um arquivo de script, a interface de linha de comando será executada no modo interativo.' 
---
= Modo interativo
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


Se você inserir `SMcli` e um nome de storage array, mas não especificar parâmetros CLI, comandos de script ou um arquivo de script, a interface de linha de comando será executada no modo interativo. O modo interativo permite executar comandos individuais sem prefixar os comandos com `SMcli`o .

No modo interativo, você pode inserir um único comando, exibir os resultados e digitar o próximo comando sem digitar a cadeia de carateres completa `SMcli`. O modo interativo é útil para determinar erros de configuração e testar rapidamente alterações de configuração.

Para terminar uma sessão de modo interativo, digite o comando específico do sistema operacional. Para Linux, esta combinação chave é *Control-D*. Para Windows, esta combinação de teclas é *Control-Z e ENTER*.
