---
permalink: get-started/interactive-mode.html 
sidebar: sidebar 
keywords: interactive mode 
summary: 'O modo interativo permite executar comandos individuais sem prefixar os comandos com `SMcli`o .' 
---
= Modo interativo
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
O modo interativo permite executar comandos individuais sem prefixar os comandos com `SMcli`o .

Se você inserir `SMcli` e um nome de storage array, mas não especificar parâmetros CLI, comandos de script ou um arquivo de script, a interface de linha de comando será executada no modo interativo.

No modo interativo, você pode inserir um único comando, exibir os resultados e digitar o próximo comando sem digitar a cadeia de carateres completa `SMcli`. O modo interativo é útil para determinar erros de configuração e testar rapidamente alterações de configuração.

Para terminar uma sessão de modo interativo, digite o comando específico do sistema operacional. Para Linux, esta combinação chave é *Control-D*. Para Windows, esta combinação de teclas é *Control-Z e ENTER*.
