---
permalink: commands-a-z/check-repositoryconsistency.html 
sidebar: sidebar 
keywords: check, repository, consistency 
summary: O comando check repostoryConsistency produz um relatório baseado na análise dos dados no volume de repositório subjacente de um objeto especificado. 
---
= Verifique a consistência do repositório
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
O `check repositoryConsistency` comando produz um relatório baseado na análise dos dados no volume de repositório subjacente de um objeto especificado.



== Arrays compatíveis

Este comando se aplica a qualquer storage array individual, incluindo os arrays E2700, E5600, E2800, E5700, EF600 e EF300, desde que todos os pacotes SMcli estejam instalados.



== Funções

Para executar esse comando em um storage array E2800, E5700, EF600 ou EF300, você deve ter a função Administrador do armazenamento.



== Sintaxe

[listing, subs="+macros"]
----
check (snapGroup pass:quotes[[_snapGroupName_]] repositoryConsistency |
snapVolume pass:quotes[[_snapVolumeName_]] repositoryConsistency |
volume pass:quotes[[_volumeName_]] repositoryConsistency |
volumeCopy target pass:quotes[[_targetName_]] repositoryConsistency |
asyncMirrorGroup pass:quotes[[_asyncMirrorGroupName_]]
repositoryConsistency localVolume=pass:quotes[_"localVolumeName"_]]
file=pass:quotes[_"filePath"_]
----


== Parâmetros

|===
| Parâmetro | Descrição 


 a| 
`repositoryConsistency`
 a| 
Especifica que o grupo instantâneo, o volume instantâneo, o volume ou o grupo de espelhos assíncronos (dependendo do qual é especificado pelo parâmetro correspondente) estão verificados quanto à consistência.



 a| 
`snapGroup`
 a| 
O nome do grupo de instantâneos no qual executar uma verificação de consistência. Inclua o nome do grupo de instantâneos entre colchetes ([ ]). Se o nome do grupo instantâneo contiver carateres especiais ou consistir apenas em números, você também deve inserir o nome entre aspas duplas (" ") dentro de colchetes.



 a| 
`snapVolume`
 a| 
O nome do volume instantâneo no qual executar uma verificação de consistência. Inclua o nome do volume do instantâneo entre colchetes ([ ]). Se o nome do volume instantâneo contiver carateres especiais ou consistir apenas em números, você também deve inserir o nome entre aspas duplas (" ") dentro de colchetes.



 a| 
`volume`
 a| 
O nome do volume fino no qual executar uma verificação de consistência. Coloque o nome do volume fino entre colchetes ([ ]). Se o nome do volume fino contiver carateres especiais ou consistir apenas em números, você também deve incluir o nome entre aspas duplas (" ") dentro de colchetes.



 a| 
`volumeCopy`
 a| 
Especifica que o destino de uma relação de cópia de volume é verificado quanto à consistência.



 a| 
`target`
 a| 
Use somente em conjunto com o `volumeCopy` parâmetro para especificar o nome do volume que é o destino da relação de cópia de volume. Se o nome do volume contiver carateres especiais ou consistir apenas em números, você também deve inserir o nome entre aspas duplas (" ") dentro de colchetes.



 a| 
`asyncMirrorGroup`
 a| 
O nome do grupo de espelhos assíncronos no qual executar uma verificação de consistência. Inclua o nome do grupo de espelhos assíncronos entre colchetes ([ ]). Se o nome do grupo de espelhos assíncronos contiver carateres especiais ou consistir apenas em números, você também deve incluir o nome entre aspas duplas (" ") dentro de colchetes.



 a| 
`localVolume`
 a| 
Use somente com o `asyncMirrorGroup` parâmetro para especificar o nome de um volume local que participa da relação de espelhamento. Você pode especificar um volume local que seja a origem ou o destino em uma relação espelhada. Coloque o nome do volume local entre aspas duplas (" ").



 a| 
`file`
 a| 
O caminho do arquivo e o nome do arquivo para o qual você deseja salvar o relatório resultante da verificação de consistência. Coloque o nome do ficheiro entre aspas duplas (" "). Por exemplo:

`file="C:\Program Files\CLI\logs\repoConsistency.txt"` Este parâmetro deve aparecer por último, após qualquer um dos parâmetros opcionais.

|===


== Notas

O relatório gerado por este comando destina-se a ser utilizado pelo suporte técnico para analisar problemas.



== Nível mínimo de firmware

7,83
