---
permalink: commands-a-z/clear-volume-unreadablesectors.html 
sidebar: sidebar 
keywords: clear, volume, unreadable, sectors 
summary: O comando Clear volume unreadableSectors limpa informações ilegíveis do setor de um ou mais volumes. 
---
= Limpar setores ilegíveis de volume
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
O `clear volume unreadableSectors` comando limpa informações ilegíveis do setor de um ou mais volumes.



== Arrays compatíveis

Este comando se aplica a qualquer storage array individual, incluindo os arrays E4000, E2700, E5600, E2800, E5700, EF600 e EF300, desde que todos os pacotes SMcli estejam instalados.



== Funções

Para executar esse comando em um storage array E4000, E2800, E5700, EF600 ou EF300, você deve ter a função Administrador de armazenamento.



== Sintaxe

[source, cli, subs="+macros"]
----
clear (allVolumes | volume pass:quotes[[_volumeName_]] |
volumes pass:quotes[[_"volumeName1" ... "volumeNameN"_]]) unreadableSectors
----


== Parâmetros

|===
| Parâmetro | Descrição 


 a| 
`allVolumes`
 a| 
A configuração para limpar informações de setor ilegíveis de todos os volumes no storage array.



 a| 
`volume`
 a| 
O nome de um volume para o qual você está limpando informações ilegíveis do setor. Coloque o nome do volume entre colchetes ([ ]). Se o nome do volume contiver carateres especiais ou consistir apenas em números, você deve inserir o nome entre aspas duplas (" ") dentro de colchetes.



 a| 
`volumes`
 a| 
Os nomes de vários volumes para os quais você está limpando informações ilegíveis do setor. Digite os nomes dos volumes de membros usando estas regras:

* Inclua todos os nomes entre colchetes ([ ]).
* Coloque cada um dos nomes em aspas duplas (" ").
* Separe cada um dos nomes com um espaço.


|===


== Notas

Você pode usar qualquer combinação de carateres alfanuméricos, hífens e sublinhados para os nomes. Os nomes podem ter um máximo de 30 carateres.
