---
permalink: commands-a-z/create-snapgroup.html 
sidebar: sidebar 
keywords: create, snapshot, group 
summary: O comando Create snapGroup cria um novo grupo de instantâneos e o volume do repositório associado. 
---
= Criar grupo instantâneo
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
O `create snapGroup` comando cria um novo grupo de snapshot e o volume do repositório associado.



== Arrays compatíveis

Este comando se aplica a qualquer storage array individual, incluindo os arrays E4000, E2700, E5600, E2800, E5700, EF600 e EF300, desde que todos os pacotes SMcli estejam instalados.



== Funções

Para executar esse comando em um storage array E4000, E2800, E5700, EF600 ou EF300, você deve ter a função Administrador de armazenamento.



== Contexto

Um grupo de instantâneos contém uma sequência de imagens instantâneas de um volume base associado. Um grupo de instantâneos tem um volume de repositório que é utilizado para guardar dados para todas as imagens de instantâneos que fazem parte do grupo de instantâneos.

[NOTE]
====
Antes de criar um grupo de instantâneos, certifique-se de que um grupo de volumes com capacidade livre está disponível.

====


== Sintaxe

[source, cli, subs="+macros"]
----
create snapGroup userLabel=pass:quotes[_"snapGroupName_" sourceVolume=_"volumeName"_]
[(repositoryVolume="repos_xxxx" |
repositoryVolume=(pass:quotes[_volumeGroupName_] [capacity=capacityValue]) |
repositoryVolume=(pass:quotes[_diskPoolName_] [capacity=capacityValue]))]
[repositoryFullPolicy=(failBaseWrites | purgeSnapImages)]
[rollbackPriority=(highest | high | medium | low | lowest)]
[repositoryFullLimit=pass:quotes[_percentValue_]]
[autoDeleteLimit=pass:quotes[_numberOfSnapImages_]]|
[enableSchedule=(TRUE | FALSE)]
[schedule (immediate | pass:quotes[_snapshotSchedule_)]]
----


== Parâmetros

|===
| Parâmetro | Descrição 


 a| 
`userLabel`
 a| 
O nome que você deseja dar ao novo grupo instantâneo. Inclua o identificador do grupo instantâneo em aspas duplas (" ").



 a| 
`sourceVolume`
 a| 
O nome do volume que pretende utilizar como origem para as suas imagens instantâneas. Coloque o nome do volume de origem entre aspas duplas (" ").



 a| 
`repositoryVolume`
 a| 
O nome do volume do repositório que conterá os dados alterados do grupo de instantâneos.

Você tem duas opções para definir o nome de um volume de repositório:

* Use um volume de repositório existente: Nome
* Crie um novo volume de repositório quando executar este comando


O nome de um volume de repositório existente é composto por duas partes:

* O termo "repos"
* Um identificador numérico de quatro dígitos que o software de gerenciamento de armazenamento atribui ao nome do volume do repositório


Inclua o nome do volume do repositório existente entre aspas duplas (" ").

Se você quiser criar um novo volume de repositório ao executar este comando, você deve digitar o nome de um grupo de volumes ou de um pool de discos no qual deseja o volume do repositório. Opcionalmente, você também pode definir a capacidade do volume do repositório. Se você quiser definir a capacidade, você pode usar estes valores:

* Um valor inteiro que representa uma porcentagem da capacidade do volume base
* Um valor de fração decimal que representa uma porcentagem da capacidade de volume base
* Um tamanho específico para o volume do repositório. O tamanho é definido em unidades de `bytes` `KB` , , `MB`, `GB` `TB` ou .


Se você não usar a opção capacidade, o software de gerenciamento de storage define a capacidade para 20% da capacidade de volume base.

Quando você executa esse comando, o software de gerenciamento de storage cria o volume do repositório para o volume do snapshot.



 a| 
`repositoryFullPolicy`
 a| 
Define como o processamento de imagem instantânea continua se o volume do repositório do grupo de instantâneos estiver cheio. Você pode optar por falhar gravações de e/S no volume base (`failBaseWrites`) ou excluir (limpar) as imagens instantâneas  `purgeSnapImages`) no volume do repositório. A `purgeSnapImages` opção elimina as imagens instantâneas mais antigas para libertar espaço. A ação padrão é `purgeSnapImages`.



 a| 
`rollBackPriority`
 a| 
Determina se os recursos do sistema devem ser alocados à operação de reversão à custa do desempenho do sistema. Um valor de `high` indica que a operação de reversão é priorizada sobre todas as outras e/S do host Um valor de `low` indica que a operação de reversão deve ser executada com impactos mínimo na e/S do host O valor padrão é `medium`.



 a| 
`repositoryFullLimit`
 a| 
A porcentagem da capacidade do repositório na qual você recebe um aviso de que o volume do repositório do grupo de snapshot está quase cheio. Use valores inteiros. Por exemplo, um valor de 70 significa 70%. O valor padrão é 75.



 a| 
`autoDeleteLimit`
 a| 
Cada grupo de instantâneos pode ser configurado para executar a eliminação automática das suas imagens instantâneas, de modo a manter o número total de imagens instantâneas no grupo de instantâneos a um nível designado ou inferior a um nível designado. Quando esta opção está ativada, sempre que uma nova imagem instantânea for criada no grupo de instantâneos, o sistema elimina automaticamente a imagem instantânea mais antiga do grupo para cumprir o valor limite. Essa ação libera a capacidade do repositório para que ele possa ser usado para atender aos requisitos contínuos de cópia na gravação para as imagens snapshot restantes.



 a| 
`enableSchedule`
 a| 
Use este parâmetro para ativar ou desativar a capacidade de agendar uma operação de snapshot. Para ativar o agendamento de instantâneos, defina este parâmetro como `TRUE`. Para desativar o agendamento de instantâneos, defina este parâmetro como `FALSE`.

|===


== Notas

Cada nome do grupo de instantâneos deve ser exclusivo. Você pode usar qualquer combinação de carateres alfanuméricos, sublinhado (_), hífen (-) e libra ( no) para o rótulo do usuário. As etiquetas de utilizador podem ter um máximo de 30 carateres.

Para criar um grupo de instantâneos, tem de ter um volume de repositório associado no qual armazene as imagens de instantâneos. Você pode usar um volume de repositório existente ou criar um novo volume de repositório. Você pode criar o volume do repositório ao criar o grupo de instantâneos. Um volume de repositório de grupo instantâneo é um volume expansível que é estruturado como uma coleção concatenada de até 16 entidades de volume padrão. Inicialmente, um volume de repositório expansível tem apenas um único elemento. A capacidade do volume do repositório expansível é exatamente a do único elemento. Você pode aumentar a capacidade de um volume de repositório expansível anexando volumes padrão adicionais a ele. A capacidade de volume do repositório expansível composto torna-se então a soma das capacidades de todos os volumes padrão concatenados.

Um grupo de instantâneos tem uma ordenação rigorosa de imagens instantâneas com base no tempo em que cada imagem instantânea é criada. Uma imagem instantânea que é criada após outra imagem instantânea é um _sucessor_ em relação a essa outra imagem instantânea. Uma imagem instantânea que é criada antes de outra imagem instantânea é um _predecessor_ em relação a essa outra.

Um volume de repositório do grupo de snapshot deve atender a um requisito de capacidade mínima que é a soma dos seguintes:

* 32 MB para suportar sobrecarga fixa para o grupo de instantâneos e para o processamento de cópia na gravação.
* Capacidade para processamento de reversão, que é 1/5000th da capacidade do volume base.


A capacidade mínima é a imposição pelo firmware do controlador e pelo software de gerenciamento de storage.

Quando você cria um grupo de instantâneos pela primeira vez, ele não contém imagens instantâneas. Quando cria imagens instantâneas, adiciona as imagens instantâneas a um grupo de instantâneos. Utilize o `create snapImage` comando para criar imagens instantâneas e adicionar as imagens instantâneas a um grupo de instantâneos.

Um grupo instantâneo pode ter um destes estados:

* *Optimal* -- o grupo de instantâneos está operando normalmente.
* *Full* -- o repositório do grupo instantâneo está cheio. Não é possível efetuar operações adicionais de cópia em gravação. Este estado é possível apenas para grupos de instantâneos que têm a política Repository Full definida para falhar gravações base. Qualquer grupo de snapshot em um estado completo faz com que uma condição de necessidade de atenção seja postada para o storage array.
* *Over Threshold* -- o uso do volume do repositório do grupo instantâneo está em ou além do seu limite de alerta. Qualquer grupo de snapshot nesse estado faz com que uma condição de necessidade de atenção seja postada para o storage array.
* *Failed* -- o grupo de instantâneos encontrou um problema que deixou todas as imagens de instantâneos no grupo de instantâneos inutilizáveis. Por exemplo, certos tipos de falhas de volume do repositório podem causar um estado de falha. Para recuperar de um estado com falha, use o `revive snapGroup` comando.


Pode configurar cada grupo de instantâneos para eliminar automaticamente as imagens instantâneas utilizando o `autoDeleteLimit` parâmetro. Eliminar automaticamente as imagens instantâneas permite evitar ter de eliminar de forma rotineira, manualmente as imagens que não pretende e que podem impedir a criação de imagens instantâneas futuras porque o volume do repositório está cheio. Quando utiliza o `autoDeleteLimit` parâmetro, faz com que o software de gestão de armazenamento elimine automaticamente as imagens instantâneas, começando pelas mais antigas. O software de gestão de armazenamento elimina imagens instantâneas até atingir um número de imagens instantâneas que é igual ao número introduzido com `autoDeleteLimit` o parâmetro. Quando novas imagens instantâneas são adicionadas ao volume do repositório, o software de gestão de armazenamento elimina as imagens instantâneas mais antigas até que o `autoDeleteLimit` número do parâmetro seja atingido.

O `enableSchedule` parâmetro e o `schedule` parâmetro fornecem uma forma de agendar a criação de imagens instantâneas para um grupo de instantâneos. Usando esses parâmetros, você pode agendar snapshots diariamente, semanalmente ou mensalmente (por dia ou por data). O `enableSchedule` parâmetro liga ou desativa a capacidade de agendar instantâneos. Quando você ativa o agendamento, você usa o `schedule` parâmetro para definir quando deseja que os snapshots ocorram.

Esta tabela explica como usar as opções para o `schedule` parâmetro:

|===
| Parâmetro | Descrição 


 a| 
`schedule`
 a| 
Necessário para especificar parâmetros de programação.



 a| 
`immediate`
 a| 
Inicie a operação imediatamente. Este item é mutuamente exclusivo com quaisquer outros parâmetros de agendamento.



 a| 
`enableSchedule`
 a| 
Quando definido como `true`, a programação é ativada. Quando definido como `false`, a programação é desativada.

[NOTE]
====
A predefinição é `false`.

====


 a| 
`startDate`
 a| 
Uma data específica para iniciar a operação. O formato para introduzir a data é MM:DD:YY. O padrão é a data atual. Um exemplo dessa opção é `startDate=06:27:11`.



 a| 
`scheduleDay`
 a| 
Um dia da semana em que iniciar a operação. Pode ser todos ou um ou mais dos seguintes valores:

* `monday`
* `tuesday`
* `wednesday`
* `thursday`
* `friday`
* `saturday`
* `sunday`


[NOTE]
====
Inclua o valor entre parênteses. Por exemplo, `scheduleDay=(wednesday)`.

====
Mais de um dia pode ser especificado anexando os dias em um único conjunto de parênteses e separando cada dia com um espaço. Por exemplo, `scheduleDay=(monday wednesday friday)`.

[NOTE]
====
Este parâmetro não é compatível com uma programação mensal.

====


 a| 
`startTime`
 a| 
A hora de um dia em que iniciar a operação. O formato para introduzir a hora é HH:MM, onde HH é a hora e MM é o minuto após a hora. Utiliza um relógio de 24 horas. Por exemplo, 2:00 da tarde é 14:00. Um exemplo dessa opção é `startTime=14:27`.



 a| 
`scheduleInterval`
 a| 
Uma quantidade de tempo, em minutos, para ter como mínimo entre as operações.intervalo de programação não deve ser superior a 1440 (24 horas) e deve ser um múltiplo de 30.

Um exemplo dessa opção é `scheduleInterval=180`.



 a| 
`endDate`
 a| 
Uma data específica para parar a operação. O formato para introduzir a data é MM:DD:YY. Se nenhuma data de fim for desejada, você pode especificar `noEndDate`. Um exemplo dessa opção é `endDate=11:26:11`.



 a| 
`timesPerDay`
 a| 
O número de vezes para executar a operação em um dia. Um exemplo dessa opção é `timesPerDay=4`.



 a| 
`timezone`
 a| 
Especifica o fuso horário a ser usado para o agendamento. Pode ser especificado de duas maneiras:

* *GMT±HH:MM*
+
O desvio do fuso horário de GMT. Exemplo `timezone=GMT-06:00`: .

* * String de texto*
+
Cadeia de texto de fuso horário padrão, deve ser incluída entre aspas. Exemplo:``timezone="America/Chicago"``





 a| 
`scheduleDate`
 a| 
Um dia do mês em que realizar a operação. Os valores para os dias são numéricos e no intervalo de 1-31.

[NOTE]
====
Este parâmetro não é compatível com uma programação semanal.

====
Um exemplo da `scheduleDate` opção é `scheduleDate=("15")`.



 a| 
`month`
 a| 
Um mês específico para realizar a operação. Os valores para os meses são:

* `jan` - Janeiro
* `feb` - Fevereiro
* `mar` - Março
* `apr` - Abril
* `may` - Maio
* `jun` - Junho
* `jul` - Julho
* `aug` - Agosto
* `sep` - Setembro
* `oct` - Outubro
* `nov` - Novembro
* `dec` - Dezembro


[NOTE]
====
Inclua o valor entre parênteses. Por exemplo, `month=(jan)`.

====
Mais de um mês pode ser especificado encerrando os meses em um único conjunto de parênteses e separando cada mês com um espaço. Por exemplo, `month=(jan jul dec)`.

Utilize este parâmetro com o `scheduleDate` parâmetro para efetuar a operação num dia específico do mês.

[NOTE]
====
Este parâmetro não é compatível com uma programação semanal.

====
|===
Esta tabela explica como usar o `timeZone` parâmetro:

|===
| Nome do fuso horário | Desvio GMT 


 a| 
`Etc/GMT+12`
 a| 
`GMT-12:00`



 a| 
`Etc/GMT+11`
 a| 
`GMT-11:00`



 a| 
`Pacific/Honolulu`
 a| 
`GMT-10:00`



 a| 
`America/Anchorage`
 a| 
`GMT-09:00`



 a| 
`America/Santa_Isabel`
 a| 
`GMT-08:00`



 a| 
`America/Los_Angeles`
 a| 
`GMT-08:00`



 a| 
`America/Phoenix`
 a| 
`GMT-07:00`



 a| 
`America/Chihuahua`
 a| 
`GMT-07:00`



 a| 
`America/Denver`
 a| 
`GMT-07:00`



 a| 
`America/Guatemala`
 a| 
`GMT-06:00`



 a| 
`America/Chicago`
 a| 
`GMT-06:00`



 a| 
`America/Mexico_City`
 a| 
`GMT-06:00`



 a| 
`America/Regina`
 a| 
`GMT-06:00`



 a| 
`America/Bogota`
 a| 
`GMT-05:00`



 a| 
`America/New_York`
 a| 
`GMT-05:00`



 a| 
`Etc/GMT+5`
 a| 
`GMT-05:00`



 a| 
`America/Caracas`
 a| 
`GMT-04:30`



 a| 
`America/Asuncion`
 a| 
`GMT-04:00`



 a| 
`America/Halifax`
 a| 
`GMT-04:00`



 a| 
`America/Cuiaba`
 a| 
`GMT-04:00`



 a| 
`America/La_Paz`
 a| 
`GMT-04:00`



 a| 
`America/Santiago`
 a| 
`GMT-04:00`



 a| 
`America/St_Johns`
 a| 
`GMT-03:30`



 a| 
`America/Sao_Paulo`
 a| 
`GMT-03:00`



 a| 
`America/Buenos_Aires`
 a| 
`GMT-03:00`



 a| 
`America/Cayenne`
 a| 
`GMT-03:00`



 a| 
`America/Godthab`
 a| 
`GMT-03:00`



 a| 
`America/Montevideo`
 a| 
`GMT-03:00`



 a| 
`Etc/GMT+2`
 a| 
`GMT-02:00`



 a| 
`Atlantic/Azores`
 a| 
`GMT-01:00`



 a| 
`Atlantic/Cape_Verde`
 a| 
`GMT-01:00`



 a| 
`Africa/Casablanca`
 a| 
`GMT`



 a| 
`Etc/GMT`
 a| 
`GMT`



 a| 
`Europe/London`
 a| 
`GMT`



 a| 
`Atlantic/Reykjavik`
 a| 
`GMT`



 a| 
`Europe/Berlin`
 a| 
`GMT+01:00`



 a| 
`Europe/Budapest`
 a| 
`GMT+01:00`



 a| 
`Europe/Paris`
 a| 
`GMT+01:00`



 a| 
`Europe/Warsaw`
 a| 
`GMT+01:00`



 a| 
`Africa/Lagos`
 a| 
`GMT+01:00`



 a| 
`Africa/Windhoek`
 a| 
`GMT+01:00`



 a| 
`Asia/Anman`
 a| 
`GMT+02:00`



 a| 
`Asia/Beirut`
 a| 
`GMT+02:00`



 a| 
`Africa/Cairo`
 a| 
`GMT+02:00`



 a| 
`Asia/Damascus`
 a| 
`GMT+02:00`



 a| 
`Africa/Johannesburg`
 a| 
`GMT+02:00`



 a| 
`Europe/Kiev`
 a| 
`GMT+02:00`



 a| 
`Asia/Jerusalem`
 a| 
`GMT+02:00`



 a| 
`Europe/Istanbul`
 a| 
`GMT+03:00`



 a| 
`Europe/Minsk`
 a| 
`GMT+02:00`



 a| 
`Asia/Baghdad`
 a| 
`GMT+03:00`



 a| 
`Asia/Riyadh`
 a| 
`GMT+03:00`



 a| 
`Africa/Nairobi`
 a| 
`GMT+03:00`



 a| 
`Asia/Tehran`
 a| 
`GMT+03:30`



 a| 
`Europe/Moscow`
 a| 
`GMT+04:00`



 a| 
`Asia/Dubai`
 a| 
`GMT+04:00`



 a| 
`Asia/Baku`
 a| 
`GMT+04:00`



 a| 
`Indian/Mauritius`
 a| 
`GMT+04:00`



 a| 
`Asia/Tbilisi`
 a| 
`GMT+04:00`



 a| 
`Asia/Yerevan`
 a| 
`GMT+04:00`



 a| 
`Asia/Kabul`
 a| 
`GMT+04:30`



 a| 
`Asia/Karachi`
 a| 
`GMT+05:00`



 a| 
`Asia//Tashkent`
 a| 
`GMT+05:00`



 a| 
`Asia/Calcutta`
 a| 
`GMT+05:30`



 a| 
`Asia/Colombo`
 a| 
`GMT+05:30`



 a| 
`Asia/Katmandu`
 a| 
`GMT+05:45`



 a| 
`Asia/Yekaterinburg`
 a| 
`GMT+06:00`



 a| 
`Asia/Almaty`
 a| 
`GMT+06:00`



 a| 
`Asia/Dhaka`
 a| 
`GMT+06:00`



 a| 
`Asia/Rangoon`
 a| 
`GMT+06:30`



 a| 
`Asia/Novosibirsk`
 a| 
`GMT+07:00`



 a| 
`Asia/Bangkok`
 a| 
`GMT+07:00`



 a| 
`Asia/Krasnoyarsk`
 a| 
`GMT+08:00`



 a| 
`Asia/Shanghai`
 a| 
`GMT+08:00`



 a| 
`Asia/Singapore`
 a| 
`GMT+08:00`



 a| 
`Australia/Perth`
 a| 
`GMT+08:00`



 a| 
`Asia/Taipei`
 a| 
`GMT+08:00`



 a| 
`Asia/Ulaanbaatar`
 a| 
`GMT+08:00`



 a| 
`Asia/Irkutsk`
 a| 
`GMT+09:00`



 a| 
`Asia/Tokyo`
 a| 
`GMT+09:00`



 a| 
`Asia/Seoul`
 a| 
`GMT+09:00`



 a| 
`Australia/Adelaide`
 a| 
`GMT+09:30`



 a| 
`Australia/Darwin`
 a| 
`GMT+09:30`



 a| 
`Asia/Yakutsk`
 a| 
`GMT+10:00`



 a| 
`Australia/Brisbane`
 a| 
`GMT+10:00`



 a| 
`Australia/Sydney`
 a| 
`GMT+10:00`



 a| 
`Pacific/Port Moresby`
 a| 
`GMT+10:00`



 a| 
`Australia/Hobart`
 a| 
`GMT+10:00`



 a| 
`Asia/Vladivostok`
 a| 
`GMT+11:00`



 a| 
`Pacific/Guadalcanal`
 a| 
`GMT+11:00`



 a| 
`Pacific/Auckland`
 a| 
`GMT+12:00`



 a| 
`Etc/GMT-12`
 a| 
`GMT+12:00`



 a| 
`Pacific/Fiji`
 a| 
`GMT+12:00`



 a| 
`Asia/Kamchatka`
 a| 
`GMT+12:00`



 a| 
`Pacific/Tongatapu`
 a| 
`GMT+13:00`

|===
A string de código para definir uma programação é semelhante a estes exemplos:

[listing]
----
enableSchedule=true schedule startTime=14:27
----
[listing]
----
enableSchedule=true schedule scheduleInterval=180
----
[listing]
----
enableSchedule=true schedule timeZone=GMT-06:00
----
[listing]
----
enableSchedule=true schedule timeZone="America/Chicago"
----
Se você também usar a `scheduleInterval` opção, o firmware escolhe entre a `timesPerDay` opção e a `scheduleInterval` opção selecionando o valor mais baixo das duas opções. O firmware calcula um valor inteiro para a `scheduleInterval` opção dividindo 1440 pelo `scheduleInterval` valor de opção definido. Por exemplo, 1440/180 é 8. O firmware então compara o `timesPerDay` valor inteiro com o valor inteiro calculado `scheduleInterval` e usa o valor menor.

Para remover um agendamento, use o `delete volume` comando com o `schedule` parâmetro. O `delete volume` comando com o `schedule` parâmetro exclui apenas a programação, não o volume instantâneo.



== Nível mínimo de firmware

7,83

7,86 adiciona a `scheduleDate` opção e a `month` opção.
