---
permalink: commands-a-z/create-raid-volume-free-extent-based-select.html 
sidebar: sidebar 
keywords: create, raid, volume, free, extent, based, select 
summary: O comando criar volume cria um volume no espaço livre de um grupo de volumes. 
---
= Criar volume RAID (seleção baseada em extensão livre)
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
O `create volume` comando cria um volume no espaço livre de um grupo de volumes.



== Arrays compatíveis

Este comando se aplica a qualquer storage array individual, incluindo os arrays E2700, E5600, E2800, E5700, EF600 e EF300, desde que todos os pacotes SMcli estejam instalados.



== Funções

Para executar esse comando em um storage array E2800, E5700, EF600 ou EF300, você deve ter a função Administrador do armazenamento.



== Sintaxe

[listing, subs="+macros"]
----
create volume volumeGroup=pass:quotes[_"volumeGroupName"_
userLabel="_volumeName"_]
[freeCapacityArea=pass:quotes[_freeCapacityIndexNumber_]]
[capacity=pass:quotes[_volumeCapacity_]]
[owner=(a|b)]
[mapping=(none | default)]
[cacheReadPrefetch=(TRUE | FALSE)]
[segmentSize=pass:quotes[_segmentSizeValue_]]
[usageHint=(fileSystem | dataBase | multiMedia)]
[dssPreAllocate=(TRUE | FALSE)]
[securityType=(none | capable | enabled)]
[dataAssurance=(none | enabled)]
[blockSize=blockSizeValue]
----


== Parâmetros

|===
| Parâmetro | Descrição 


 a| 
`volumeGroup`
 a| 
O nome de um grupo de volumes específico em seu storage array. Coloque o nome do grupo de volume entre aspas duplas (" ").



 a| 
`userLabel`
 a| 
O nome que você deseja dar ao novo volume. Coloque o novo nome do volume entre aspas duplas (" ").

[NOTE]
====
Este parâmetro é obrigatório.

====


 a| 
`freeCapacityArea`
 a| 
O número de índice do espaço livre em um grupo de volumes existente que você deseja usar para criar o novo volume. A capacidade livre é definida como a capacidade livre entre os volumes existentes em um grupo de volumes. Por exemplo, um grupo de volumes pode ter as seguintes áreas: Volume 1, capacidade livre, volume 2, capacidade livre, volume 3, capacidade livre. Para utilizar a capacidade livre seguinte ao volume 2, introduza este número de índice:

`freeCapacityArea=2`

[NOTE]
====
Execute o `show volumeGroup` comando para determinar se a área de capacidade livre existe.

====
[NOTE]
====
Se este parâmetro não for especificado, o volume é criado na área de capacidade livre com número mais baixo, com capacidade suficiente para o volume.

====


 a| 
`capacity`
 a| 
O tamanho do volume que você está adicionando ao storage array. O tamanho é definido em unidades de `bytes` `KB` , , `MB`, `GB` `TB` ou .



 a| 
`owner`
 a| 
O controlador que possui o volume. Os identificadores válidos do controlador são `a` ou `b`, onde `a` está o controlador no slot A e `b` é o controlador no slot B. se você não especificar um proprietário, o firmware do controlador determina o proprietário.



 a| 
`cacheReadPrefetch`
 a| 
A configuração para ativar ou desativar o cache ler pré-busca. Para ativar a pré-busca de leitura de cache, defina este parâmetro como `TRUE`. Para desativar a pré-busca de leitura de cache, defina este parâmetro como `FALSE`.



 a| 
`segmentSize`
 a| 
A quantidade de dados (em KB) que o controlador grava em uma única unidade em um volume antes de gravar dados na próxima unidade. Os valores válidos são `8` `16` , `32`, `64`, , , `128`, `256`, ou `512`.



 a| 
`usageHint`
 a| 
As configurações para o `cacheReadPrefetch` parâmetro e o `segmentSize` parâmetro são valores padrão. Os valores padrão são baseados no padrão de uso de e/S típico da aplicação que está usando o volume. Os valores válidos são `fileSystem`, `dataBase`, `multiMedia` ou .



 a| 
`dssPreAllocate`
 a| 
A configuração para garantir que a capacidade de reserva seja alocada para o tamanho futuro do segmento aumenta. O valor padrão é `TRUE`.



 a| 
`securityType`
 a| 
A configuração para especificar o nível de segurança ao criar os grupos de volumes e todos os volumes associados. Estas definições são válidas:

`none` -- o grupo de volumes e os volumes não são seguros.

`capable` -- o grupo de volumes e os volumes são capazes de ter a segurança definida, mas a segurança não foi ativada.

`enabled` -- o grupo de volumes e os volumes têm a segurança ativada.



 a| 
`mapping`
 a| 
Este parâmetro permite mapear o volume para um host. Se pretender mapear mais tarde, defina este parâmetro como `none`. Se pretender mapear agora, defina este parâmetro como `default`. O volume é mapeado para todos os hosts que têm acesso ao pool de armazenamento. O valor padrão é `none`.



 a| 
`blockSize`
 a| 
Este parâmetro define o tamanho do bloco do volume que está sendo criado. Um valor de 0 ou o parâmetro não definido usa o tamanho padrão do bloco.

|===


== Notas

Você pode usar qualquer combinação de carateres alfanuméricos, hífens e sublinhados para os nomes. Os nomes podem ter um máximo de 30 carateres.

O `owner` parâmetro define qual controlador possui o volume. A propriedade preferida do controlador de um volume é o controlador que atualmente possui o grupo de volumes.

Se você não especificar uma capacidade usando o `capacity` parâmetro, toda a capacidade disponível na área de capacidade livre do grupo de volume será usada. Se você não especificar unidades de capacidade, `bytes` será usado como o valor padrão.



== Tamanho do segmento

O tamanho de um segmento determina quantos blocos de dados o controlador grava em uma única unidade em um volume antes de gravar dados na próxima unidade. Cada bloco de dados armazena 512 bytes de dados. Um bloco de dados é a menor unidade de armazenamento. O tamanho de um segmento determina quantos blocos de dados contém. Por exemplo, um segmento de 8 KB contém 16 blocos de dados. Um segmento de 64 KB contém 128 blocos de dados.

Quando você insere um valor para o tamanho do segmento, o valor é verificado em relação aos valores suportados fornecidos pelo controlador no tempo de execução. Se o valor inserido não for válido, o controlador retornará uma lista de valores válidos. O uso de uma única unidade para uma única solicitação deixa outras unidades disponíveis para atender simultaneamente a outras solicitações. Se o volume estiver em um ambiente onde um único usuário está transferindo grandes unidades de dados (como Multimídia), o desempenho é maximizado quando uma única solicitação de transferência de dados é atendida com uma única faixa de dados. (Uma faixa de dados é o tamanho do segmento que é multiplicado pelo número de unidades no grupo de volumes que são usadas para transferências de dados.) Neste caso, várias unidades são usadas para a mesma solicitação, mas cada unidade é acessada apenas uma vez.

Para obter o desempenho ideal em um ambiente de armazenamento de sistemas de arquivos ou banco de dados multiusuário, defina o tamanho do segmento para minimizar o número de unidades necessárias para atender a uma solicitação de transferência de dados.



== Dica de utilização

[NOTE]
====
Não é necessário introduzir um valor para o `cacheReadPrefetch` parâmetro ou para o `segmentSize` parâmetro. Se não introduzir um valor, o firmware do controlador utiliza o `usageHint` parâmetro com `fileSystem` como valor predefinido. Introduzir um valor para o `usageHint` parâmetro e um valor para o `cacheReadPrefetch` parâmetro ou um valor para o `segmentSize` parâmetro não causa um erro. O valor inserido para o parâmetro ou para `cacheReadPrefetch` o `segmentSize` parâmetro tem prioridade sobre o valor do `usageHint` parâmetro. O tamanho do segmento e as configurações de pré-busca de leitura de cache para várias dicas de uso são mostrados na tabela a seguir:

====
|===
| Dica de uso | Definição do tamanho do segmento | Configuração de pré-busca de leitura de cache dinâmico 


 a| 
Sistema de arquivos
 a| 
128 KB
 a| 
Ativado



 a| 
Banco de dados
 a| 
128 KB
 a| 
Ativado



 a| 
Multimédia
 a| 
256 KB
 a| 
Ativado

|===


== Cache lê pré-busca

A pré-busca de leitura de cache permite que o controlador copie blocos de dados adicionais no cache enquanto o controlador lê e copia blocos de dados solicitados pelo host da unidade para o cache. Essa ação aumenta a chance de que uma futura solicitação de dados possa ser atendida a partir do cache. A pré-busca de leitura de cache é importante para aplicativos Multimídia que usam transferências de dados sequenciais. Os valores válidos para o `cacheReadPrefetch` parâmetro são `TRUE` ou `FALSE`. A predefinição é `TRUE`.



== Tipo de segurança

Use o `securityType` parâmetro para especificar as configurações de segurança do storage array.

Antes de definir o `securityType` parâmetro como `enabled`, você deve criar uma chave de segurança do storage array. Use o `create storageArray securityKey` comando para criar uma chave de segurança de storage array. Estes comandos estão relacionados com a chave de segurança:

* `create storageArray securityKey`
* `export storageArray securityKey`
* `import storageArray securityKey`
* `set storageArray securityKey`
* `enable volumeGroup [volumeGroupName] security`
* `enable diskPool [diskPoolName] security`




== Nível mínimo de firmware

7,10 adiciona o `dssPreAllocate` parâmetro.

7,50 adiciona o `securityType` parâmetro.

7,75 adiciona o `dataAssurance` parâmetro.

11,70 adiciona o `blockSize` parâmetro.
