---
permalink: commands-a-z/create-mapping-volume.html 
sidebar: sidebar 
keywords: create, volume, map 
summary: O comando criar volume de mapeamento cria um mapeamento lógico de um volume para um host ou um grupo de host. 
---
= Criar mapeamento de volume
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
O `create mapping volume` comando cria um mapeamento lógico de um volume para um host ou um grupo de host.



== Arrays compatíveis

Este comando se aplica a qualquer storage array individual, incluindo os arrays E4000, E2700, E5600, E2800, E5700, EF600 e EF300, desde que todos os pacotes SMcli estejam instalados.



== Funções

Para executar esse comando em um storage array E4000, E2800, E5700, EF600 ou EF300, você deve ter a função Administrador de armazenamento.



== Sintaxe

[source, cli, subs="+macros"]
----
create mapping volume=pass:quotes[_"VolumeName"_
(host="_hostName_" | hostGroup=("_hostGroupName_"] | defaultGroup))
logicalUnitNumber=lun
mapWaitPeriod=mapWaitPeriodValue
----


== Parâmetros

|===
| Parâmetro | Descrição 


 a| 
`Volume`
 a| 
O nome do volume para o qual você deseja criar um mapeamento lógico. Coloque o nome do volume entre aspas duplas (" ").



 a| 
`host`
 a| 
O nome de um host para o qual você deseja criar um mapeamento lógico. Inclua o nome do host em aspas duplas (" ").



 a| 
`hostGroup`
 a| 
O nome de um grupo de host para o qual você deseja criar um mapeamento lógico. Coloque o nome do grupo anfitrião em aspas duplas (" "). Se você usar a `defaultGroup` palavra-chave, não a coloque entre aspas.



 a| 
`logicalUnitNumber`
 a| 
O número lógico ou o ID do namespace que você deseja usar para mapear para um host específico. Esse parâmetro também atribui o host a um grupo de hosts.

[NOTE]
====
O número de unidade lógica ou o ID do namespace especificado não deve estar já em uso e deve estar dentro do intervalo suportado pelo sistema operacional host. Não haverá erro se você mapear o volume para um número de unidade lógica ou ID de namespace não suportado pelo host, mas o host não poderá acessar o volume.

====


 a| 
`mapWaitPeriod`
 a| 
Bloqueia o mapeamento até que ele seja capaz de completar o comando ou o tempo limite para não afetar a interação. Se um valor não for inserido, o comportamento padrão é falhar a ação se o volume não puder ser mapeado imediatamente.

|===


== Nível mínimo de firmware

7,83

8,63 adiciona o parâmetro mapWaitPeriod.
