---
permalink: commands-a-z/create-storagearray-syslog.html 
sidebar: sidebar 
keywords: create, storage, array, syslog, configuration 
summary: O comando Create storageArray syslog permite arquivar logs de auditoria em um servidor syslog externo. Depois que uma conexão é estabelecida entre o storage array e o servidor syslog, os logs de auditoria são salvos automaticamente no servidor syslog. 
---
= Crie a configuração syslog array de storage
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
O `create storageArray syslog` comando permite arquivar logs de auditoria em um servidor syslog externo. Depois que uma conexão é estabelecida entre o storage array e o servidor syslog, os logs de auditoria são salvos automaticamente no servidor syslog.



== Arrays compatíveis

Este comando se aplica a um storage array individual de armazenamento E2800, E5700, EF600 ou EF300. Ele não opera em matrizes de armazenamento E2700 ou E5600.



== Funções

Para executar esse comando em um storage array E2800, E5700, EF600 ou EF300, você deve ter a função Security Admin.



== Sintaxe

[listing]
----

create storageArray syslog serverAddress="<address>" port=<port> protocol=("udp" | "tcp" | "tls") components=(componentName=("auditLog") ...)
----


== Parâmetros

|===
| Parâmetro | Descrição 


 a| 
`serverAddress`
 a| 
Nome do host ou endereço IP do recetor syslog.



 a| 
`port`
 a| 
Número da porta do recetor syslog.



 a| 
`protocol`
 a| 
Protocolo de transmissão syslog. Os valores aceitáveis incluem udp, tcp ou tls.



 a| 
`components`
 a| 
Lista de entradas de componentes que serão registradas no servidor syslog. Atualmente, apenas os logs de auditoria são suportados.



 a| 
`componentName`
 a| 
Nome do componente; atualmente apenas é suportado "Auditlog".

|===


=== Exemplo

[listing]
----
SMcli -n Array1 -c "create storageArray syslog
serverAddress=\"192.168.2.1\" port=514 protocol=\"udp\"
components=(componentName=\"auditLog\");"
ID: 331998fe-3154-4489-b773-b0bb60c6b48e
Server Address: 192.168.2.1.com
Port: 514
Protocol: udp
Components
1. Component Name: auditLog
SMcli completed successfully.
----


== Nível mínimo de firmware

8,42
