---
permalink: commands-a-z/delete-storagearray-directoryservers.html 
sidebar: sidebar 
keywords: delete, storage, array, directory, servers, command, allow, directory, role 
summary: O comando delete storageArray directoryServers permite excluir um ou mais servidores de diretório. 
---
= Eliminar servidor de diretório de matriz de armazenamento
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
O `delete storageArray directoryServers` comando permite excluir um ou mais servidores de diretório.



== Arrays compatíveis

Este comando se aplica a um storage array individual de armazenamento E2800, E5700, EF600 ou EF300. Ele não opera em matrizes de armazenamento E2700 ou E5600.



== Funções

Para executar esse comando em um storage array E2800, E5700, EF600 ou EF300, você deve ter a função Security Admin.



== Sintaxe

[listing, subs="+macros"]
----
pass:quotes[delete storageArray (allDirectoryServers |
 directoryServers ["_domainId1_" ... "_domainIdN_"])
----


== Parâmetros

[cols="2*"]
|===
| Parâmetro | Descrição 


 a| 
`allDirectoryServers`
 a| 
Permite eliminar todos os servidores de diretório.



 a| 
`directoryServers`
 a| 
Permite especificar um ou mais servidores de diretório a serem excluídos, cada um identificado com o ID do domínio.

[NOTE]
====
Inclua as IDs entre colchetes ([ ]). Se você forneceu mais de um, separe-os com um espaço.

====
|===


== Exemplos

[listing]
----

SMcli -n Array1 -c "delete storageArray directoryServers ["domain1" "domain3"];"

SMcli -n Array1 -c "delete storageArray allDirectoryServers;"

SMcli completed successfully.
----


== Nível mínimo de firmware

8,40 adiciona o comando.
