---
permalink: commands-a-z/delete-ssdcache.html 
sidebar: sidebar 
keywords: delete, cache, command, data, purged, array, support, role, parameter 
summary: O comando delete ssdCache exclui o cache SSD. Todos os dados no cache SSD são purgados. 
---
= Eliminar cache SSD
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
 `delete ssdCache`O comando exclui o cache SSD. Todos os dados no cache SSD são purgados.



== Arrays compatíveis

Este comando se aplica a qualquer storage array individual, incluindo os arrays E2700, E5600, E2800, E5700, EF600 e EF300, desde que todos os pacotes SMcli estejam instalados.



== Funções

Para executar esse comando em um storage array E2800, E5700, EF600 ou EF300, você deve ter a função Administrador de suporte.



== Sintaxe

[listing, subs="+macros"]
----
pass:quotes[delete ssdCache [_ssdCacheName_]]
----


== Parâmetro

[cols="2*"]
|===
| Parâmetro | Descrição 


 a| 
`ssdCache`
 a| 
O nome do cache SSD que você deseja excluir. Inclua o nome do cache SSD entre colchetes ([ ]). Se o nome do cache SSD contiver carateres especiais ou consistir apenas em números, você deve incluir o nome do cache SSD em aspas duplas (" ") dentro de colchetes.

|===


== Nível mínimo de firmware

7,84

O 11,80 adiciona suporte a array EF600 e EF300
