---
permalink: commands-a-z/disable-storagearray.html 
sidebar: sidebar 
keywords: disable, storage, array, command, storage, feature 
summary: O comando Disable storageArray desativa um recurso de storage array. 
---
= Desativar o recurso de storage array
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
O `disable storageArray` comando desativa um recurso de storage array.



== Arrays compatíveis

Este comando se aplica a qualquer storage array individual, incluindo os arrays E4000, E2700, E5600, E2800, E5700, EF600 e EF300, desde que todos os pacotes SMcli estejam instalados.



== Funções

Para executar esse comando em um storage array E4000, E2800, E5700, EF600 ou EF300, você deve ter a função Administrador de armazenamento.



== Contexto

Execute o `show storageArray` comando para mostrar uma lista dos identificadores de recursos para todos os recursos habilitados na matriz de armazenamento.



== Sintaxe

[source, cli, subs="+macros"]
----
pass:quotes[disable storageArray (featurePack | feature=_featureAttributeList_)]
----
Pass:quotes[o `_featureAttributeList_`] pode ser um ou mais desses valores de atributo. Se você inserir mais de um valor de atributo, separe os valores com um espaço.

* `driveSecurity`




== Parâmetros

Nenhum.



== Nível mínimo de firmware

8,20 adiciona o `driveSecurity` atributo e remove todos os outros atributos.
