---
permalink: commands-a-z/download-controller-cacertificate.html 
sidebar: sidebar 
keywords: download, controller, certificate, command, install, root, intermediate, web, servers, validate, array, roles, context 
summary: O comando caCertificate do controlador de download instala os certificados de CA raiz/intermediária nos servidores da Web dos controladores para validar o certificado assinado do servidor da Web. 
---
= Instale certificados de CA raiz/intermediário
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
O `download controller caCertificate` comando instala os certificados de CA raiz/intermediária nos servidores da Web dos controladores para validar o certificado assinado pelo servidor da Web.



== Arrays compatíveis

Esse comando se aplica a um storage array individual de armazenamento E4000, E2800, E5700, EF600 ou EF300. Ele não opera em matrizes de armazenamento E2700 ou E5600.



== Funções

Para executar esse comando em um storage array E4000, E2800, E5700, EF600 ou EF300, você deve ter a função Security Admin.



== Contexto

Execute esta ação para cada controlador.



== Sintaxe

[source, cli, subs="+macros"]
----
download controller[(a|b)] caCertificate pass:quotes[[alias="_string_"]]
         pass:quotes[file="_filename_"]
----


== Parâmetros

[cols="2*"]
|===
| Parâmetro | Descrição 


 a| 
`controller`
 a| 
Permite especificar o controlador no qual deseja instalar o certificado assinado raiz/intermediário. Identificadores válidos do controlador são a ou b, onde a é o controlador no slot A, e b é o controlador no slot B. feche o identificador do controlador entre colchetes ([ ]).



 a| 
`alias`
 a| 
Permite especificar um alias para representar o certificado raiz/intermediário. Esse alias é usado para procurar informações sobre os certificados raiz/intermediário ou para excluí-los. Um alias está associado a um certificado raiz/intermediário e deve ser exclusivo.



 a| 
`file`
 a| 
Permite especificar o ficheiro que contém o certificado de CA raiz/intermédia. As extensões aceitáveis são .pem, .cer, .crt e .der.

|===


== Exemplos

[listing]
----

SMcli -n Array1 -c "download controller[a] caCertificate alias="myAlias" file="C:\rootCA1.cer";"
SMcli -n Array1 -c "download controller[b] caCertificate file="C:\rootCA1.cer";"

SMcli completed successfully.
----


== Nível mínimo de firmware

8,40
