---
permalink: commands-a-z/download-controller-arraymanagementservercertificate.html 
sidebar: sidebar 
keywords: download, controller, array, management, server, certificate, command, install 
summary: O comando download controller arrayManagementServerCertificate instala o certificado do servidor no controlador. 
---
= Instale o certificado assinado pelo servidor
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
O `download controller arrayManagementServerCertificate` comando instala o certificado do servidor no controlador.



== Arrays compatíveis

Esse comando se aplica a um storage array individual de armazenamento E4000, E2800, E5700, EF600 ou EF300. Ele não opera em matrizes de armazenamento E2700 ou E5600.



== Funções

Para executar esse comando em um storage array E4000, E2800, E5700, EF600 ou EF300, você deve ter a função Security Admin.



== Contexto

Execute esta ação para cada controlador usando o certificado assinado aplicável ao controlador. O certificado assinado deve incluir os nomes IPs/DNS do controlador.



== Sintaxe

[source, cli, subs="+macros"]
----
download controller [(a|b)] pass:quotes[arrayManagementServerCertificate file="_filename_"]
----


== Parâmetros

[cols="2*"]
|===
| Parâmetro | Descrição 


 a| 
`controller`
 a| 
Permite ao utilizador especificar o controlador para o qual pretende instalar o certificado assinado pelo servidor. Identificadores válidos do controlador são a ou b, onde a é o controlador no slot A, e b é o controlador no slot B. feche o identificador do controlador entre colchetes ([ ]).



 a| 
`file`
 a| 
Permite que o usuário especifique o caminho do arquivo e o nome do arquivo que contém o certificado assinado. As extensões aceitáveis são .cer, .crt, .der.

|===


== Exemplos

[listing]
----

SMcli -n Array1 -c "download controller [a] arrayManagementServerCertificate
   file="C:\serverSignedCertificateA.cer";"

SMcli -n Array1 -c "download controller [b] arrayManagementServerCertificate
   file="C:\serverSignedCertificateB.cer";"

SMcli completed successfully.
----


== Nível mínimo de firmware

8,40
