---
permalink: commands-a-z/download-drive-firmware.html 
sidebar: sidebar 
keywords: download, drive, firmware, array, support, role, context, level 
summary: O comando download do firmware da unidade faz download de uma imagem de firmware para uma unidade. 
---
= Transfira o firmware da unidade
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
O `download drive firmware` comando baixa uma imagem de firmware para uma unidade.



== Arrays compatíveis

Este comando se aplica a qualquer storage array individual, incluindo os arrays E2700, E5600, E2800, E5700, EF600 e EF300, desde que todos os pacotes SMcli estejam instalados.



== Funções

Para executar esse comando em um storage array E2800, E5700, EF600 ou EF300, você deve ter a função Administrador de armazenamento ou Administrador de suporte.



== Contexto

[CAUTION]
====
*Possíveis danos à configuração da matriz de armazenamento* -- o download incorreto do firmware da unidade pode resultar em danos às unidades ou perda de acesso aos dados.

====
[NOTE]
====
O `content` parâmetro está obsoleto. Use o `firmware` parâmetro em vez disso.

====
Este comando destina-se a transferir uma imagem de firmware para apenas um modelo de unidade de cada vez. Se você usar esse comando em um script, certifique-se de usar esse comando apenas uma vez. Se você usar este comando mais de uma vez, a operação pode falhar. Você pode baixar imagens de firmware para todas as unidades em um storage de armazenamento de uma só vez usando o `download storageArray driveFirmware` comando.



== Sintaxe

[listing, subs="+macros"]
----
pass:quotes[download (drive \[_trayID_,[_drawerID,_]pass:quotes[_slotID_] \| drives\ pass:quotes[[_trayID1_,[_drawerID1_,]slotID1 ... trayIDn,[drawerIDn,]slotIDn\])
 [online|offline] firmware file="filename"
----


== Parâmetros

[cols="2*"]
|===
| Parâmetro | Descrição 


 a| 
`drive` ou `drives`
 a| 
Para bandejas de unidades de alta capacidade, especifique o valor de ID da bandeja, o valor de ID da gaveta e o valor de ID do slot para a unidade. Para bandejas de unidades de baixa capacidade, especifique o valor de ID da bandeja e o valor de ID do slot para a unidade. Os valores de ID da bandeja são `0` para `99`. Os valores de ID da gaveta são `1` para `5`.

Todos os máximos de ID de slot são 24. Os valores de ID do slot começam em 0 ou 1, dependendo do modelo da bandeja. As bandejas de unidades compatíveis com os controladores E2800 e E5700 têm números de ID de slot a partir de 0. As bandejas de unidades compatíveis com os controladores E2700 e E5600 têm números de ID de slot a partir de 1.

Inclua o valor de ID da bandeja, o valor de ID da gaveta e o valor de ID do slot entre colchetes ([ ]).



 a| 
`online` ou `offline`
 a| 
 `online`Selecione para efetuar uma transferência do firmware da unidade online; caso contrário, `offline`selecione . O valor padrão é `offline`.



 a| 
`file`
 a| 
O caminho do ficheiro e o nome do ficheiro que contém a imagem de firmware. Insira o caminho do arquivo e o nome do arquivo da imagem de firmware em aspas duplas (" "). Por exemplo:

`file="C:\Program Files\CLI\dnld\drvfrm.dlp"`

Nomes de arquivo válidos têm `.dlp` uma extensão.



 a| 
`firmware`
 a| 
Indica para baixar o firmware do controlador.

|===


== Notas

Antes de tentar transferir o firmware da unidade, tome estas precauções:

* A menos que você esteja usando o `online` parâmetro, interrompa toda a atividade de e/S para o storage array antes de baixar a imagem de firmware. O `download drive firmware` comando sem o `online` parâmetro bloqueia toda a atividade de e/S até que o download termine ou falhe; no entanto, como precaução, certifique-se de que toda a atividade de e/S que possa afetar a unidade esteja parada.
* Certifique-se de que o ficheiro de imagem de firmware é compatível com a bandeja de unidades Se transferir um ficheiro de imagem de firmware que não seja compatível com a bandeja de unidades selecionada, a bandeja de unidades poderá ficar inutilizável.
* Não faça alterações de configuração no storage de armazenamento enquanto você baixa o firmware da unidade. Tentar fazer uma alteração de configuração pode fazer com que o download do firmware falhe e inutilizar as unidades selecionadas.
* Para solicitações de atualização de firmware de unidade on-line emitidas usando este comando, a controladora removerá unidades de grupo de volume RAID 0 da lista de unidades para as quais o novo firmware é baixado. O status de retorno individual da unidade será definido como `Never Attempted With Reason`.


Quando transferir o firmware para as unidades, tem de fornecer o caminho completo e o nome do ficheiro para a imagem de firmware armazenada no sistema.

Você pode usar `download drive` o comando para testar o firmware em uma unidade antes de instalar o firmware em todas as unidades em uma matriz de armazenamento. O download retorna um destes status:

* Bem-sucedido
* Sem sucesso com motivo
* Nunca tentou com razão


 `drive`O parâmetro dá suporte a bandejas de unidades de alta capacidade e bandejas de unidades de baixa capacidade. Uma bandeja de unidades de alta capacidade tem gavetas que prendem as unidades. As gavetas deslizam para fora da bandeja de unidades para fornecer acesso às unidades. Uma bandeja de unidades de baixa capacidade não tem gavetas. Para uma bandeja de unidades de alta capacidade, você deve especificar o identificador (ID) da bandeja de unidades, o ID da gaveta e o ID do slot no qual uma unidade reside. Para uma bandeja de unidades de baixa capacidade, você precisa especificar apenas o ID da bandeja de unidades e o ID do slot em que uma unidade reside. Para uma bandeja de unidades de baixa capacidade, um método alternativo para identificar um local para uma unidade é especificar a ID da bandeja de unidades, definir a ID da gaveta como `0` e especificar a ID do slot no qual uma unidade reside.



== Nível mínimo de firmware

7,60 adiciona a `drawerID` entrada do usuário.

8,25 adiciona o `online` parâmetro.
