---
permalink: commands-a-z/recopy-volumecopy-target.html 
sidebar: sidebar 
keywords: volumecopy, target, command, operation, volume, copy, pair, reinitiate, array, role, context 
summary: O comando recopy volumeCopy target reinicia uma operação de cópia de volume usando um par de cópias de volume existente. 
---
= Cópia de volume recópia
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
O `recopy volumeCopy target` comando reinicia uma operação de cópia de volume usando um par de cópias de volume existente.



== Arrays compatíveis

Este comando se aplica a qualquer storage array individual, incluindo os arrays E4000, E2700, E5600, E2800, E5700, EF600 e EF300, desde que todos os pacotes SMcli estejam instalados.



== Funções

Para executar esse comando em um storage array E4000, E2800, E5700, EF600 ou EF300, você deve ter a função Administrador de armazenamento.



== Contexto

[NOTE]
====
Com a versão de firmware 7,83, o `copyType=(online | offline)` parâmetro já não é utilizado.

====
Este comando é válido para pares de cópias de volume de imagem instantânea.

Este comando funciona com pares de cópia de volume que você criou com um volume de imagem instantânea.

[NOTE]
====
Iniciar uma operação de cópia de volume substitui todos os dados existentes no volume de destino, faz com que o volume de destino seja somente leitura para hosts e falha em todos os volumes de imagem instantânea associados ao volume de destino, se houver algum. Se você já usou o volume de destino como uma cópia antes, certifique-se de que não precisa mais dos dados ou de fazer backup deles.

====


== Sintaxe

[source, cli]
----
recopy volumeCopy target [targetName]
[source [sourceName]]
[copyPriority=(highest | high | medium | low | lowest)]
[targetReadOnlyEnabled=(TRUE | FALSE)]
----


== Parâmetros

|===
| Parâmetro | Descrição 


 a| 
`target`
 a| 
O nome do volume de destino para o qual você deseja reiniciar uma operação de cópia de volume. Coloque o nome do volume alvo entre colchetes ([ ]). Se o nome do volume de destino tiver carateres especiais, você deve incluir o nome do volume de destino entre aspas duplas (" ") dentro de colchetes.



 a| 
`source`
 a| 
O nome do volume de origem para o qual você deseja reiniciar uma operação de cópia de volume. Inclua o nome do volume de origem entre colchetes ([ ]). Se o nome do volume de origem tiver carateres especiais, você deve incluir o nome do volume de origem entre aspas duplas (" ") dentro de colchetes.



 a| 
`copyPriority`
 a| 
A prioridade que a cópia de volume tem em relação à atividade de e/S do host. Os valores válidos são `highest`, `high`, `medium`, `low` `lowest` ou .



 a| 
`targetReadOnlyEnabled`
 a| 
A definição para que possa escrever no volume de destino ou apenas ler a partir do volume de destino. Para gravar no volume de destino, defina este parâmetro como `FALSE`. Para impedir a gravação no volume de destino, defina este parâmetro como `TRUE`.

|===


== Notas

Prioridade de cópia define a quantidade de recursos do sistema que são usados para copiar os dados entre o volume de origem e o volume de destino de um par de cópias de volume. Se você selecionar o nível de prioridade mais alto, a cópia de volume usará a maioria dos recursos do sistema para executar a cópia de volume, o que diminui o desempenho para transferências de dados do host.



== Nível mínimo de firmware

6,10

7,83 remove o `copyType=(online | offline)` parâmetro.
