---
permalink: commands-a-z/recreate-storagearray-mirrorrepository.html 
sidebar: sidebar 
keywords: recreate, synchronous, mirror, repository, volume 
summary: 'O comando recriar storageArray CSC Repository cria um novo volume de repositório de espelhamento síncrono (também chamado de volume de repositório de espelho) usando os parâmetros definidos para um volume de repositório de espelho anterior.' 
---
= Recriar o volume do repositório de espelhamento síncrono
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
O `recreate storageArray mirrorRepository` comando cria um novo volume de repositório de espelhamento síncrono (também chamado de volume de repositório de espelho) usando os parâmetros definidos para um volume de repositório de espelho anterior.



== Arrays compatíveis

Este comando se aplica a qualquer storage array individual, incluindo os arrays E4000, E2700, E5600, E2800 e E5700, desde que todos os pacotes SMcli estejam instalados.



== Funções

Para executar esse comando em um storage array E4000, E2800 ou E5700, você deve ter a função Storage Admin.



== Contexto

[NOTE]
====
Com a versão de firmware 7,80, o `recreate storageArray mirrorRepository` comando está obsoleto. Este comando não é mais suportado na GUI ou na CLI. Se você tentar executar este comando, uma mensagem de erro retorna indicando que essa funcionalidade não é mais suportada e que não serão feitas alterações nos repositórios de espelho remotos especificados.

====
O requisito subjacente é que você tenha criado anteriormente um volume de repositório espelhado. Ao usar esse comando, você pode definir o volume do repositório espelhado de uma de três maneiras: Unidades definidas pelo usuário, grupo de volumes definido pelo usuário ou número de unidades definido pelo usuário para o volume do repositório espelhado. Se você optar por definir um número de unidades, o firmware do controlador escolherá quais unidades usar para o volume do repositório espelhado.



== Sintaxe (unidades definidas pelo usuário)

[source, cli, subs="+macros"]
----
recreate storageArray mirrorRepository
repositoryRAIDLevel=(1 | 3 | 5 | 6)
repositoryDrives=pass:quotes[(_trayID1_,pass:quotes[[_drawerID1,_]]pass:quotes[_slotID1
... trayIDN_],pass:quotes[[_drawerIDN,_]]pass:quotes[_slotIDN_])
[trayLossProtect=(TRUE | FALSE)]
[dataAssurance=(none | enabled)]
----


== Sintaxe (grupo de volume definido pelo usuário)

[source, cli, subs="+macros"]
----
recreate storageArray mirrorRepository
repositoryVolumeGroup=pass:quotes[_volumeGroupName_
[freeCapacityArea=pass:quotes[_freeCapacityIndexNumber_]]
----


== Sintaxe (número definido pelo usuário de unidades)

[source, cli, subs="+macros"]
----
recreate storageArray mirrorRepository
repositoryRAIDLevel=(1 | 3 | 5 | 6)
repositoryDriveCount=pass:quotes[_numberOfDrives_]
(
  [driveMediaType=(HDD | SSD | unknown | allMedia)] |
  [driveType=(SAS | NVMe4K)]
)
[repositoryVolumeGroupUserLabel="userLabel"] |
[trayLossProtect=(TRUE | FALSE)] |
[drawerLossProtect=(true|false)] |
[dataAssurance=(none | enabled)]
----


== Parâmetros

|===
| Parâmetro | Descrição 


 a| 
`repositoryRAIDLevel`
 a| 
O nível RAID para o volume do repositório espelhado. Os valores válidos são `1`, `3`, `5`, `6` ou .



 a| 
`repositoryDrives`
 a| 
As unidades que você deseja usar para o volume do repositório espelhado. Os valores de ID da gaveta são `1` para `5`. Os valores de ID do slot são `1` para `24`. Inclua o valor de ID da bandeja, o valor de ID da gaveta e o valor de ID do slot entre colchetes ([ ]). Insira os nomes dos volumes do repositório usando estas regras:

Para bandejas de unidades de alta capacidade, especifique o valor de ID da bandeja, o valor de ID da gaveta e o valor de ID do slot para a unidade. Para bandejas de unidades de baixa capacidade, especifique o valor de ID da bandeja e o valor de ID do slot para a unidade. Os valores de ID da bandeja são `0` para `99`. Os valores de ID da gaveta são `1` para `5`.

Todos os máximos de ID de slot são 24. Os valores de ID do slot começam em 0 ou 1, dependendo do modelo da bandeja. As bandejas de unidades compatíveis com os controladores E2800 e E5700 têm números de ID de slot a partir de 0. As bandejas de unidades compatíveis com os controladores E2700 e E5600 têm números de ID de slot a partir de 1.

Inclua o valor de ID da bandeja, o valor de ID da gaveta e o valor de ID do slot entre colchetes ([ ]).

* Inclua todos os valores de ID da bandeja, os valores de ID da gaveta e o valor de ID do slot entre colchetes ([ ]).
* Separe o valor de ID da bandeja, o valor de ID da gaveta e o valor de ID do slot com vírgulas.
* Separe cada uma das posições de condução com um espaço.




 a| 
`repositoryVolumeGroup`
 a| 
O nome do grupo de volumes onde o volume do repositório espelhado está localizado.



 a| 
`repositoryVolumeGroupUserLabel`
 a| 
O nome que você deseja dar ao novo grupo de volumes no qual o volume do repositório espelhado será localizado. Coloque o nome do grupo de volume entre aspas duplas (" ").



 a| 
`freeCapacityArea`
 a| 
O número de índice do espaço livre em um grupo de volumes existente que você deseja usar para recriar o volume do repositório espelhado. A capacidade livre é definida como a capacidade livre entre os volumes existentes em um grupo de volumes. Por exemplo, um grupo de volumes pode ter as seguintes áreas: Volume 1, capacidade livre, volume 2, capacidade livre, volume 3, capacidade livre. Para usar a capacidade livre após o volume 2, você especificaria:

[listing]
----
freeCapacityArea=2
----
Execute o `show volumeGroup` comando para determinar se existe uma área de capacidade livre.



 a| 
`repositoryDriveCount`
 a| 
O número de unidades não atribuídas que você deseja usar para o volume do repositório espelhado.



 a| 
`driveMediaType`
 a| 
O tipo de Mídia de unidade para o qual você deseja recuperar informações. Os valores a seguir são tipos válidos de Mídia de unidade:

* `HDD` indica que você tem unidades de disco rígido na bandeja da unidade
* `SSD` indica que têm discos de estado sólido na bandeja de unidades
* `unknown` indica que você tem certeza do tipo de mídia de unidade na bandeja de unidades
* `allMedia` indica que tem todos os tipos de material na bandeja de unidades




 a| 
`driveType`
 a| 
O tipo de unidade que você deseja usar para o volume do repositório espelhado. Não é possível misturar tipos de unidade.

Você deve usar esse parâmetro quando tiver mais de um tipo de unidade em seu storage array.

Os tipos de unidade válidos são:

* `SAS`
* `NVMe4K`


Se você não especificar um tipo de unidade, o comando padrão será qualquer tipo.



 a| 
`trayLossProtect`
 a| 
A configuração para aplicar proteção contra perda de bandeja quando você cria o volume do repositório espelhado. Para aplicar a proteção contra perda de bandeja, defina este parâmetro como `TRUE`. O valor padrão é `FALSE`.



 a| 
`drawerLossProtect`
 a| 
A configuração para aplicar a proteção contra perda de gaveta quando você cria o volume do repositório espelhado. Para aplicar a proteção contra perda de gaveta, defina este parâmetro como `TRUE`. O valor padrão é `FALSE`.

|===


== Notas

Se você inserir um valor para o espaço de armazenamento do volume do repositório espelhado que é muito pequeno, o firmware do controlador retornará uma mensagem de erro, que indica a quantidade de espaço necessária para o volume do repositório espelhado. O comando não tenta alterar o volume do repositório espelhado. Você pode digitar novamente o comando usando o valor da mensagem de erro para o valor do espaço de armazenamento do volume do repositório espelhado.

 `repositoryDrives`O parâmetro dá suporte a bandejas de unidades de alta capacidade e bandejas de unidades de baixa capacidade. Uma bandeja de unidades de alta capacidade tem gavetas que prendem as unidades. As gavetas deslizam para fora da bandeja de unidades para fornecer acesso às unidades. Uma bandeja de unidades de baixa capacidade não tem gavetas. Para uma bandeja de unidades de alta capacidade, você deve especificar o identificador (ID) da bandeja de unidades, o ID da gaveta e o ID do slot no qual uma unidade reside. Para uma bandeja de unidades de baixa capacidade, você precisa especificar apenas o ID da bandeja de unidades e o ID do slot em que uma unidade reside. Para uma bandeja de unidades de baixa capacidade, um método alternativo para identificar um local para uma unidade é especificar a ID da bandeja de unidades, definir a ID da gaveta como `0` e especificar a ID do slot no qual uma unidade reside.

Quando você atribui as unidades, se você definir o `trayLossProtect` parâmetro como `TRUE` e tiver selecionado mais de uma unidade de qualquer bandeja, a matriz de armazenamento retornará um erro. Se você definir `trayLossProtect` o parâmetro como `FALSE`, o storage array executará operações, mas o volume do repositório espelhado que você criar pode não ter proteção contra perda de bandeja.

Quando o firmware do controlador atribui as unidades, se você definir o `trayLossProtect` parâmetro como `TRUE`, o storage array retornará um erro se o firmware do controlador não puder fornecer unidades que resultem no novo volume do repositório espelhado com proteção contra perda de bandeja. Se você definir `trayLossProtect` o parâmetro como `FALSE`, o storage array executará a operação mesmo que isso signifique que o volume do repositório espelhado pode não ter proteção contra perda de bandeja.



== Gerenciamento de garantia de dados

O recurso Data Assurance (DA) aumenta a integridade dos dados em todo o sistema de armazenamento. O DA permite que o storage array verifique se há erros que possam ocorrer quando os dados são movidos entre os hosts e as unidades. Quando esse recurso está ativado, o storage de armazenamento anexa códigos de verificação de erros (também conhecidos como verificações de redundância cíclica ou CRCs) a cada bloco de dados no volume. Depois que um bloco de dados é movido, o storage array usa esses códigos CRC para determinar se ocorreram erros durante a transmissão. Os dados potencialmente corrompidos não são gravados no disco nem devolvidos ao host.

Se você quiser usar o recurso DA, comece com um pool ou grupo de volume que inclui apenas unidades que suportam DA. Em seguida, crie volumes compatíveis com DA. Finalmente, mapeie esses volumes com capacidade PARA DA para o host usando uma interface de e/S capaz de DA. As interfaces de e/S capazes de DA incluem Fibre Channel, SAS e iSER over InfiniBand (extensões iSCSI para RDMA/IB). DA não é compatível com iSCSI via Ethernet ou SRP em InfiniBand.

[NOTE]
====
Quando todas as unidades são capazes de DA, você pode definir o `dataAssurance` parâmetro para `enabled` e, em seguida, usar DA com certas operações. Por exemplo, você pode criar um grupo de volumes que inclua unidades compatíveis com DA e, em seguida, criar um volume dentro desse grupo de volumes habilitado PARA DA. Outras operações que usam um volume habilitado PARA DA têm opções para suportar o recurso DA.

====
Se o `dataAssurance` parâmetro estiver definido como `enabled`, somente unidades capazes de garantia de dados serão consideradas para candidatos a volume; caso contrário, serão consideradas unidades capazes de garantia de dados e unidades que não sejam capazes de garantia de dados. Se apenas unidades de garantia de dados estiverem disponíveis, o novo grupo de volumes será criado usando as unidades de garantia de dados ativadas.



== Nível mínimo de firmware

6,10

7,10 adiciona capacidade RAID nível 6

7,75 adiciona o `dataAssurance` parâmetro.

8,60 adiciona os `driveMediaType` parâmetros , `repositoryVolumeGroupUserLabel` e `drawerLossProtect` .
