---
permalink: commands-a-z/reduce-disk-pool-capacity.html 
sidebar: sidebar 
keywords: reduce, disk pool, capacity 
summary: O comando Set diskPool reduz a capacidade do pool de discos removendo logicamente as unidades do pool. 
---
= Reduzir a capacidade do pool de disco
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
O `set diskPool` comando reduz a capacidade do pool de discos removendo logicamente as unidades do pool.



== Arrays compatíveis

Este comando se aplica a qualquer storage array individual, incluindo os arrays E4000, E2700, E5600, E2800, E5700, EF600 e EF300, desde que todos os pacotes SMcli estejam instalados.



== Funções

Para executar esse comando em um storage array E4000, E2800, E5700, EF600 ou EF300, você deve ter a função Administrador de armazenamento.



== Contexto

Este comando usa o recurso redução dinâmica de capacidade (DCR), que permite remover unidades selecionadas de um pool de discos e reutilizar as unidades removidas conforme necessário.

O número máximo de unidades que você pode remover de um pool de discos em uma única operação DCR é 60. Não é possível reduzir o pool de discos para abaixo do tamanho mínimo do pool de discos.



== Sintaxe

[source, cli, subs="+macros"]
----
set diskPool pass:quotes[[_diskPoolName_]]
removeDrives=pass:quotes[(_trayID1_],pass:quotes[[_drawerID1_,]]pass:quotes[_slotID1
... trayIDn_],pass:quotes[[_drawerIDn_,]]pass:quotes[_slotIDn_])
----


== Parâmetro

|===
| Parâmetro | Descrição 


 a| 
`diskPool`
 a| 
O nome do pool de discos para o qual você deseja reduzir a capacidade. Inclua o nome do pool de discos entre colchetes ([ ]).



 a| 
`removeDrives`
 a| 
Para bandejas de unidades de alta capacidade, especifique o valor de ID da bandeja, o valor de ID da gaveta e o valor de ID do slot para a unidade. Para bandejas de unidades de baixa capacidade, especifique o valor de ID da bandeja e o valor de ID do slot para a unidade. Os valores de ID da bandeja são `0` para `99`. Os valores de ID da gaveta são `1` para `5`.

Todos os máximos de ID de slot são 24. Os valores de ID do slot começam em 0 ou 1, dependendo do modelo da bandeja. As bandejas de unidades compatíveis com os controladores E2800 e E5700 têm números de ID de slot a partir de 0. As bandejas de unidades compatíveis com os controladores E2700 e E5600 têm números de ID de slot a partir de 1.

Inclua o valor de ID da bandeja, o valor de ID da gaveta e o valor de ID do slot entre colchetes ([ ]).

|===


== Notas

Cada nome do pool de discos deve ser exclusivo. Você pode usar qualquer combinação de carateres alfanuméricos, sublinhado (_), hífen (-) e libra ( no) para o rótulo do usuário. As etiquetas de utilizador podem ter um máximo de 30 carateres.

Você pode querer remover unidades selecionadas de um pool de discos se precisar criar um grupo separado ou remover a capacidade desnecessária do storage array. As unidades removidas tornam-se unidades não atribuídas e os dados que existiam nelas são redistribuídos pelas unidades restantes no pool de discos. A capacidade do pool de discos é diminuída pela capacidade das unidades removidas. A remoção de unidades de um pool de discos é sempre realizada como uma tarefa em segundo plano e os volumes permanecem totalmente acessíveis durante esta operação. O progresso da operação de remoção é relatado como parte do status de operações de longo prazo.

Este comando falha se não houver capacidade livre suficiente nas unidades que permanecem no pool de discos para armazenar todos os dados que estavam nas unidades que você remove do pool de discos. A capacidade de reserva no pool de discos pode ser usada para armazenar dados que estavam nas unidades removidas do pool de discos. No entanto, se a capacidade de reserva for inferior ao limite crítico, um evento crítico será gravado no log de eventos principais.

Diminuir o tamanho do pool de discos pode resultar em uma menor capacidade de reserva necessária. Em alguns casos, a fim de diminuir a probabilidade de que este comando falhe, reduza sua capacidade de reserva antes de executar este comando para aumentar a quantidade de espaço disponível para dados de pool de disco.

O firmware do controlador determina quantas unidades você pode remover e você pode selecionar as unidades específicas a serem removidas. O firmware da controladora baseia a contagem da quantidade de espaço livre necessária para redistribuir os dados entre as unidades restantes, sem consumir nenhuma capacidade reservada para reconstruções. Se a capacidade livre do conjunto de discos já for inferior à quantidade de Unidade de Reconstrução reservada, o controlador não permite o início de uma operação de DCR.

Uma operação DCR pode resultar na capacidade configurada excedendo um ou ambos os limites de utilização do pool. Em caso afirmativo, os alertas de limite normais são emitidos.



== Nível mínimo de firmware

8,10
