---
permalink: commands-a-z/remove-drives-from-ssd-cache.html 
sidebar: sidebar 
keywords: remove, drives, ssd, cache 
summary: 'O comando Set ssdCache diminui a capacidade do cache SSD removendo discos de estado sólido (SSDs).' 
---
= Remova as unidades do cache SSD
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
O `set ssdCache` comando diminui a capacidade do cache SSD removendo discos de estado sólido (SSDs).



== Arrays compatíveis

Este comando se aplica a qualquer storage array individual, incluindo os arrays E4000, E2700, E5600, E2800, E5700, EF600 e EF300, desde que todos os pacotes SMcli sejam instalados.



== Funções

Para executar esse comando em um storage array E4000, E2800, E5700, EF600 ou EF300, você deve ter a função Admin de suporte.



== Sintaxe

[source, cli, subs="+macros"]
----
set ssdCache pass:quotes[[_ssdCacheName_]]
removeDrives=pass:quotes[(_trayID1_,]pass:quotes[[_drawerID1_,]]pass:quotes[_slotID1 ... trayIDn_],pass:quotes[[_drawerIDn,_]]pass:quotes[_slotIDn_])
----


== Parâmetros

|===
| Parâmetro | Descrição 


 a| 
`ssdCache`
 a| 
O nome do cache SSD do qual você deseja remover SSDs. Inclua o nome do cache SSD entre colchetes ([ ]). Se o nome do cache SSD tiver carateres especiais ou consistir apenas em números, você deve incluir o nome do cache SSD em aspas duplas (" ") dentro de colchetes.



 a| 
`removeDrives`
 a| 
Para bandejas de unidades de alta capacidade, especifique o valor de ID da bandeja, o valor de ID da gaveta e o valor de ID do slot para a unidade. Para bandejas de unidades de baixa capacidade, especifique o valor de ID da bandeja e o valor de ID do slot para a unidade. Os valores de ID da bandeja são `0` para `99`. Os valores de ID da gaveta são `1` para `5`.

Todos os máximos de ID de slot são 24. Os valores de ID do slot começam em 0 ou 1, dependendo do modelo da bandeja. As bandejas de unidades compatíveis com os controladores E2800 e E5700 têm números de ID de slot a partir de 0. As bandejas de unidades compatíveis com os controladores E2700 e E5600 têm números de ID de slot a partir de 1.

Inclua o valor de ID da bandeja, o valor de ID da gaveta e o valor de ID do slot entre colchetes ([ ]).

|===


== Notas

Você não pode remover todos os SSDs do cache SSD usando este comando; pelo menos um SSD deve permanecer no cache SSD. Se você quiser remover completamente o cache SSD, use o `delete ssdCache` comando em vez disso.



== Nível mínimo de firmware

7,84

O 11,80 adiciona suporte a array EF600 e EF300
