---
permalink: commands-a-z/remove-member-volume-from-consistency-group.html 
sidebar: sidebar 
keywords: remove, member, volume, consistency group 
summary: O comando Set consistentcyGroup remove um volume de membro de um grupo de consistência de snapshot existente. 
---
= Remova o volume do membro do grupo de consistência
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
O `set consistencyGroup` comando remove um volume de membro de um grupo de consistência de snapshot existente.



== Arrays compatíveis

Este comando se aplica a qualquer storage array individual, incluindo os arrays E2700, E5600, E2800, E5700, EF600 e EF300, desde que todos os pacotes SMcli estejam instalados.



== Funções

Para executar esse comando em um storage array E2800, E5700, EF600 ou EF300, você deve ter a função Administrador do armazenamento.



== Contexto

Opcionalmente, você pode excluir os membros do volume do repositório do grupo de consistência.



== Sintaxe

[listing, subs="+macros"]
----
set consistencyGroup pass:quotes[[_"consistencyGroupName"_]]
removeCGMemberVolume=pass:quotes["_memberVolumeName_"]
[deleteRepositoryMembers=(TRUE | FALSE)]
----


== Parâmetros

|===
| Parâmetro | Descrição 


 a| 
`consistencyGroupName`
 a| 
O nome do grupo de consistência do qual você deseja remover um membro. Coloque o nome do grupo de consistência entre aspas duplas (" ") dentro de colchetes ([ ]).



 a| 
`removeCGMemberVolume`
 a| 
O nome do volume do membro que você deseja remover. Inclua o nome do grupo de membros entre aspas duplas (" ").



 a| 
`deleteRepositoryMembers`
 a| 
Determina se deseja remover todos os membros do repositório do grupo de consistência.

|===


== Nível mínimo de firmware

7,83
