---
permalink: commands-a-z/remove-volumecopy-target.html 
sidebar: sidebar 
keywords: remove, volume, copy 
summary: O comando remove volumeCopy target remove um par de cópias de volume. 
---
= Remover cópia de volume
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
O `remove volumeCopy target` comando remove um par de cópias de volume.



== Arrays compatíveis

Este comando se aplica a qualquer storage array individual, incluindo os arrays E2700, E5600, E2800, E5700, EF600 e EF300, desde que todos os pacotes SMcli estejam instalados.



== Funções

Para executar esse comando em um storage array E2800, E5700, EF600 ou EF300, você deve ter a função Administrador do armazenamento.



== Contexto

Este comando é válido para pares de cópias de volume instantâneo.

[NOTE]
====
Com a versão de firmware 7,83, o `copyType=(online | offline)` parâmetro já não é utilizado.

====


== Sintaxe

[listing, subs="+macros"]
----
remove volumeCopy target pass:quotes[[_targetName_]] [source pass:quotes[[_sourceName_]]]
----


== Parâmetros

|===
| Parâmetro | Descrição 


 a| 
`target`
 a| 
O nome do volume de destino que você deseja remover. Coloque o nome do volume alvo entre colchetes ([ ]). Se o nome do volume de destino tiver carateres especiais ou consistir apenas em números, você deve incluir o nome do volume de destino entre aspas duplas (" ") dentro de colchetes.



 a| 
`source`
 a| 
O nome do volume de origem que você deseja remover. Inclua o nome do volume de origem entre colchetes ([ ]). Se o nome do volume de origem tiver carateres especiais ou consistir apenas em números, você deve incluir o nome do volume de origem entre aspas duplas (" ") dentro de colchetes.

|===


== Nível mínimo de firmware

5,40

7,83 remove o `copyType=(online | offline)` parâmetro.
