---
permalink: commands-a-z/reset-storagearray-sasphybaseline.html 
sidebar: sidebar 
keywords: reset, storage array, sas, phy, baseline 
summary: 'O comando reset storageArray SASPHYBaseline redefine a linha de base SAS Physical Layer (SAS PHY) para todos os dispositivos e remove a lista de erros do arquivo .csv.' 
---
= Redefina a linha de base SAS PHY da matriz de armazenamento
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
O `reset storageArray SASPHYBaseline` comando redefine a linha de base da camada física SAS (SAS PHY) para todos os dispositivos e remove a lista de erros do `.csv` arquivo.



== Arrays compatíveis

Este comando se aplica a qualquer storage array individual, incluindo os arrays E4000, E2700, E5600, E2800, E5700, EF600 e EF300, desde que todos os pacotes SMcli estejam instalados.



== Funções

Para executar esse comando em um storage array E4000, E2800, E5700, EF600 ou EF300, você deve ter a função Administrador de armazenamento.



== Contexto

O `.csv` arquivo é gerado quando você executa o `save storageArray SASPHYCounts` comando.

[NOTE]
====
A versão anterior `reset storageArray SASPHYBaseline` do comando limpa contagens de erro para todos os dispositivos, exceto as unidades. O `reset storageArray SASPHYBaseline` comando agora redefine a linha de base SAS PHY para as unidades, bem como para os outros dispositivos. Todos os erros são excluídos do `.csv` arquivo.

====


== Sintaxe

[source, cli]
----
reset storageArray SASPHYBaseline
----


== Parâmetros

Nenhum.



== Nível mínimo de firmware

6,10

7,83 redefine a linha de base SAS PHY para unidades.
