---
permalink: commands-a-z/reset-storagearray-volumedistribution.html 
sidebar: sidebar 
keywords: reset, storage array, volume, distribution 
summary: 'O comando reset storageArray volumeDistribution reatribui (move) todos os volumes para o controlador preferido.' 
---
= Redefina a distribuição do volume da matriz de armazenamento
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
O `reset storageArray volumeDistribution` comando reatribui (move) todos os volumes ao seu controlador preferido.



== Arrays compatíveis

Este comando se aplica a qualquer storage array individual, incluindo os arrays E4000, E2700, E5600, E2800, E5700, EF600 e EF300, desde que todos os pacotes SMcli estejam instalados.



== Funções

Para executar esse comando em um storage array E4000, E2800, E5700, EF600 ou EF300, você deve ter a função Administrador de armazenamento.



== Sintaxe

[source, cli]
----
reset storageArray volumeDistribution
----


== Parâmetros

Nenhum.



== Notas

Se você usar esse comando em um host sem um driver de vários caminhos, você deve parar as operações de e/S para os volumes até que esse comando seja concluído para evitar erros de aplicativo.

Em determinados ambientes de sistema operacional do host, talvez seja necessário reconfigurar o driver de host de vários caminhos. Você também pode precisar fazer modificações no sistema operacional para reconhecer o novo caminho de e/S para os volumes.



== Nível mínimo de firmware

5,20
