---
permalink: commands-a-z/resume-ssdcache.html 
sidebar: sidebar 
keywords: resume, ssd, cache 
summary: O comando resume ssdCache reinicia o cache de todos os volumes usando o cache SSD que foi temporariamente interrompido com o comando suspender ssdCache. 
---
= Retomar cache SSD
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
O `resume ssdCache` comando reinicia o cache de todos os volumes usando o cache SSD que foi temporariamente interrompido com o `suspend ssdCache` comando.



== Arrays compatíveis

Este comando se aplica a qualquer storage array individual, incluindo os arrays E2700, E5600, E2800, E5700, EF600 e EF300, desde que todos os pacotes SMcli estejam instalados.



== Funções

Para executar esse comando em um storage array E2800, E5700, EF600 ou EF300, você deve ter a função Administrador de suporte.



== Sintaxe

[listing, subs="+macros"]
----
resume ssdCache pass:quotes[[_ssdCacheName_]]
----


== Parâmetro

|===
| Parâmetro | Descrição 


 a| 
`ssdCache`
 a| 
O nome do cache SSD para o qual você deseja retomar as operações de armazenamento em cache. Inclua o nome do cache SSD entre colchetes ([ ]). Se o nome do cache SSD tiver carateres especiais ou consistir apenas em números, você deve incluir o nome do cache SSD em aspas duplas (" ") dentro de colchetes.

|===


== Nível mínimo de firmware

7,84

O 11,80 adiciona suporte a array EF600 e EF300
