---
permalink: commands-a-z/revive-drive.html 
sidebar: sidebar 
keywords: revive, drive 
summary: O comando Revive DRIVE força a unidade especificada para o estado ideal. 
---
= Reavive a condução
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
O `revive drive` comando força a unidade especificada para o estado ideal.



== Arrays compatíveis

Este comando se aplica a qualquer storage array individual, incluindo os arrays E4000, E2700, E5600, E2800, E5700, EF600 e EF300, desde que todos os pacotes SMcli estejam instalados.



== Funções

Para executar esse comando em um storage array E4000, E2800, E5700, EF600 ou EF300, você deve ter a função Administrador de armazenamento ou Administrador de suporte.



== Contexto

[NOTE]
====
*Possível perda de acesso a dados* -- o uso correto deste comando depende da configuração de dados de todas as unidades do grupo de volumes. Nunca tente reviver uma unidade, a menos que você seja supervisionado por suporte técnico.

====


== Sintaxe

[source, cli, subs="+macros"]
----
revive drive pass:quotes[[_trayID_],pass:quotes[[_drawerID,_]]pass:quotes[_slotID_]]
----


== Parâmetro

|===
| Parâmetro | Descrição 


 a| 
`drive`
 a| 
Para bandejas de unidades de alta capacidade, especifique o valor de ID da bandeja, o valor de ID da gaveta e o valor de ID do slot para a unidade. Para bandejas de unidades de baixa capacidade, especifique o valor de ID da bandeja e o valor de ID do slot para a unidade. Os valores de ID da bandeja são `0` para `99`. Os valores de ID da gaveta são `1` para `5`.

Todos os máximos de ID de slot são 24. Os valores de ID do slot começam em 0 ou 1, dependendo do modelo da bandeja. As bandejas de unidades compatíveis com os controladores E2800 e E5700 têm números de ID de slot a partir de 0. As bandejas de unidades compatíveis com os controladores E2700 e E5600 têm números de ID de slot a partir de 1.

Inclua o valor de ID da bandeja, o valor de ID da gaveta e o valor de ID do slot entre colchetes ([ ]).

|===


== Notas

 `drive`O parâmetro dá suporte a bandejas de unidades de alta capacidade e bandejas de unidades de baixa capacidade. Uma bandeja de unidades de alta capacidade tem gavetas que prendem as unidades. As gavetas deslizam para fora da bandeja de unidades para fornecer acesso às unidades. Uma bandeja de unidades de baixa capacidade não tem gavetas. Para uma bandeja de unidades de alta capacidade, você deve especificar o identificador (ID) da bandeja de unidades, o ID da gaveta e o ID do slot no qual uma unidade reside. Para uma bandeja de unidades de baixa capacidade, você precisa especificar apenas o ID da bandeja de unidades e o ID do slot em que uma unidade reside. Para uma bandeja de unidades de baixa capacidade, um método alternativo para identificar um local para uma unidade é especificar a ID da bandeja de unidades, definir a ID da gaveta como `0` e especificar a ID do slot no qual uma unidade reside.



== Nível mínimo de firmware

5,43

7,60 adiciona a `drawerID` entrada do usuário.
