---
permalink: commands-a-z/save-storagearray-performancestats.html 
sidebar: sidebar 
keywords: save, storage, array, performance, statistics 
summary: O comando save storageArray performanceStats salva as estatísticas de desempenho em um arquivo. 
---
= Salvar estatísticas de desempenho do storage array
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
O `save storageArray performanceStats` comando salva as estatísticas de desempenho em um arquivo.



== Arrays compatíveis

Este comando se aplica a qualquer storage array individual, incluindo os arrays E2700, E5600, E2800, E5700, EF600 e EF300, desde que todos os pacotes SMcli estejam instalados.



== Funções

Para executar esse comando em um storage array E2800, E5700, EF600 ou EF300, você deve ter a função Administrador do armazenamento.



== Contexto

Antes de usar esse comando, execute o `set session performanceMonitorInterval` comando e o `set session performanceMonitorIterations` comando para especificar com que frequência as estatísticas são coletadas.



== Sintaxe

[listing, subs="+macros"]
----
save storageArray performanceStats file=pass:quotes["_filename_"]
----


== Parâmetro

[cols="2*"]
|===
| Parâmetro | Descrição 


 a| 
`file`
 a| 
O caminho do arquivo e o nome do arquivo para o qual você deseja salvar as estatísticas de desempenho. Coloque o nome do ficheiro entre aspas duplas (" "). Por exemplo:

`file="C:\Program Files\CLI\logs\sastat.csv"`

O nome padrão do arquivo que contém as estatísticas de desempenho é `performanceStatistics.csv`. Você pode usar qualquer nome de arquivo, mas você deve usar a `.csv` extensão.

|===


== Nível mínimo de firmware

6,10
