---
permalink: commands-a-z/save-storagearray-keymanagementclientcsr.html 
sidebar: sidebar 
keywords: generate, key, management, certificate, sign, request, csr 
summary: O comando save storageArray keyManagementClientCSR solicita um CSR gerado para o storage array que você pode salvar em um arquivo. 
---
= Gerar solicitação de assinatura de certificado de Gerenciamento de chaves (CSR)
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
O `save storageArray keyManagementClientCSR` comando solicita um CSR gerado para o storage array que você pode salvar em um arquivo.



== Arrays compatíveis

Esse comando se aplica a um storage array individual de armazenamento E4000, E2800, E5700, EF600 ou EF300. Ele não opera em matrizes de armazenamento E2700 ou E5600.



== Funções

Para executar esse comando em um storage array E4000, E2800, E5700, EF600 ou EF300, você deve ter a função Security Admin.



== Contexto

[NOTE]
====
Este comando aplica-se apenas ao gerenciamento de chaves externas.

====


== Sintaxe

[source, cli, subs="+macros"]
----

save storageArray keyManagementClientCSR commonName=pass:quotes["_common_name_"]
organization=pass:quotes["_organization_"]
locality=pass:quotes["_locality_"]
country=pass:quotes["_country_"]
file=pass:quotes["_file_"]
[organizationalUnit=pass:quotes["_organizational unit_"]]
[stateProvince=pass:quotes["_state_province_"]]
----


== Parâmetros

[cols="2*"]
|===
| Parâmetro | Descrição 


 a| 
`commonName`
 a| 
O valor inserido para esse parâmetro deve corresponder a um dos nomes de usuário definidos no servidor KMIP.



 a| 
`organization`
 a| 
Permite especificar o nome legal completo da organização ao qual o storage array pertence. Não abreviar e incluir quaisquer sufixos como Inc, Corp ou LLC.



 a| 
`locality`
 a| 
Permite especificar a cidade ou localidade onde o storage array está localizado,



 a| 
`country`
 a| 
Permite especificar o código ISO de dois dígitos (International Organization for Standardization) 3166-1 alfa-2 do seu país, como EUA.



 a| 
`file`
 a| 
Permite especificar o local do ficheiro e do ficheiro onde irá guardar o ficheiro de certificado assinado do controlador.



 a| 
`organizationalUnit`
 a| 
Permite especificar a divisão da organização que lida com o certificado.



 a| 
`stateProvince`
 a| 
Permite especificar o estado ou a região em que o storage array está localizado. Isso não deve ser abreviado.

|===


== Exemplo

[listing, subs="+macros"]
----

SMcli -n Array1 -c "save storageArray keyManagementClientCSR commonName=pass:quotes["_192.0.2.1_"]
organization=pass:quotes["_Widgets Are Us_, _Inc_."]
locality=pass:quotes["_sedgwick_"]
country=pass:quotes["_US_"]
file=pass:quotes["_latestCertificate_"]
organizationalUnit=pass:quotes["_Products Unit_"]
stateProvince=pass:quotes["_Kansas_"];"

SMcli completed successfully.
----


== Nível mínimo de firmware

8,40
