---
permalink: commands-a-z/save-storagearray-configuration.html 
sidebar: sidebar 
keywords: save, storage, array, configuration 
summary: O comando save storageArray Configuration cria um arquivo de script que você pode usar para recriar a configuração atual de volume de storage array. 
---
= Salve a configuração do storage array
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
O `save storageArray configuration` comando cria um arquivo de script que você pode usar para recriar a configuração atual de volume de storage array.



== Arrays compatíveis

Este comando se aplica a qualquer storage array individual, incluindo os arrays E2700, E5600, E2800, E5700, EF600 e EF300, desde que todos os pacotes SMcli estejam instalados.



== Funções

Para executar esse comando em um storage array E2800, E5700, EF600 ou EF300, você deve ter a função Administrador do armazenamento. No entanto, o uso deste comando com o parâmetro LDAP é restrito àqueles com a função Security Admin.



== Contexto

[NOTE]
====
Esse comando não salva os dados de configuração de espelhamento remoto ou cópia de volume no storage array atual em um arquivo.

====


== Sintaxe

[listing, subs="+macros"]
----
save storageArray configuration file=pass:quotes["_filename_"]
(allconfig|[globalSettings=(TRUE | FALSE)]
[volumeConfigAndSettings=(TRUE | FALSE)]
[hostTopology=(TRUE | FALSE)]
[lunMappings=(TRUE | FALSE)])
----


== Parâmetros

[cols="2*"]
|===
| Parâmetro | Descrição 


 a| 
`file`
 a| 
O caminho do arquivo e o nome do arquivo para o qual você deseja salvar as configurações. Coloque o nome do ficheiro entre aspas duplas (" "). Por exemplo:

`file="C:\Program Files\CLI\logs\saconf.cfg"`

O nome padrão do arquivo que contém as configurações é `storage-array-configuration.cfg`. Este comando não adiciona automaticamente uma extensão de arquivo ao arquivo salvo. Você deve especificar uma extensão de arquivo ao digitar o nome do arquivo.



 a| 
`allConfig`
 a| 
A definição para guardar todos os valores de configuração no ficheiro. (Se você escolher este parâmetro, todos os parâmetros de configuração serão definidos como `TRUE` .)



 a| 
`globalSettings`
 a| 
A definição para guardar as definições globais no ficheiro. Para guardar as definições globais, defina este parâmetro como `TRUE`. Para evitar guardar as definições globais, defina este parâmetro como `FALSE`. O valor padrão é `TRUE`.



 a| 
`volumeConfigAndSettings`
 a| 
A definição para guardar as definições de configuração do volume e todas as definições globais no ficheiro. Para guardar as definições de configuração do volume e as definições globais, defina este parâmetro para `TRUE`. Para evitar guardar as definições de configuração do volume e as definições globais, defina este parâmetro como `FALSE`. O valor padrão é `TRUE`.



 a| 
`hostTopology`
 a| 
A configuração para salvar a topologia do host no arquivo. Para salvar a topologia do host, defina esse parâmetro como `TRUE`. Para evitar salvar a topologia do host, defina esse parâmetro como `FALSE`. O valor padrão é `FALSE`.



 a| 
`lunMappings`
 a| 
A configuração para salvar o mapeamento LUN ou NSID no arquivo. Para salvar o mapeamento LUN ou NSID, defina este parâmetro como `TRUE`. Para evitar salvar o mapeamento LUN ou NSID, defina este parâmetro como `FALSE`. O valor padrão é `FALSE`.

|===


== Notas

Ao usar esse comando, você pode especificar qualquer combinação dos parâmetros para a configuração global, a configuração de volume, a topologia do host ou o mapeamento LUN. Se pretender introduzir todas as definições, utilize o `allConfig` parâmetro. Você deve usar o `allConfig` parâmetro ou um ou mais dos outros quatro parâmetros.



== Nível mínimo de firmware

6,10
