---
permalink: commands-a-z/save-controller-cacertificate.html 
sidebar: sidebar 
keywords: retrieve, installed, ca, certificates 
summary: O comando save controller caCertificate recupera os certificados de CA instalados do controlador especificado. Incluídos nos certificados recuperados estão todos os certificados de CA solicitados do servidor da Web do controlador. 
---
= Recuperar certificados CA instalados
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
O `save controller caCertificate` comando recupera os certificados de CA instalados do controlador especificado. Incluídos nos certificados recuperados estão todos os certificados de CA solicitados do servidor da Web do controlador.



== Arrays compatíveis

Este comando se aplica a um storage array individual de armazenamento E2800, E5700, EF600 ou EF300. Ele não opera em matrizes de armazenamento E2700 ou E5600.



== Funções

Para executar esse comando em um storage array E2800, E5700, EF600 ou EF300, você deve ter a função Security Admin.



== Sintaxe

[listing, subs="+macros"]
----

save controller[(a|b)] caCertificate [all | aliases=pass:quotes[("_alias1_" ... "_aliasN_")]]
 path="fileLocation"
----


== Parâmetros

[cols="2*"]
|===
| Parâmetro | Descrição 


 a| 
`controller`
 a| 
Permite especificar o controlador no qual pretende recuperar os certificados raiz/intermédios. Identificadores válidos do controlador são a ou b, onde a é o controlador no slot A, e b é o controlador no slot B. feche o identificador do controlador entre colchetes ([ ]).



 a| 
`all`
 a| 
Permite especificar a recuperação de todos os certificados importados para resolver a cadeia de certificados assinada. Os certificados instalados pelo usuário incluem certificados de gerenciamento de chaves.



 a| 
`aliases`
 a| 
Permite especificar qual o certificado raiz/intermediário instalado pelo usuário a recuperar por alias. Inclua todos os aliases entre parênteses. Se você inserir mais de um alias, separe-os com um espaço.



 a| 
`path`
 a| 
Permite especificar o local local para salvar os certificados raiz/intermediário dos controladores.

|===


== Exemplos

[listing]
----

SMcli -n Array1 -c "save controller[a] caCertificate all path="C:\";"

SMcli -n Array1 -c "save controller[b] caCertificate aliases=("myAlias" "anotherAlias") path="C:\";"

SMcli completed successfully.
----


== Nível mínimo de firmware

8,40
