---
permalink: commands-a-z/save-controller-arraymanagementsignedcertificate.html 
sidebar: sidebar 
keywords: retrieve, installed, server, certificate 
summary: O comando save controller arrayManagementSignedCertificate recupera o certificado do servidor instalado para o controlador para que você possa exibir os detalhes do certificado. 
---
= Recuperar certificado do servidor instalado
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
O `save controller arrayManagementSignedCertificate` comando recupera o certificado do servidor instalado para o controlador para que você possa exibir os detalhes do certificado.



== Arrays compatíveis

Este comando se aplica a um storage array individual de armazenamento E2800, E5700, EF600 ou EF300. Ele não opera em matrizes de armazenamento E2700 ou E5600.



== Funções

Para executar esse comando em um storage array E2800, E5700, EF600 ou EF300, você deve ter a função Security Admin.



== Sintaxe

[listing, subs="+macros"]
----

save controller [(a|b)] arrayManagementSignedCertificate
     file=pass:quotes["_filename_"]
----


== Parâmetros

[cols="2*"]
|===
| Parâmetro | Descrição 


 a| 
`controller`
 a| 
Permite especificar o controlador do qual pretende transferir o certificado assinado. Identificadores válidos do controlador são a ou b, onde a é o controlador no slot A, e b é o controlador no slot B. feche o identificador do controlador entre colchetes ([ ]).



 a| 
`file`
 a| 
Permite especificar o ficheiro para o qual pretende guardar o ficheiro de certificado assinado do controlador.

|===


== Exemplos

[listing]
----

SMcli -n Array1 -c "save controller [a] arrayManagementSignedCertificate
   file="C:\controllerAcertificate.cer";"

SMcli -n Array1 -c "save controller [b] arrayManagementSignedCertificate
   file="C:\controllerBcertificate.cer";"

SMcli completed successfully.
----


== Nível mínimo de firmware

8,40
