---
permalink: commands-a-z/set-hostchannel.html 
sidebar: sidebar 
keywords: set, host, channel 
summary: O comando Set hostChannel define o ID do loop para o canal host. 
---
= Defina o canal do host
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
O `set hostChannel` comando define a ID do loop para o canal host.



== Arrays compatíveis

Este comando se aplica a qualquer storage array individual, incluindo os arrays E4000, E2700, E5600, E2800, E5700, EF600 e EF300, desde que todos os pacotes SMcli estejam instalados.



== Funções

Para executar esse comando em um storage array E4000, E2800, E5700, EF600 ou EF300, você deve ter a função Administrador de armazenamento.



== Sintaxe

[source, cli, subs="+macros"]
----
set hostChannel pass:quotes[[_hostChannelNumber_]]
preferredID=pass:quotes[_portID_]
----


== Parâmetros

[cols="2*"]
|===
| Parâmetro | Descrição 


 a| 
`hostChannel`
 a| 
O número do identificador do canal anfitrião para o qual pretende definir a ID do loop. Inclua o número do identificador do canal do host entre colchetes ([ ]).

Use um valor de canal de host apropriado para seu modelo de controlador específico. Uma bandeja de controlador pode suportar um canal de host ou até oito canais de host. Os valores válidos do canal do host são `a1`, `a2` `a3` , `a4` `a5` , , , , `a6` `a7`, , `a8` `b1` , `b2`, , , `b3` `b4`, , `b5`, `b6`, `b7`, `b8` ou .



 a| 
`preferredID`
 a| 
O identificador de porta para o canal de host especificado. Os valores de ID da porta são `0` para `127`.

|===


== Nível mínimo de firmware

6,10

6,14 adiciona uma atualização ao identificador do canal do host.

7,15 adiciona uma atualização ao identificador do canal do host.
