---
permalink: commands-a-z/set-storagearray-autosupportondemand.html 
sidebar: sidebar 
keywords: enable, disable, autosupport, ondemand, feature, individual, E2800, E5700, arrays 
summary: O comando Set storageArray autoSupportOnDemand ativa ou desativa o recurso AutoSupport OnDemand. Esse recurso permite que o suporte técnico coordene a transmissão de dados do AutoSupport e permite que eles solicitem a retransmissão de dados de suporte ausentes. 
---
= Ative ou desative o recurso AutoSupport OnDemand
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
O `set storageArray autoSupportOnDemand` comando liga ou desliga o recurso AutoSupport OnDemand. Esse recurso permite que o suporte técnico coordene a transmissão de dados do AutoSupport e permite que eles solicitem a retransmissão de dados de suporte ausentes.



== Arrays compatíveis

Esse comando se aplica a um storage array individual de armazenamento E4000, E2800, E5700, EF600 ou EF300. Ele não opera em matrizes de armazenamento E2700 ou E5600.



== Funções

Para executar esse comando em um storage array E4000, E2800, E5700, EF600 ou EF300, você deve ter a função Administrador de armazenamento ou Administrador de suporte.



== Contexto

Antes de ativar esse recurso, primeiro você deve habilitar o recurso AutoSupport no storage array. Depois de ativar esse recurso, você pode ativar o recurso de Diagnóstico remoto do AutoSupport (se desejado).



== Sintaxe

[source, cli]
----
set storageArray autoSupportOnDemand (enable | disable)
----


== Parâmetros

[cols="2*"]
|===
| Parâmetro | Descrição 


 a| 
`enable | disable`
 a| 
Permite que o usuário ative ou desative o recurso AutoSupport OnDemand. Se o AutoSupport estiver desativado, a ação de ativação falhará e solicitará ao usuário que a ative primeiro. Se o recurso Diagnóstico remoto estiver ativado, a ação de desativação também desativará o recurso Diagnóstico remoto.

|===


== Exemplos

[listing]
----

SMcli -n Array1 -c "set storageArray autoSupportOnDemand enable;"

SMcli completed successfully.
----


== Verificação

Use o `show storageArray autoSupport` comando para ver se você ativou o recurso. As duas linhas iniciais da saída exibida mostram o status de ativação do recurso AutoSupport, seguido pelo recurso AutoSupport OnDemand:

[listing]
----
The AutoSupport is enabled on this storage array.
The AutoSupport OnDemand feature is enabled on this storage array.
The AutoSupport Remote Diagnostics feature is enabled on this storage array.
----


== Nível mínimo de firmware

8,40
