---
permalink: commands-a-z/set-autosupport-https-delivery-method.html 
sidebar: sidebar 
keywords: 'Specify AutoSupport HTTP(S) delivery method' 
summary: 'O comando Set storageArray AutoSupport deliveryMethod configura o método de entrega para enviar mensagens AutoSupport para HTTP(S).' 
---
= Especifique o método de entrega AutoSupport HTTP(S)
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
O `set storageArray autoSupport deliveryMethod` comando configura o método de entrega para enviar mensagens AutoSupport para HTTP(S).



== Arrays compatíveis

Esse comando se aplica a um storage array individual de armazenamento E4000, E2800, E5700, EF600 ou EF300. Ele não opera em matrizes de armazenamento E2700 ou E5600.



== Funções

Para executar esse comando em um storage array E4000, E2800, E5700, EF600 ou EF300, você deve ter a função Administrador de armazenamento ou Administrador de suporte.



== Sintaxe

[source, cli, subs="+macros"]
----

set storageArray autoSupport deliveryMethod=email mailRelayServer="mail.example.com" senderEmail="sender@example.com"
----


== Parâmetros

[cols="2*"]
|===
| Parâmetro | Descrição 


 a| 
`deliveryMethod`
 a| 
Permite ao utilizador especificar o método de entrega para a coleção AutoSupport. As opções válidas são:

* e-mail
* HTTPS


[NOTE]
====
Se o método de e-mail estiver configurado, o OnDemand do AutoSupport e o Diagnóstico remoto serão desativados.

====


 a| 
`direct`
 a| 
Permite que o usuário se conete diretamente aos sistemas de suporte técnico de destino usando o protocolo HTTP ou HTTPS.



 a| 
`proxyConfigScript`
 a| 
Permite ao utilizador especificar a localização de um ficheiro de script PAC (Proxy Auto-Configuration)



 a| 
`proxyServer`
 a| 
Permite que o usuário especifique os detalhes do servidor proxy HTTP(S) necessários para estabelecer conexão com o sistema de suporte técnico de destino.



 a| 
`hostAddress`
 a| 
Permite que o usuário especifique o endereço de host do servidor proxy. Necessário se o proxyServer for usado.



 a| 
`portNumber`
 a| 
Permite que o usuário especifique o número da porta do servidor proxy. Necessário se o proxyServer for usado.



 a| 
`username`
 a| 
Permite que o usuário especifique o nome de usuário do servidor proxy se ele estiver configurado.



 a| 
`password`
 a| 
Permite que o usuário especifique a senha do servidor proxy se estiver configurado.

|===


== Nível mínimo de firmware

8,40



== Exemplos

[listing]
----

SMcli -n Array1 -c "set storageArray autoSupport deliveryMethod=HTTP direct;"

SMcli -n Array1 -c "set storageArray autoSupport deliveryMethod=HTTP
proxyConfigScript=\"http://company.com/~username/proxy.pac\";"

SMcli -n Array1 -c "set storageArray autoSupport deliveryMethod=HTTPS
proxyServer hostAddress=10.117.12.112 portNumber=8080 userName=\"tracyt\" password=\"1234456\";"

SMcli completed successfully.
----


== Verificação

Envie uma mensagem de teste usando o `start storageArray autoSupport deliveryTest` comando para verificar se seus métodos de entrega estão configurados corretamente.



== Nível mínimo de firmware

8,40
