---
permalink: commands-a-z/set-storagearray-pqvalidateonreconstruct.html 
sidebar: sidebar 
keywords: set, storage, array, pq validation, reconstruct 
summary: O comando Set storageArray pqValidateOnReconstruct define o estado de validação P/Q do storage na reconstrução. Quando essa capacidade está ativada, os dados são reconstruídos usando dados P e dados Q, e os resultados são verificados para verificar a consistência antes de determinar como proceder. 
---
= Defina a validação PQ do storage array no Reconstruct
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
O `set storageArray pqValidateOnReconstruct` comando define o estado de validação P/Q do storage na reconstrução. Quando essa capacidade está ativada, os dados são reconstruídos usando dados P e dados Q, e os resultados são verificados para verificar a consistência antes de determinar como proceder.



== Arrays compatíveis

Esse comando se aplica a um storage array individual de armazenamento E4000, E2800, E5700, EF600 ou EF300. Ele não opera em matrizes de armazenamento E2700 ou E5600.



== Funções

Para executar esse comando em um storage array E4000, 2800, E5700, EF600 ou EF300, você deve ter a função Administrador de armazenamento.



== Contexto

Esse recurso se aplica a pools de discos e grupos de volume RAID 6, que têm paridade dupla. Nesse caso, ainda há redundância no grupo de volumes ou no pool de discos quando uma unidade falha, portanto, é possível verificar a consistência de dados e paridade durante a reconstrução. Se for detetada uma inconsistência durante a reconstrução e o Data Assurance estiver ativado para o volume, poderá ser possível identificar a origem da inconsistência para que os dados possam ser reconstruídos utilizando as unidades restantes. Se esse recurso estiver ativado e o Data Assurance não estiver habilitado para o volume ou se a inconsistência não puder ser isolada em uma única unidade, o bloco que está sendo reconstruído será marcado como ilegível.

A validação pode aumentar os tempos de reconstrução para unidades SSD, pelo que esta funcionalidade pode ser ativada ou desativada com base no tipo de material. Se ativado para um determinado tipo de Mídia, o recurso será aplicado a todos os pools e grupos de volume RAID 6 usando esse tipo de Mídia.



== Sintaxe

[source, cli]
----
set storageArray pqValidateOnReconstruct (enable | disable) driveMediaType=(hdd | ssd | allMedia)
----


== Parâmetros

[cols="2*"]
|===
| Parâmetro | Descrição 


 a| 
`pqValidateOnReconstruct`
 a| 
Modifica a validação P/Q na capacidade de reconstrução.



 a| 
`enable` ou `disable`
 a| 
Ativa ou desativa a validação P/Q na reconstrução.



 a| 
`driveMediaType`
 a| 
O tipo de material de condução no qual definir a validação P/Q na capacidade de reconstrução. São suportados os seguintes tipos de material de disco:

* `hdd` indica que pretende definir o estado de validação em unidades de disco rígido
* `ssd` indica que você deseja definir o estado de validação em discos de estado sólido
* `allMedia` indica que pretende definir o estado de validação em todos os suportes da matriz de armazenamento.


|===


== Exemplo com o tipo de Mídia da unidade especificado como unidades de disco rígido

[listing]
----

SMcli -n Array1 -c "set storageArray pqValidateOnReconstruct enable driveMediaType=hdd;"

SMcli completed successfully.
----


== Exemplo com o tipo de Mídia de unidade especificado como unidades de estado sólido

[listing]
----

SMcli -n Array1 -c "set storageArray pqValidateOnReconstruct disable driveMediaType=ssd;"

SMcli completed successfully.
----


== Nível mínimo de firmware

8,42
