---
permalink: commands-a-z/set-storagearray-isnsipv4configurationmethod.html 
sidebar: sidebar 
keywords: set, storage, array, isns, server, ipv4, address 
summary: 'O comando Set storageArray isnsIPv4ConfigurationMethod define o método de configuração e o endereço de um iSNS (Internet Storage Name Service) IPv4.' 
---
= Defina o endereço do servidor iSNS do storage array IPv4
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
O `set storageArray isnsIPv4ConfigurationMethod` comando define o método de configuração e o endereço de um iSNS (Internet Storage Name Service) do IPv4.



== Arrays compatíveis

Este comando se aplica a qualquer storage array individual, incluindo os arrays E4000, E2700, E5600, E2800, E5700, EF600 e EF300, desde que todos os pacotes SMcli estejam instalados.



== Funções

Para executar esse comando em um storage array E4000, E2800, E5700, EF600 ou EF300, você deve ter a função Administrador de armazenamento.



== Sintaxe

[source, cli, subs="+macros"]
----
set storageArray isnsIPv4ConfigurationMethod=(static | dhcp)
isnsIPv4Address=pass:quotes[_ipAddress_]
----


== Parâmetros

[cols="2*"]
|===
| Parâmetros | Descrição 


 a| 
`isnsIPv4ConfigurationMethod`
 a| 
O método que você deseja usar para definir a configuração do servidor iSNS. Você pode inserir o endereço IP dos servidores IPv4 iSNS selecionando `static`. Para IPv4, pode optar por um servidor DHCP (Dynamic Host Configuration Protocol) selecionar o endereço IP do servidor iSNS introduzindo `dhcp`. Para ativar o DHCP, tem de definir o `isnsIPv4Address` parâmetro como `0.0.0.0`.



 a| 
`isnsIPv4Address`
 a| 
O endereço IP que você deseja usar para o servidor iSNS. Utilizar este parâmetro com o `static` valor para IPv4 configurações. Se optar por um servidor DHCP definir o endereço IP de um servidor iSNS Internet IPv4, tem de definir o `*isnsIPv4Address*` parâmetro como `0.0.0.0`.

|===


== Notas

O protocolo iSNS facilita a descoberta, o gerenciamento e a configuração automatizada de dispositivos iSCSI e de Fibre Channel em uma rede TCP/IP. O iSNS fornece serviços de descoberta e gerenciamento de armazenamento inteligentes comparáveis aos encontrados em redes Fibre Channel, o que permite que uma rede IP comum funcione em uma capacidade semelhante à de uma rede de área de armazenamento. O iSNS também facilita uma integração perfeita de redes IP e redes Fibre Channel, devido à capacidade de emular dispositivos e dispositivos Fibre Channel.

O servidor DHCP passa parâmetros de configuração, como endereços de rede, para nós IP. O DHCP permite que um cliente adquira todos os parâmetros de configuração IP que ele precisa para operar. O DHCP permite alocar automaticamente endereços de rede reutilizáveis.



== Nível mínimo de firmware

7,10
