---
permalink: commands-a-z/set-volume-ssdcacheenabled.html 
sidebar: sidebar 
keywords: set, ssd, cache, volume 
summary: O comando Set volume ssdCacheEnabled ativa ou desativa o armazenamento em cache usando o recurso cache SSD para um volume específico. 
---
= Definir cache SSD para um volume
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
O `set volume ssdCacheEnabled` comando liga ou desliga o cache usando o recurso cache SSD para um volume específico.



== Arrays compatíveis

Este comando se aplica a qualquer storage array individual, incluindo os arrays E4000, E2700, E5600, E2800, E5700, EF600 e EF300, desde que todos os pacotes SMcli sejam instalados.



== Funções

Para executar esse comando em um storage array E4000, E2800, E5700, EF600 ou EF300, você deve ter a função Admin de suporte.



== Contexto

O volume pode ser um destes:

* Volume padrão, identificado por um nome ou por um WWID
* Volume do Snapshot
* Volume de snapshot de grupo de consistência




== Sintaxe aplicável a um volume padrão

[source, cli, subs="+macros"]
----
set volume (pass:quotes[[_volumeName_]] | <"WWID">) ssdCacheEnabled=(TRUE | FALSE)
----


== Sintaxe aplicável a um volume instantâneo

[source, cli, subs="+macros"]
----
set snapVolume pass:quotes[["_snapVolumeName_"]] ssdCacheEnabled=(TRUE | FALSE)
----


== Sintaxe aplicável a um volume instantâneo de grupo de consistência

[source, cli, subs="+macros"]
----
set cgSnapVolume pass:quotes[["_cgSnapVolumeName_"]] ssdCacheEnabled=(TRUE | FALSE)
----


== Parâmetros

[cols="2*"]
|===
| Parâmetro | Descrição 


 a| 
`volume`
 a| 
O nome do volume padrão para o qual você deseja ativar ou desativar o cache SSD. Coloque o nome do volume entre colchetes ([ ]). Se o nome do volume tiver carateres especiais ou números, você deve incluir o nome do volume entre aspas duplas (" ") dentro de colchetes ([ ]).



 a| 
`volume`
 a| 
O World Wide Identifier (WWID) do volume padrão para o qual você deseja ativar ou desativar o cache SSD. Coloque o WWID entre aspas duplas (" ") entre colchetes angulares ( ).



 a| 
`snapVolume`
 a| 
O nome do volume instantâneo para o qual você deseja ativar ou desativar o cache SSD. Coloque o nome do volume instantâneo entre aspas duplas (" ") dentro de colchetes ([ ]).



 a| 
`cgSnapVolume`
 a| 
O nome do volume instantâneo do grupo de consistência para o qual você deseja ativar ou desativar o cache SSD. Inclua o nome do volume instantâneo do grupo de consistência entre aspas duplas (" ") dentro de colchetes ([ ]).



 a| 
`ssdCacheEnabled`
 a| 
Para ativar o cache SSD, defina este parâmetro como `TRUE`. Para desativar o cache SSD, defina este parâmetro como `FALSE`.

|===


== Notas

Você pode ativar ou desativar o cache SSD por apenas um volume de cada vez.

Quando você desativa o cache SSD para um volume, o cache SSD para esse volume é purgado.



== Nível mínimo de firmware

7,84

O 11,80 adiciona suporte a array EF600 e EF300
