---
permalink: commands-a-z/set-storagearray-managementinterface.html 
sidebar: sidebar 
keywords: set, storage, array, management, interface 
summary: O comando set storageArray managementInterface altera a interface de gerenciamento do controlador. Altere o tipo de interface de gerenciamento para garantir a confidencialidade entre o storage array e seu software de gerenciamento ou para acessar ferramentas externas. 
---
= Definir a interface de gerenciamento de array de storage
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
O `set storageArray managementInterface` comando altera a interface de gerenciamento do controlador. Altere o tipo de interface de gerenciamento para garantir a confidencialidade entre o storage array e seu software de gerenciamento ou para acessar ferramentas externas.



== Arrays compatíveis

Este comando se aplica a um storage array individual de armazenamento E2800, E5700, EF600 ou EF300. Ele não opera em matrizes de armazenamento E2700 ou E5600.



== Funções

Para executar esse comando em um storage array E2800, E5700, EF600 ou EF300, você deve ter a função Security Admin.



== Sintaxe

[listing]
----

set storageArray managementInterface restOnly={true | false}
----


== Parâmetros

[cols="2*"]
|===
| Parâmetro | Descrição 


 a| 
`restOnly`
 a| 
Quando definido como `true`, indica que a interface RESTful é a única interface de gerenciamento permitida. Essa interface impõe uma conexão criptografada entre o storage array e o software de gerenciamento.

Quando definido como `false`, indica que a interface herdada entre o storage array e o software de gerenciamento é permitida. Esta interface não está encriptada.

Algumas ferramentas que se comunicam diretamente com a interface de gerenciamento herdada, como o provedor SMI-S do SANtricity ou o OnCommand Insight (OCI), não funcionarão a menos que o `restOnly` parâmetro esteja definido como `false`. Entre em Contato com o suporte técnico para obter mais informações.

|===


== Exemplos

[listing]
----

SMcli -n Array1 -c "set storageArray managementInterface restOnly=true;"

SMcli completed successfully.
----