---
permalink: commands-a-z/set-iscsiinitiator.html 
sidebar: sidebar 
keywords: set, iscsi, initiator 
summary: O comando Set iscsiInitiator define os atributos de um iniciador iSCSI. 
---
= Definir iniciador iSCSI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
O `set iscsiInitiator` comando define os atributos de um iniciador iSCSI.



== Arrays compatíveis

Este comando se aplica a qualquer storage array individual, incluindo os arrays E4000, E2700, E5600, E2800, E5700, EF600 e EF300, desde que todos os pacotes SMcli estejam instalados.



== Funções

Para executar esse comando em um storage array E4000, E2800, E5700, EF600 ou EF300, você deve ter a função Administrador de armazenamento.

[NOTE]
====
Este comando está obsoleto e é substituído pelo xref:set-initiator.adoc[Definir iniciador]comando.

====


== Sintaxe

[source, cli, subs="+macros"]
----
set iscsiInitiator (pass:quotes[["_initiatorUserLabel_"]] | <"_iscsiInitiatorName_">)
(userLabel=pass:quotes["_newName_"] |
host=pass:quotes["_newHostName_"] |
chapSecret=pass:quotes["_newSecurityKey_"])
----


== Parâmetros

[cols="2*"]
|===
| Parâmetro | Descrição 


 a| 
`initiatorUserLabel`
 a| 
A etiqueta de utilizador do iniciador iscsi do iniciador iSCSI para o qual pretende definir atributos. Coloque a etiqueta do utilizador do iniciador iSCSI em aspas duplas (" ") dentro de colchetes ([ ]).

[NOTE]
====
Inicie o rótulo do usuário do iniciador com o nome do host ao qual a porta do host está conetada. Como pode haver mais de um identificador de porta de host em um host, use um sufixo exclusivo para o ID da porta do host. Se o nome do host for `ICTM1590S02H1` o rótulo do iniciador, será exibido da seguinte forma:

====
[listing]
----
set iscsiInitiator ["ICTM1590S02H1_AA"]
----


 a| 
`iscsiInitiatorName`
 a| 
O nome do iniciador para o qual você deseja definir atributos. Coloque as `iscsiInitiatorName` aspas duplas (" ") dentro dos suportes angulares ( ).

[NOTE]
====
O `iscsiInitiatorName` é o iSCSI Qualified Name (iqn). Um exemplo:

====
[listing]
----
set iscsiInitiator <"iqn.2016-11.com.vmware.iscsi:ictm1509s02h1">
----


 a| 
`userLabel`
 a| 
A nova etiqueta de utilizador que pretende utilizar para o iniciador iSCSI. Coloque a nova etiqueta de utilizador entre aspas duplas (" ").

[NOTE]
====
Uma prática recomendada é iniciar o rótulo do usuário do iniciador com o nome do host ao qual a porta do host está conetada. Como pode haver mais de um identificador de porta de host em um host, use um sufixo exclusivo para o ID da porta do host. Se o nome do host for `ICTM1590S02H1`, um exemplo da etiqueta do usuário do iniciador é mostrado abaixo:

====
[listing]
----
set iscsiInitiator ["ICTM1590S02H1_AA"]
----


 a| 
`host`
 a| 
O nome do novo host ao qual a porta do host está conetada. Inclua o nome do host em aspas duplas (" "). Um exemplo é mostrado abaixo:

[listing]
----
["ICTM1590S02H2"]
----


 a| 
`chapSecret`
 a| 
A chave de segurança que você deseja usar para autenticar uma conexão peer. Coloque a chave de segurança entre aspas duplas (" ").

|===


== Notas

Você pode usar qualquer combinação de carateres alfanuméricos, hífens e sublinhados para os nomes. Os nomes podem ter um máximo de 30 carateres.

O CHAP (Challenge Handshake Authentication Protocol) é um protocolo que autentica o ponto de uma conexão. O CHAP é baseado nos pares que compartilham um _segredo_. Um segredo é uma chave de segurança semelhante a uma senha.

Use o `chapSecret` parâmetro para configurar as chaves de segurança para iniciadores que exigem uma autenticação mútua. O segredo CHAP deve ter entre 12 carateres e 57 carateres. Esta tabela lista os carateres válidos.

[cols="1a,1a,1a,1a,1a,1a,1a,1a,1a,1a,1a,1a"]
|===


 a| 
Espaço
 a| 
!
 a| 
"
 a| 
N.o
 a| 
Custo
 a| 
%
 a| 

 a| 
'
 a| 
(
 a| 
)
 a| 
*
 a| 



 a| 
,
 a| 
-
 a| 
.
 a| 
/
 a| 
0
 a| 
1
 a| 
2
 a| 
3
 a| 
4
 a| 
5
 a| 
6
 a| 
7



 a| 
8
 a| 
9
 a| 
:
 a| 
;
 a| 

 a| 
.
 a| 

 a| 
?
 a| 
A
 a| 
A
 a| 
B
 a| 
C



 a| 
D
 a| 
E
 a| 
F
 a| 
G
 a| 
H
 a| 
I
 a| 
J
 a| 
K
 a| 
L
 a| 
M
 a| 
N
 a| 
O



 a| 
P
 a| 
P
 a| 
R
 a| 
S
 a| 
T
 a| 
U
 a| 
V
 a| 
W
 a| 
X
 a| 
Y
 a| 
Z
 a| 
[



 a| 
*
 a| 
]
 a| 
(Em inglês)
 a| 
_
 a| 
'
 a| 
a
 a| 
b
 a| 
c
 a| 
d
 a| 
e
 a| 
f
 a| 
g



 a| 
h
 a| 
i
 a| 
j
 a| 
k
 a| 
l
 a| 
m
 a| 
n
 a| 
o
 a| 
p
 a| 
p
 a| 
r
 a| 
s



 a| 
t
 a| 
u
 a| 
v
 a| 
w
 a| 
x
 a| 
y
 a| 
z
 a| 
(2
 a| 
|
 a| 
Selecione
 a| 
.
 a| 

|===


== Nível mínimo de firmware

7,10

8,41 este comando está obsoleto.
