---
permalink: commands-a-z/set-consistency-group-attributes.html 
sidebar: sidebar 
keywords: set, consistency, group, attributes 
summary: O comando Set consistentcyGroup define as propriedades de um grupo de consistência de snapshot. 
---
= Definir atributos de grupo de consistência
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
O `set consistencyGroup` comando define as propriedades de um grupo de consistência de snapshot.



== Arrays compatíveis

Este comando se aplica a qualquer storage array individual, incluindo os arrays E2700, E5600, E2800, E5700, EF600 e EF300, desde que todos os pacotes SMcli estejam instalados.



== Funções

Para executar esse comando em um storage array E2800, E5700, EF600 ou EF300, você deve ter a função Administrador do armazenamento.



== Sintaxe

[listing, subs="+macros"]
----
set consistencyGroup pass:quotes[["_consistencyGroupName_"]]
[userLabel=pass:quotes["_consistencyGroupName_"]]
[repositoryFullPolicy=(failBaseWrites | purgeSnapImages)]
[repositoryFullLimit=pass:quotes[_percentValue_]]
[autoDeleteLimit=pass:quotes[_numberOfSnapImages_]]
[rollbackPriority=(lowest | low | medium | high | highest)]
----


== Parâmetros

[cols="2*"]
|===
| Parâmetro | Descrição 


 a| 
`consistencyGroupName`
 a| 
O nome do grupo de consistência para o qual você está definindo propriedades. Coloque o nome do grupo de consistência entre aspas duplas (" ") dentro de colchetes ([ ]).



 a| 
`userLabel`
 a| 
O novo nome que você deseja dar ao grupo de consistência de snapshot. Inclua o novo nome do grupo de consistência entre aspas duplas (" ").



 a| 
`repositoryFullPolicy`
 a| 
Como você deseja que o processamento de snapshot continue se os volumes do repositório de snapshot estiverem cheios. Pode optar por falhar gravações no volume (`failBaseWrites`base ) ou eliminar (limpar) as imagens instantâneas  `purgeSnapImages`). A ação padrão é `purgeSnapImages`.



 a| 
`repositoryFullLimit`
 a| 
A porcentagem da capacidade do repositório na qual você recebe um aviso de que o volume do repositório instantâneo está quase cheio. Use valores inteiros. Por exemplo, um valor de 70 significa 70%. O valor padrão é 75.



 a| 
`autoDeleteLimit`
 a| 
Cada grupo de consistência pode ser configurado para executar a eliminação automática das suas imagens de instantâneos para manter o número total de imagens de instantâneos no grupo de instantâneos a ou abaixo de um nível designado. Quando esta opção está ativada, sempre que uma nova imagem instantânea for criada no grupo de instantâneos, o sistema elimina automaticamente a imagem instantânea mais antiga do grupo para cumprir o valor limite. Essa ação libera a capacidade do repositório para que ele possa ser usado para atender aos requisitos contínuos de cópia na gravação para as imagens snapshot restantes.



 a| 
`rollBackPriority`
 a| 
A prioridade para operações de reversão para um grupo de consistência enquanto o storage array estiver operacional. Os valores válidos são `highest`, `high`, `medium`, `low` `lowest` ou .

|===


== Notas

Você pode usar qualquer combinação de carateres alfanuméricos, sublinhado (_), hífen (-) e libra ( no) para os nomes. Os nomes podem ter um máximo de 30 carateres.

Quando você usa este comando, você pode especificar um ou mais parâmetros. No entanto, você não precisa usar todos os parâmetros.

A prioridade de reversão define a quantidade de recursos do sistema que devem ser alocados à operação de reversão à custa do desempenho do sistema. Um valor de `high` indica que a operação de reversão é priorizada sobre todas as outras e/S do host Um valor de `low` indica que a operação de reversão deve ser executada com impactos mínimo na e/S do host



== Eliminação automática

Pode configurar cada grupo de instantâneos para efetuar a eliminação automática das suas imagens instantâneas, de forma a manter o número total de imagens instantâneas no grupo de instantâneos a um número máximo de imagens ou inferior a um número máximo de imagens. Quando o número de imagens instantâneas no grupo de instantâneos está no limite máximo, o `autoDeleteLimit` parâmetro elimina automaticamente as imagens instantâneas sempre que uma nova imagem instantânea é criada no grupo de instantâneos. O `autoDeleteLimit` parâmetro elimina as imagens instantâneas mais antigas do grupo de instantâneos até que o número máximo de imagens definido com o parâmetro seja atingido. A exclusão de imagens snapshot dessa forma libera a capacidade do repositório para que ele possa ser usado para atender aos requisitos de cópia em gravação para as imagens snapshot restantes.



== Nível mínimo de firmware

7,83
