---
permalink: commands-a-z/set-email-smtp-delivery-method.html 
sidebar: sidebar 
keywords: specify, email, smtp, delivery method, individual, E2800, E5700, arrays 
summary: 'O comando Set storageArray AutoSupport deliveryMethod configura o método de entrega para enviar mensagens AutoSupport para e-mail (SMTP).' 
---
= Especifique o método de entrega de e-mail (SMTP)
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
O `set storageArray autoSupport deliveryMethod` comando configura o método de entrega para enviar mensagens AutoSupport para e-mail (SMTP).



== Arrays compatíveis

Esse comando se aplica a um storage array individual de armazenamento E4000, E2800, E5700, EF600 ou EF300. Ele não opera em matrizes de armazenamento E2700 ou E5600.



== Funções

Para executar esse comando em um storage array E4000, E2800, E5700, EF600 ou EF300, você deve ter a função Administrador de armazenamento ou Administrador de suporte.



== Sintaxe

[source, cli, subs="+macros"]
----
set storageArray autoSupport deliveryMethod=email
mailRelayServer=pass:quotes["_serverAddress_" senderEmail="_emailAddress_"] destinationAddress="destination1@example.com" destinationAddress="destination2@example.com";
----


== Parâmetros

[cols="2*"]
|===
| Parâmetro | Descrição 


 a| 
`deliveryMethod`
 a| 
Permite ao utilizador especificar o método de entrega para a coleção AutoSupport. As opções válidas são:

* e-mail
* HTTPS


[NOTE]
====
Se o método de e-mail estiver configurado, o OnDemand do AutoSupport e o Diagnóstico remoto serão desativados.

====


 a| 
`mailRelayServer`
 a| 
Permite que o usuário especifique o servidor de reencaminhamento de e-mail para a coleção AutoSupport.



 a| 
`senderEmail`
 a| 
Permite que o usuário especifique o endereço de e-mail de envio para a coleção AutoSupport.



 a| 
`destinationAddress`
 a| 
Endereço de e-mail para onde os envios da AutoSupport serão enviados. Este parâmetro pode ser fornecido várias vezes para permitir que os envios sejam enviados para vários endereços.

|===


=== Exemplos

[listing]
----

SMcli -n Array1 -c "set storageArray autoSupportConfig deliveryMethod=email mailRelayServer=\"mailserver.company.com\" senderEmail=\"user@company.com\";"

SMcli completed successfully.
----


=== Verificação

Envie uma mensagem de teste usando o `_start storageArray autoSupport deliveryTest_` comando para verificar se seus métodos de entrega estão configurados corretamente.



== Nível mínimo de firmware

8,40
