---
permalink: commands-a-z/set-storagearray-autosupportmaintenancewindow.html 
sidebar: sidebar 
keywords: enable, disable, autosupport, maintenance, window, individual, E2800, E5700, arrays 
summary: O comando Set storageArray autoSupportMaintenanceWindow liga ou desliga o recurso janela de manutenção do AutoSupport. 
---
= Ative ou desative a janela de manutenção do AutoSupport
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
O `set storageArray autoSupportMaintenanceWindow` comando liga ou desliga o recurso da janela de manutenção do AutoSupport.

Use uma janela de manutenção para suprimir a criação automática de ticket em eventos de erro. No modo de operação normal, a matriz de armazenamento usará o AutoSupport para abrir um caso com suporte técnico se houver um problema. Quando o AutoSupport é colocado numa janela de manutenção, esta funcionalidade é suprimida.



== Arrays compatíveis

Esse comando se aplica a um storage array individual de armazenamento E4000, E2800, E5700, EF600 ou EF300. Ele não opera em matrizes de armazenamento E2700 ou E5600.



== Funções

Para executar esse comando em um storage array E4000, E2800, E5700, EF600 ou EF300, você deve ter a função Administrador de armazenamento ou Administrador de suporte.



== Sintaxe

[source, cli]
----
set storageArray autoSupportMaintenanceWindow (enable | disable)
    emailAddresses=("emailAddress1" "emailAddress2" ...)
    [duration=<duration_in_hours>];
----


== Parâmetros

[cols="2*"]
|===
| Parâmetro | Descrição 


 a| 
`emailAddresses`
 a| 
A lista de endereços de e-mail para receber um e-mail de confirmação de que a solicitação da janela de manutenção foi processada. Você pode especificar até cinco endereços de e-mail.



 a| 
`duration`
 a| 
Opcional. A duração (em horas) para ativar a janela de manutenção. Se omitido, é utilizada a duração máxima suportada (72 horas).

|===


== Exemplos

[listing]
----

SMcli -n Array1 -c "set storageArray autoSupportMaintenanceWindow enable
      emailAddresses=\"me@company.com\" duration=5;"

SMcli completed successfully.
----
[listing]
----
SMcli -n Array1 -c "set storageArray autoSupportMaintenanceWindow enable
      emailAddresses=(\"me1@company.com\" \"me2@company.com\");"

SMcli completed successfully.
----
[listing]
----
SMcli -n Array1 -c "set storageArray autoSupportMaintenanceWindow disable
      emailAddresses=(\"me1@company.com\" \"me2@company.com\" \"me3@company.com\"
      \"me4@company.com\" \"me5@company.com\");"

SMcli completed successfully.
----


== Nível mínimo de firmware

8,42
