---
permalink: commands-a-z/set-isertarget.html 
sidebar: sidebar 
keywords: set, iser, target 
summary: O comando Set iserTarget define propriedades para um destino iSER. 
---
= Defina o destino iSER
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
O `set iserTarget` comando define propriedades para um destino iSER.



== Arrays compatíveis

Este comando se aplica a qualquer storage array individual, incluindo os arrays E2700, E5600, E2800, E5700, EF600 e EF300, desde que todos os pacotes SMcli estejam instalados.



== Funções

Para executar esse comando em um storage array E2800, E5700, EF600 ou EF300, você deve ter a função Administrador do armazenamento.

[NOTE]
====
Este comando está obsoleto e é substituído pelo xref:set-target.adoc[Definir propriedades de destino]comando.

====


== Sintaxe

[source, cli, subs="+macros"]
----
set iserTarget pass:quotes[["_userLabel_"]]
authenticationMethod=(none | chap) |
chapSecret=pass:quotes[_securityKey_] |
targetAlias=pass:quotes["_userLabel_"]
----


== Parâmetros

[cols="2*"]
|===
| Parâmetro | Descrição 


 a| 
`iserTarget`
 a| 
O destino iSER para o qual você deseja definir propriedades. Coloque as `_userLabel_` aspas duplas (" "). Você também deve incluir os `_userLabel_` colchetes ([ ]) se o rótulo do usuário for um alias de destino ou colchetes de ângulo ( ) se o rótulo do usuário for um IQN (iSCSI Qualified Name).



 a| 
`authenticationMethod`
 a| 
O meio de autenticar sua sessão iSCSI.



 a| 
`chapSecret`
 a| 
A chave de segurança que você deseja usar para autenticar uma conexão peer.



 a| 
`targetAlias`
 a| 
O novo nome que você deseja usar para o destino. Coloque o nome entre aspas duplas (" ").

|===


== Notas

O CHAP (Challenge Handshake Authentication Protocol) é um protocolo que autentica o ponto de uma conexão. O CHAP é baseado nos pares que compartilham um _segredo_. Um segredo é uma chave de segurança semelhante a uma senha.

Use o `chapSecret` parâmetro para configurar as chaves de segurança para iniciadores que exigem uma autenticação mútua. O segredo CHAP deve ter entre 12 carateres e 57 carateres. Esta tabela lista os carateres válidos.

[cols="1a,1a,1a,1a,1a,1a,1a,1a,1a,1a,1a,1a"]
|===


 a| 
Espaço
 a| 
!
 a| 
"
 a| 
N.o
 a| 
Custo
 a| 
%
 a| 

 a| 
'
 a| 
(
 a| 
)
 a| 
*
 a| 



 a| 
,
 a| 
-
 a| 
.
 a| 
/
 a| 
0
 a| 
1
 a| 
2
 a| 
3
 a| 
4
 a| 
5
 a| 
6
 a| 
7



 a| 
8
 a| 
9
 a| 
:
 a| 
;
 a| 

 a| 
.
 a| 

 a| 
?
 a| 
A
 a| 
A
 a| 
B
 a| 
C



 a| 
D
 a| 
E
 a| 
F
 a| 
G
 a| 
H
 a| 
I
 a| 
J
 a| 
K
 a| 
L
 a| 
M
 a| 
N
 a| 
O



 a| 
P
 a| 
P
 a| 
R
 a| 
S
 a| 
T
 a| 
U
 a| 
V
 a| 
W
 a| 
X
 a| 
Y
 a| 
Z
 a| 
[



 a| 
*
 a| 
]
 a| 
(Em inglês)
 a| 
_
 a| 
'
 a| 
a
 a| 
b
 a| 
c
 a| 
d
 a| 
e
 a| 
f
 a| 
g



 a| 
h
 a| 
i
 a| 
j
 a| 
k
 a| 
l
 a| 
m
 a| 
n
 a| 
o
 a| 
p
 a| 
p
 a| 
r
 a| 
s



 a| 
t
 a| 
u
 a| 
v
 a| 
w
 a| 
x
 a| 
y
 a| 
z
 a| 
(2
 a| 
|
 a| 
Selecione
 a| 
.
 a| 

|===


== Nível mínimo de firmware

8,20

8,41 este comando está obsoleto.
