---
permalink: commands-a-z/set-storagearray-externalkeymanagement.html 
sidebar: sidebar 
keywords: set, external, key, management, set 
summary: O comando Set storageArray externalKeyManagement configura o endereço do servidor de gerenciamento de chaves externas e o número da porta. 
---
= Defina as configurações de gerenciamento de chaves externas
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
O `set storageArray externalKeyManagement` comando configura o endereço do servidor de gerenciamento de chaves externo e o número da porta.



== Arrays compatíveis

Este comando se aplica a um storage array individual de armazenamento E2800, E5700, EF600 ou EF300. Ele não opera em matrizes de armazenamento E2700 ou E5600.



== Funções

Para executar esse comando em um storage array E2800, E5700, EF600 ou EF300, você deve ter a função Security Admin.



== Contexto

[NOTE]
====
Este comando aplica-se apenas ao gerenciamento de chaves externas.

====


== Sintaxe

[listing, subs="+macros"]
----

set storageArray externalKeyManagement serverAddress=pass:quotes[_serverAddress_]
serverPort=pass:quotes[_portNumber_]
----


== Parâmetros

[cols="2*"]
|===
| Parâmetro | Descrição 


 a| 
`serverAddress`
 a| 
Permite especificar o endereço do servidor de gerenciamento de chaves externo. O endereço do servidor pode ser um nome de domínio totalmente qualificado, endereço IPv4 ou endereço IPv6.



 a| 
`serverPort`
 a| 
Permite especificar o número da porta do servidor de gerenciamento de chaves externo.

|===


== Exemplo

[listing]
----
SMcli -n Array1 -c "set storageArray externalKeyManagement serverAddress=192.0.2.1 serverPort=8081;"

   SMcli completed successfully.
----


== Nível mínimo de firmware

8,40
