---
permalink: commands-a-z/set-drive-securityid.html 
sidebar: sidebar 
keywords: set, fips, drive, security, identifier 
summary: O comando Set drive securityID é usado para redefinir uma unidade FIPS de volta às configurações originais do fabricante. 
---
= Defina o identificador de segurança da unidade FIPS
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
O `set drive securityID` comando é usado para redefinir uma unidade FIPS de volta às configurações originais do fabricante.



== Arrays compatíveis

Este comando se aplica a qualquer storage array individual, incluindo os arrays E2700, E5600, E2800, E5700, EF600 e EF300, desde que todos os pacotes SMcli estejam instalados.



== Funções

Para executar esse comando em um storage array E2800, E5700, EF600 ou EF300, você deve ter a função Security Admin.



== Contexto

[NOTE]
====
Este comando repõe uma unidade FIPS de volta às configurações originais do fabricante e apaga todos os dados existentes da unidade. Esta operação é completamente irreversível. Isso pode ser necessário se a unidade estiver bloqueada devido a um arquivo de chave de segurança inválido ou ausente ou frase-passe desconhecida. Todos os dados da unidade existentes serão apagados.

====
Para apagar uma unidade FDE, utilize o `start secureErase` comando.



== Sintaxe

[listing, subs="+macros"]
----
set drive pass:quotes[[_trayID_],pass:quotes[[_drawerID_,]]pass:quotes[_slotID_]] securityID="string"
----


== Parâmetros

[cols="2*"]
|===
| Parâmetro | Descrição 


 a| 
`drive`
 a| 
Para bandejas de unidades de alta capacidade, especifique o valor de ID da bandeja, o valor de ID da gaveta e o valor de ID do slot para a unidade. Para bandejas de unidades de baixa capacidade, especifique o valor de ID da bandeja e o valor de ID do slot para a unidade. Os valores de ID da bandeja são `0` para `99`. Os valores de ID da gaveta são `1` para `5`.

Todos os máximos de ID de slot são 24. Os valores de ID do slot começam em 0 ou 1, dependendo do modelo da bandeja. As bandejas de unidades compatíveis com os controladores E2800 e E5700 têm números de ID de slot a partir de 0. As bandejas de unidades compatíveis com os controladores E2700 e E5600 têm números de ID de slot a partir de 1.

Inclua o valor de ID da bandeja, o valor de ID da gaveta e o valor de ID do slot entre colchetes ([ ]).



 a| 
`securityID`
 a| 
O ID de segurança da unidade a apagar, em forma de cadeia de carateres. Esta cadeia pode ter um máximo de 32 carateres. A forma do ID de segurança varia de acordo com o fabricante.

[NOTE]
====
Para encontrar a ID de segurança, remova a unidade e leia a ID de segurança na etiqueta do recipiente.

====
|===


== Notas

 `drive`O parâmetro dá suporte a bandejas de unidades de alta capacidade e bandejas de unidades de baixa capacidade. Uma bandeja de unidades de alta capacidade tem gavetas que prendem as unidades. As gavetas deslizam para fora da bandeja de unidades para fornecer acesso às unidades. Uma bandeja de unidades de baixa capacidade não tem gavetas. Para uma bandeja de unidades de alta capacidade, você deve especificar o identificador (ID) da bandeja de unidades, o ID da gaveta e o ID do slot no qual uma unidade reside. Para uma bandeja de unidades de baixa capacidade, você precisa especificar apenas o ID da bandeja de unidades e o ID do slot em que uma unidade reside. Para uma bandeja de unidades de baixa capacidade, um método alternativo para identificar um local para uma unidade é especificar a ID da bandeja de unidades, definir a ID da gaveta como `0` e especificar a ID do slot no qual uma unidade reside.



== Exemplo

[listing]
----
set drive [1,31,4] securityID="V2zdvLTdGWdWyTALGHns";
----


== Nível mínimo de firmware

8,25
