---
permalink: commands-a-z/set-storagearray-passwordlength.html 
sidebar: sidebar 
keywords: set, storage, array, password, length 
summary: O comando Set storageArray passwordlength permite que o usuário admin defina um comprimento mínimo para todas as senhas novas ou atualizadas no storage array. 
---
= Defina o comprimento da senha do storage array
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
O `set storageArray passwordlength` comando permite que o usuário admin defina um comprimento mínimo para todas as senhas novas ou atualizadas na matriz de armazenamento.



== Arrays compatíveis

Esse comando se aplica a um storage array individual de armazenamento E4000, E2800, E5700, EF600 ou EF300. Ele não opera em matrizes de armazenamento E2700 ou E5600.



== Funções

Para executar esse comando em um storage array E4000, E2800, E5700, EF600 ou EF300, você deve ter a função Security Admin.



== Sintaxe

[source, cli]
----
set storageArray passwordLength=<INTEGER>
----


== Parâmetros

[cols="2*"]
|===
| Parâmetro | Descrição 


 a| 
`password length`
 a| 
Permite-lhe definir o comprimento mínimo necessário para todas as palavras-passe novas ou atualizadas.



 a| 
`INTEGER`
 a| 
Permite-lhe definir o comprimento mínimo necessário, entre 0 e 30, para todas as palavras-passe novas ou atualizadas.

|===


== Exemplos

[listing]
----

SMcli <array_ip> -u <username> -p <password> -c "set storageArray passwordLength=0;"

SMcli completed successfully.
----


== Nível mínimo de firmware

8,41 adiciona o comando.
