---
permalink: commands-a-z/set-storagearray-controllerhealthimageallowoverwrite.html 
sidebar: sidebar 
keywords: set, storage, array, controller, health, image, allow, overwrite 
summary: O comando Set storageArray controllerHealthImageAllowOverWrite define um sinalizador em um controlador para permitir que uma nova imagem de integridade do controlador substitua uma imagem de integridade do controlador existente em matrizes de armazenamento que suportam o recurso de imagem de integridade do controlador. 
---
= Definir a imagem de integridade do controlador da matriz de armazenamento permitir substituição
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
O `set storageArray controllerHealthImageAllowOverWrite` comando define um sinalizador em um controlador para permitir que uma nova imagem de integridade do controlador substitua uma imagem de integridade do controlador existente em matrizes de armazenamento que suportam o recurso de imagem de integridade do controlador.



== Arrays compatíveis

Este comando se aplica a qualquer storage array individual, incluindo os arrays E2700, E5600, E2800, E5700, EF600 e EF300, desde que todos os pacotes SMcli estejam instalados.



== Funções

Para executar esse comando em um storage array E2800, E5700, EF600 ou EF300, você deve ter a função Administrador do armazenamento.



== Contexto

Se o storage array não suportar o recurso de imagem de integridade do controlador, o comando retornará um erro.

[NOTE]
====
Com a versão de firmware 8,20, o `coreDumpAllowOverWrite` parâmetro é substituído pelo `controllerHealthImageAllowOverWrite` parâmetro.

====


== Sintaxe

[listing]
----
set storageArray controllerHealthImageAllowOverWrite
----


== Parâmetros

Nenhum.



== Notas

Quando a imagem de integridade do controlador é recuperada, o `allow overwrite` sinalizador é definido. Se a imagem de integridade do controlador não for recuperada, a imagem expira em 48 horas, após as quais o `allow overwrite` sinalizador é definido. Quando você usa o `set storageArray controllerHealthImageAllowOverWrite` comando para definir o `allow overwrite` sinalizador, a expiração de 48 horas é dispensada como se a imagem tivesse sido recuperada.



== Nível mínimo de firmware

7,86

8,20 substitui o `*coreDumpAllowOverWrite*` parâmetro pelo `controllerHealthImageAllowOverWrite` parâmetro.
