---
permalink: commands-a-z/set-auditlog.html 
sidebar: sidebar 
keywords: set, audit log 
summary: O comando Set Auditlog configura as configurações do log de auditoria. 
---
= Definir as definições do registo de auditoria
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
O `set auditLog` comando configura as configurações do log de auditoria.



== Arrays compatíveis

Este comando se aplica a um storage array individual de armazenamento E2800, E5700, EF600 ou EF300. Ele não opera em matrizes de armazenamento E2700 ou E5600.



== Funções

Para executar esse comando em um storage array E2800, E5700, EF600 ou EF300, você deve ter a função Security Admin.



== Sintaxe

[listing, subs="+macros"]
----

set auditLog (logLevel={all | writeOnly} |
    fullPolicy={overwrite | preventSystemAccess} |
    pass:quotes[maxRecords=_n_] | pass:quotes[warningThreshold=_n_)]
----


== Parâmetros

[cols="2*"]
|===
| Parâmetro | Descrição 


 a| 
`logLevel`
 a| 
Permite especificar o nível de registo. As opções válidas são: `all` E `writeOnly`. O valor padrão é `writeOnly`.



 a| 
`fullPolicy`
 a| 
Permite especificar a política quando o registo está cheio. As opções válidas são: `overwrite` E `preventSystemAccess`.



 a| 
`maxRecords`
 a| 
Permite que o usuário especifique o número máximo de Registros a serem armazenados onde `n` é um número inteiro começando em 30000 e terminando em 50000.



 a| 
`warningThreshold`
 a| 
Permite especificar a porcentagem em que um alerta de aviso será enviado para indicar que o log de auditoria está quase cheio quando a política completa estiver definida como `preventSystemAccess`. Use valores inteiros entre 0 e 100. Definir este parâmetro para 0 (zero) desativa os alertas de aviso.

|===


== Exemplos

[listing]
----

SMcli -n Array1 -c "set auditLog logLevel=writeOnly fullPolicy=preventSystemAccess maxRecords=40000 warningThreshold=90;"

SMcli completed successfully.
----


== Nível mínimo de firmware

8,40
