---
permalink: commands-a-z/set-syslog.html 
sidebar: sidebar 
keywords: configure, syslog, set 
summary: O comando set syslog configura as informações de alerta do syslog. Você pode configurar o monitor de eventos para enviar alertas para o servidor syslog sempre que um evento alertable ocorrer. 
---
= Configure as configurações do syslog
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
O `set syslog` comando configura as informações de alerta do syslog. Você pode configurar o monitor de eventos para enviar alertas para o servidor syslog sempre que um evento alertable ocorrer.



== Arrays compatíveis

Esse comando se aplica a um storage array individual de armazenamento E4000, E2800, E5700, EF600 ou EF300. Ele não opera em matrizes de armazenamento E2700 ou E5600.



== Funções

Para executar esse comando em um storage array E4000, E2800, E5700, EF600 ou EF300, você deve ter a função Administrador de armazenamento.



== Contexto

* O endereço do servidor syslog deve estar disponível. Este endereço pode ser um nome de domínio totalmente qualificado, um endereço IPv4 ou um endereço IPv6.
* O número da porta UDP do servidor syslog deve estar disponível. Esta porta é tipicamente 514.




== Sintaxe

[source, cli, subs="+macros"]
----
set syslog [defaultFacility=pass:quotes[_facilityNumber_]]
| [defaultTag=pass:quotes[_defaultTag_]]
| [syslogFormat=pass:quotes[_rfc3164_|_rfc5424_]]
| (serverAddresses=pass:quotes[(_serverAddress:portNumber ... serverAddress:portNumber_)]
| addServerAddresses=pass:quotes[(_serverAddress:portNumber ... serverAddress:portNumber_))]
----


== Parâmetros

[cols="2*"]
|===
| Parâmetro | Descrição 


 a| 
`defaultFacility`
 a| 
Opcional. Permite especificar o número da instalação padrão. A facilidade padrão deve ser um valor numérico entre 0 e 23.



 a| 
`defaultTag`
 a| 
Opcional. Permite especificar a tag padrão. Inclua string em aspas.



 a| 
`syslogFormat`
 a| 
O formato de mensagens usado para as mensagens syslog. O valor pode ser um dos seguintes:

* `rfc3164` - Formato compatível com RFC 3164
* `rfc5424` - Formato compatível com RFC 5424




 a| 
`serverAddresses`
 a| 
Permite definir um ou mais endereços de servidor syslog com números de porta associados. Usar esta opção Definir irá limpar os endereços de servidor existentes. Um endereço de servidor syslog pode ser um nome de domínio totalmente qualificado, endereço IPv4 ou endereço IPv6. A porta UDP deve ser um valor numérico entre 0 e 65535. Normalmente, a porta UDP para syslog é 514. Inclua todos os endereços entre parênteses. Se você inserir mais de um endereço, separe-os com um espaço.



 a| 
`addServerAddresses`
 a| 
Permite adicionar um ou mais endereços de servidor syslog com números de porta associados. A utilização desta opção Set (Definir) não elimina os endereços de servidor existentes. Um endereço de servidor syslog pode ser um nome de domínio totalmente qualificado, endereço IPv4 ou endereço IPv6. A porta UDP deve ser um valor numérico entre 0 e 65535. Normalmente, a porta UDP para syslog é 514. Inclua todos os endereços entre parênteses. Se você inserir mais de um endereço, separe-os com um espaço.

|===


== Exemplos

[listing]
----

SMcli -n Array1 -c "set syslog serverAddresses=("ICTM1402S02H2.company.com:22");"

SMcli -n Array1 -c "set syslog addServerAddresses=("serverName1.company.com:514"
"serverName2.company.com:514");"

SMcli completed successfully.
----


== Nível mínimo de firmware

8,40

11.70.1 adicionou o `syslogFormat` parâmetro para especificar o formato de mensagem Syslog.
