---
permalink: commands-a-z/show-volume-reservations.html 
sidebar: sidebar 
keywords: show, volume, reservations 
summary: O comando show volume reservations retorna informações sobre os volumes que têm reservas persistentes. 
---
= Mostrar reservas de volume
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
O `show volume reservations` comando retorna informações sobre os volumes que têm reservas persistentes.



== Arrays compatíveis

Este comando se aplica a qualquer storage array individual, incluindo os arrays E4000, E2700, E5600, E2800, E5700, EF600 e EF300, desde que todos os pacotes SMcli estejam instalados.



== Funções

Para executar esse comando em um storage array E4000, E2800, E5700, EF600 ou EF300, você deve ter a função Storage Admin ou Storage Monitor.



== Sintaxe

[source, cli, subs="+macros"]
----
show (allVolumes | volume pass:quotes[[_volumeName_]] |
volumes pass:quotes[[_volumeName1_ ... _volumeNameN_]]) reservations
----


== Parâmetros

[cols="2*"]
|===
| Parâmetro | Descrição 


 a| 
`allVolumes`
 a| 
O parâmetro para retornar estatísticas de desempenho sobre todos os volumes no storage array.



 a| 
`volume`
 a| 
O nome de um volume para o qual você deseja recuperar informações. Coloque o nome do volume entre colchetes ([ ]). Se o nome do volume tiver carateres especiais ou números, você deve incluir o nome entre aspas duplas (" ") dentro de colchetes.



 a| 
`volumes`
 a| 
Os nomes de vários volumes para os quais você deseja recuperar informações. Insira os nomes dos volumes usando estas regras:

* Inclua todos os nomes entre colchetes ([ ]).
* Separe cada um dos nomes com um espaço.


Se os nomes dos volumes tiverem carateres especiais ou números, insira os nomes usando estas regras:

* Inclua todos os nomes entre colchetes ([ ]).
* Coloque cada um dos nomes em aspas duplas (" ").
* Separe cada um dos nomes com um espaço.


|===


== Nível mínimo de firmware

5,40
