---
permalink: commands-a-z/show-ssd-cache-statistics.html 
sidebar: sidebar 
keywords: show, ssd, cache, statistics 
summary: O comando show ssdCache exibe dados sobre o uso do cache SSD. 
---
= Mostrar estatísticas de cache SSD
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
O `show ssdCache` comando exibe dados sobre o uso do cache SSD.



== Arrays compatíveis

Este comando se aplica a qualquer storage array individual, incluindo os arrays E4000, E2700, E5600, E2800, E5700, EF600 e EF300, desde que todos os pacotes SMcli sejam instalados.



== Funções

Para executar esse comando em um storage array E4000, E2800, E5700, EF600 ou EF300, você deve ter a função Admin de suporte.



== Sintaxe

[source, cli, subs="+macros"]
----
show ssdCache pass:quotes[[_ssdCacheName_]] [ssdCacheStatistics]
[controller=(a|b|both)]
pass:quotes[[file="_filename_"]]
----


== Parâmetros

[cols="2*"]
|===
| Parâmetro | Descrição 


 a| 
`ssdCache`
 a| 
O nome do cache SSD para o qual você deseja recuperar informações. Inclua o nome do cache SSD entre colchetes ([ ]). Se o nome do cache SSD tiver carateres ou números especiais, você deve incluir o nome do cache SSD em aspas duplas (" ") dentro de colchetes.



 a| 
`ssdCacheStatistics`
 a| 
Um parâmetro opcional para o `show ssdCache` comando que indica que você deseja recuperar estatísticas de cache.



 a| 
`controller`
 a| 
Cada controladora armazena metadados de cache SSD para os volumes que possui. Portanto, as estatísticas de cache SSD são mantidas e exibidas por controlador. Os identificadores válidos do controlador são `a` `b` , , ou `both`, onde `a` está o controlador no slot A , `b` é o controlador no slot B e `both` é ambos controladores. Inclua o identificador do controlador entre colchetes ([ ]). Se não especificar um controlador, o valor predefinido é `both`.



 a| 
`file`
 a| 
O caminho do arquivo e o nome do arquivo para o qual você deseja salvar as estatísticas de cache SSD. Estatísticas adicionais estão disponíveis quando você salva as estatísticas em um arquivo.

Coloque o nome do ficheiro entre aspas duplas (" "). Por exemplo:

`file="C:\Program Files\CLI\logs\ssdcachestats.csv"`.

Você pode usar qualquer nome de arquivo, mas você deve usar a `.csv` extensão.

|===


== Notas

As seguintes estatísticas são apresentadas no ecrã:

* *Reads* -- número total de leituras de host de volumes habilitados para cache SSD.
+
Compare as leituras relativas às gravações. As leituras precisam ser maiores do que as gravações para uma operação de cache SSD eficaz. Quanto maior a proporção de leituras para gravações, melhor a operação do cache.

* *Write* -- número total de gravações de host em volumes habilitados para cache SSD.
* *Cache Hits* -- uma contagem do número de acessos de cache.
* *Cache hits (%)* -- derivado de Cache Hits/Total de leituras.
+
A porcentagem de acerto do cache deve ser superior a 50 por cento para operação efetiva de cache SSD. Um pequeno número poderia ser indicativo de várias coisas:

+
** A proporção de leituras para gravações é muito pequena.
** As leituras não são repetidas.
** A capacidade do cache é muito pequena.
+
[NOTE]
====
Para ajudar a determinar a capacidade ideal de cache SSD, você pode executar a ferramenta de Modelagem de desempenho usando o `start ssdCache [ssdCacheName] performanceModeling` comando.

====


* *Alocação de cache (%)* -- a quantidade de armazenamento em cache SSD alocada, expressa como uma porcentagem do armazenamento em cache SSD disponível para este controlador. Derivado de bytes alocados / bytes disponíveis.
+
A porcentagem de alocação de cache normalmente aparece como 100 por cento. Se esse número for inferior a 100 por cento, significa que o cache não foi aquecido ou a capacidade do cache SSD é maior do que todos os dados que estão sendo acessados. Neste último caso, uma capacidade de cache SSD menor poderia fornecer o mesmo nível de desempenho. Observe que isso não indica que os dados armazenados em cache foram colocados no cache SSD, é simplesmente uma etapa de preparação antes que os dados possam ser colocados no cache SSD.

* *Utilização de cache (%)* -- a quantidade de armazenamento em cache SSD que contém dados de volumes ativados, expressa como uma porcentagem de armazenamento em cache SSD alocado. Esse valor representa a utilização ou a densidade do cache SSD. Derivado de bytes de dados do usuário / bytes alocados.
+
A porcentagem de utilização do cache normalmente é inferior a 100%, talvez muito menor. Este número mostra a porcentagem da capacidade de cache SSD que é preenchida com dados de cache. O motivo pelo qual esse número é inferior a 100 por cento é que cada unidade de alocação do cache SSD, o bloco cache SSD, é dividido em unidades menores chamadas sub-blocos, que são preenchidos de forma um pouco independente. Um número maior geralmente é melhor, mas os ganhos de desempenho podem ser significativos mesmo com um número menor.



Essas estatísticas adicionais são incluídas quando você salva os dados em um arquivo:

* *Leia blocos* -- número de blocos em leituras de host.
* * Escrever blocos* -- número de blocos em gravações de host.
* * Blocos de hit completo * -- número de cache de bloco hit.
+
Os blocos de hit completos indicam o número de blocos que foram lidos inteiramente do cache SSD. O cache SSD só é benéfico para o desempenho para as operações que são hits de cache completo.

* *Partial Hits* -- número de leituras de host onde pelo menos um bloco, mas não todos os blocos, estavam no cache SSD. Este é um cache SSD *miss* onde as leituras foram satisfeitas a partir do volume base.
+
Acessos parciais de cache e blocos parciais de acerto de cache resultam de uma operação que tem apenas uma parte de seus dados no cache SSD. Neste caso, a operação tem de recuperar os dados do volume da unidade de disco rígido em cache. O cache SSD não oferece nenhum benefício de desempenho para esse tipo de hit. Se a contagem de blocos de acerto de cache parcial for maior do que os blocos de acerto de cache completo, é possível que um tipo de caraterística de e/S diferente (sistema de arquivos, banco de dados ou servidor web) possa melhorar o desempenho.

* *Partial Hits -- Blocks* -- número de blocos em Partial Hits.
+
Acessos parciais de cache e blocos parciais de acerto de cache resultam de uma operação que tem apenas uma parte de seus dados no cache SSD. Neste caso, a operação tem de recuperar os dados do volume da unidade de disco rígido em cache. O cache SSD não oferece nenhum benefício de desempenho para esse tipo de hit. Se a contagem de blocos de acerto de cache parcial for maior do que os blocos de acerto de cache completo, é possível que um tipo de caraterística de e/S diferente (sistema de arquivos, banco de dados ou servidor web) possa melhorar o desempenho.

* *Misses* -- número de leituras de host onde nenhum dos blocos estava no cache SSD. Esta é uma falta de cache SSD onde as leituras foram satisfeitas a partir do volume base.
* *Misses -- blocos* -- número de blocos em misses.
* * Preencher ações (leituras do host)* -- número de leituras do host onde os dados foram copiados do volume base para o cache SSD.
* * Preencher ações (Host Reads) -- blocos* -- número de blocos em ações de preenchimento (Host Reads).
* * Preencher ações (Host Write)* -- número de gravações de host onde os dados foram copiados do volume base para o cache SSD.
+
A contagem de ações de preenchimento (gravações de host) pode ser zero para as configurações de cache que não preenchem o cache como resultado de uma operação de e/S de gravação.

* * Preencher ações (Host Write) -- blocos* -- número de blocos em ações de preenchimento (Host Write).
* *Invalidate actions* -- número de vezes que os dados foram invalidados/removidos do cache SSD. Uma operação de invalidação de cache é executada para cada solicitação de gravação do host, cada solicitação de leitura do host com Acesso forçado à Unidade (FUA), cada solicitação de verificação e em algumas outras circunstâncias.
* *Ações de reciclagem* -- número de vezes que o bloco de cache SSD foi reutilizado para outro volume base e/ou um intervalo LBA diferente.
+
Para uma operação de cache eficaz, é importante que o número de reciclagens seja pequeno em comparação com o número combinado de operações de leitura e gravação. Se o número de ações de reciclagem estiver próximo ao número combinado de leituras e gravações, o cache SSD está sendo arrastado. A capacidade do cache precisa ser aumentada ou a carga de trabalho não é favorável para uso com cache SSD.

* *Available bytes* -- número de bytes disponíveis no cache SSD para uso por este controlador.
+
Os bytes disponíveis, os bytes alocados e os bytes de dados do usuário são usados para calcular a % de alocação de cache e a % de utilização de cache.

* *Bytes alocados* -- número de bytes alocados do cache SSD por este controlador. Os bytes alocados a partir do cache SSD podem estar vazios ou podem conter dados de volumes base.
+
Os bytes disponíveis, os bytes alocados e os bytes de dados do usuário são usados para calcular a % de alocação de cache e a % de utilização de cache.

* *Bytes de dados do usuário* -- número de bytes alocados no cache SSD que contêm dados de volumes base.
+
Os bytes disponíveis, os bytes alocados e os bytes de dados do usuário são usados para calcular a % de alocação de cache e a % de utilização de cache.





== Nível mínimo de firmware

7,84

O 11,80 adiciona suporte a array EF600 e EF300
