---
permalink: commands-a-z/show-asyncmirrorgroup-summary.html 
sidebar: sidebar 
keywords: show, asynchronous, mirror, groups 
summary: O comando show asyncMirrorGroup summary exibe informações de configuração para um ou mais grupos de espelhos assíncronos. 
---
= Mostrar grupos de espelhos assíncronos
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
O `show asyncMirrorGroup summary` comando exibe informações de configuração para um ou mais grupos de espelhos assíncronos.



== Arrays compatíveis

Este comando se aplica a qualquer storage array individual, incluindo os arrays E2700, E5600, E2800, E5700, EF600 e EF300, desde que todos os pacotes SMcli estejam instalados.



== Funções

Para executar esse comando em um storage array E2800, E5700, EF600 ou EF300, você deve ter a função Administrador do armazenamento.



== Contexto

Esse comando também exibe os pares espelhados assíncronos associados a cada grupo de espelhos assíncronos, incluindo pares espelhados assíncronos incompletos.

Você também pode usar este comando para mostrar o progresso da sincronização periódica de dados em todos os pares espelhados dentro do grupo de espelhos assíncronos.



== Sintaxe

[listing, subs="+macros"]
----
show (allAsyncMirrorGroups |
asyncMirrorGroup pass:quotes[[_asyncMirrorGroupName_]] |
asyncMirrorGroups pass:quotes[[_asyncMirrorGroupName1_ ... _asyncMirrorGroupNameN_]])
[summary]
----


== Parâmetro

[cols="2*"]
|===
| Parâmetro | Descrição 


 a| 
`allAsyncMirrorGroups`
 a| 
Use este parâmetro se quiser exibir as propriedades de todos os grupos de espelhos assíncronos.



 a| 
`asyncMirrorGroup`
 a| 
O nome de um grupo de espelhos assíncrono para o qual você deseja exibir informações de configuração e o andamento da sincronização periódica de dados. Inclua o nome do grupo de espelhos assíncronos entre colchetes ([ ]). Se o nome do grupo de espelhos assíncronos tiver carateres ou números especiais, você deve incluir o nome do grupo de espelhos assíncronos entre aspas duplas (" ") dentro de colchetes.



 a| 
`asyncMirrorGroups`
 a| 
Os nomes de vários grupos de espelhos assíncronos para os quais você deseja recuperar informações. Digite os nomes dos grupos de espelhos assíncronos usando estas regras:

* Inclua todos os nomes entre colchetes ([ ]).
* Separe cada um dos nomes com um espaço.


Se os nomes de grupos de espelhos assíncronos tiverem carateres ou números especiais, insira os nomes usando estas regras:

* Inclua todos os nomes entre colchetes ([ ]).
* Coloque cada um dos nomes em aspas duplas (" ").
* Separe cada um dos nomes com um espaço.




 a| 
`summary`
 a| 
Este parâmetro exibe uma lista concisa de informações sobre o progresso da sincronização de um ou mais grupos de espelhos assíncronos.

|===


== Nível mínimo de firmware

7,84

O 11,80 adiciona suporte a array EF600 e EF300
