---
permalink: commands-a-z/show-controller.html 
sidebar: sidebar 
keywords: show, controller 
summary: O comando show controller retorna informações sobre um controller. 
---
= Mostrar controlador
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
O `show controller` comando retorna informações sobre um controlador.



== Arrays compatíveis

Este comando se aplica a qualquer storage array individual, incluindo os arrays E4000, E2700, E5600, E2800, E5700, EF600 e EF300, desde que todos os pacotes SMcli estejam instalados.



== Funções

Para executar esse comando em um storage array E4000, E2800, E5700, EF600 ou EF300, você deve ter a função Administrador de armazenamento.



== Contexto

Para cada controlador em uma matriz de armazenamento, este comando retorna as seguintes informações:

* O status (Online ou Offline)
* A configuração atual de firmware e NVSRAM
* A configuração de firmware pendente e a configuração NVSRAM (se houver)
* O ID do quadro
* A ID do produto
* A revisão do produto
* O número de série
* A data de fabricação
* O tamanho do cache ou o tamanho do processador
* A data e a hora em que o controlador está definido
* Os volumes associados (incluindo o proprietário preferido)
* A porta Ethernet
* A interface do disco físico
* A interface de host, que se aplica somente às interfaces de host Fibre Channel




== Sintaxe

[source, cli]
----
show (allControllers | controller [(a|b)])
 [summary]
----


== Parâmetros

[cols="2*"]
|===
| Parâmetro | Descrição 


 a| 
`allControllers`
 a| 
A configuração para retornar informações sobre ambos os controladores no storage array.



 a| 
`controller`
 a| 
A configuração para retornar informações sobre um controlador específico na matriz de armazenamento. Os identificadores válidos do controlador são `a` ou `b` , onde `a` está o controlador no slot A, e `b` é o controlador no slot B. feche o identificador do controlador entre colchetes ([ ]).



 a| 
`summary`
 a| 
A configuração para retornar uma lista concisa de informações sobre ambos os controladores no storage array.

|===


== Notas

A lista a seguir é um exemplo das informações retornadas pelo `show controller` comando. Este exemplo mostra apenas como as informações são apresentadas e não deve ser considerado como uma prática recomendada para uma configuração de storage array.

[listing]
----
Controller in slot A

   Status: Online
   Current configuration
      Firmware version: 96.10.21.00
         Appware version: 96.10.21.00
         Bootware version: 96.10.21.00
      NVSRAM version: N4884-610800-001
   Pending configuration
      Firmware version: Not applicable
         Appware version: Not applicable
         Bootware version: Not applicable
      NVSRAM version: Not applicable
      Transferred on: Not applicable
   Board ID: 4884
   Product ID: INF-01-00
   Product revision: 9610
   Serial number: 1T14148766
   Date of manufacture: October 14, 2006
   Cache/processor size (MB): 1024/128
   Date/Time: Wed Feb 18 13:55:53 MST 2008
   Associated Volumes (* = Preferred Owner):
      1*, 2*, CTL 0 Mirror Repository*, Mirror Repository 1*,
      JCG_Remote_MirrorMenuTests*
   Ethernet port: 1
      MAC address: 00:a0:b8:0c:c3:f5
      Host name: ausctlr9
      Network configuration: Static
      IP address: 172.22.4.249
      Subnet mask: 255.255.255.0
      Gateway: 172.22.4.1
      Remote login: Enabled
   Drive interface: Fibre
      Channel: 1
      Current ID: 125/0x1
      Maximum data rate: 2 Gbps
      Current data rate: 1 Gbps
      Data rate control: Switch
      Link status: Up
   Drive interface: Fibre
      Channel: 2
      Current ID: 125/0x1
      Maximum data rate: 2 Gbps
      Current data rate: 1 Gbps
      Data rate control: Switch
      Link status: Up
   Drive interface: Fibre
      Channel: 3
      Current ID: 125/0x1
      Maximum data rate: 2 Gbps
      Current data rate: 1 Gbps
      Data rate control: Switch
      Link status: Up
   Drive interface: Fibre
      Channel: 4
      Current ID: 125/0x1
      Maximum data rate: 2 Gbps
      Current data rate: 1 Gbps
      Data rate control: Switch
      Link status: Up
   Host interface: Fibre
      Port: 1
      Current ID: Not applicable/0xFFFFFFFF
      Preferred ID: 126/0x0
      NL-Port ID: 0x011100
      Maximum data rate: 2 Gbps
      Current data rate: 1 Gbps
      Data rate control: Switch
      Link status: Up
      Topology: Fabric Attach
      World-wide port name: 20:2c:00:a0:b8:0c:c3:f6
      World-wide node name: 20:2c:00:a0:b8:0c:c3:f5
      Part type: HPFC-5200    revision 10
   Host interface: Fibre
      Port: 2
      Current ID: Not applicable/0xFFFFFFFF
      Preferred ID: 126/0x0
      NL-Port ID: 0x011100
      Maximum data rate: 2 Gbps
      Current data rate: 1 Gbps
      Data rate control: Switch
      Link status: Up
      Topology: Fabric Attach
      World-wide port name: 20:2c:00:a0:b8:0c:c3:f7
      World-wide node name: 20:2c:00:a0:b8:0c:c3:f5
      Part type: HPFC-5200    revision 10
----
Quando você usa o `summary` parâmetro, o comando retorna a lista de informações sem as informações do canal da unidade e as informações do canal do host.

O `show storageArray` comando também retorna informações detalhadas sobre o controlador.



== Nível mínimo de firmware

5,43 adiciona o `summary` parâmetro.
