---
permalink: commands-a-z/show-volumecopy-source-targetcandidates.html 
sidebar: sidebar 
keywords: show, volume, copy, target, candidates 
summary: O comando show volumeCopy source targetCandidates retorna informações sobre os volumes candidatos que você pode usar como destino para uma operação de cópia de volume. Este comando é válido para pares de cópias de volume instantâneo. 
---
= Mostrar candidatos alvo de cópia de volume
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
O `show volumeCopy source targetCandidates` comando retorna informações sobre os volumes candidatos que você pode usar como destino para uma operação de cópia de volume. Este comando é válido para pares de cópias de volume instantâneo.



== Arrays compatíveis

Este comando se aplica a qualquer storage array individual, incluindo os arrays E4000, E2700, E5600, E2800, E5700, EF600 e EF300, desde que todos os pacotes SMcli estejam instalados.



== Funções

Para executar esse comando em um storage array E4000, E2800, E5700, EF600 ou EF300, você deve ter a função Storage Admin ou Storage Monitor.



== Sintaxe

[source, cli, subs="+macros"]
----
show volumeCopy source pass:quotes[["_sourceName_"]] targetCandidates
----


== Parâmetro

[cols="2*"]
|===
| Parâmetro | Descrição 


 a| 
`source`
 a| 
O nome do volume de origem para o qual você está tentando encontrar um volume de destino candidato. Coloque o nome do volume entre colchetes ([ ]). Se o nome do volume tiver carateres especiais ou números, você deve incluir o nome do volume entre aspas duplas (" ") dentro de colchetes.

|===