---
permalink: commands-a-z/show-volumegroup-importdependencies.html 
sidebar: sidebar 
keywords: show, volume, group, import, dependencies 
summary: O comando show volumeGroup importDependencies mostra uma lista de dependências para as unidades em um grupo de volumes que você deseja mover de um storage array para um segundo storage array. 
---
= Mostrar dependências de importação do grupo de volumes
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
O `show volumeGroup importDependencies` comando mostra uma lista de dependências para as unidades em um grupo de volumes que você deseja mover de um storage array para um segundo storage array.



== Arrays compatíveis

Este comando se aplica a qualquer storage array individual, incluindo os arrays E2700, E5600, E2800, E5700, EF600 e EF300, desde que todos os pacotes SMcli estejam instalados.



== Funções

Para executar esse comando em um storage array E2800, E5700, EF600 ou EF300, você deve ter a função Storage Admin ou Storage Monitor.



== Sintaxe

[listing, subs="+macros"]
----
pass:quotes[show volumeGroup [_volumeGroupName_]] importDependencies
[cancelImport=(TRUE | FALSE)]
----


== Parâmetros

[cols="2*"]
|===
| Parâmetro | Descrição 


 a| 
`volumeGroup`
 a| 
O nome do grupo de volumes para o qual você deseja mostrar dependências de importação. Inclua o nome do grupo de volume entre colchetes ([ ]).



 a| 
`cancelImport`
 a| 
A configuração para reduzir as unidades depois que as dependências do grupo de volume tiverem sido lidas. Para reduzir as unidades, defina este parâmetro como `TRUE`. Para deixar as unidades girarem, defina este parâmetro como `FALSE`.

|===


== Notas

Este comando retorna as dependências de um grupo de volume específico, que deve estar em um estado exportado ou em um estado forçado. Se uma decisão for tomada para manter as dependências listadas, o `cancelImport` parâmetro pode ser forçado a girar as unidades de volta para baixo.

Você deve executar o `show volumeGroup importDependencies` comando antes de executar o `start volumeGroup import` comando.



== Nível mínimo de firmware

7,10
