---
permalink: commands-a-z/show-storagearray-iscsinegotiationdefaults.html 
sidebar: sidebar 
keywords: show, storage, array, negotiation, defaults 
summary: O comando show storageArray iscsiNegotiationDefaults retorna informações sobre configurações de nível de conexão que estão sujeitas a negociação de destino do iniciador. 
---
= Mostrar padrões de negociação de storage array
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
O `show storageArray iscsiNegotiationDefaults` comando retorna informações sobre as configurações de nível de conexão que estão sujeitas a negociação do iniciador-alvo.



== Arrays compatíveis

Este comando se aplica a qualquer storage array individual, incluindo os arrays E4000, E2700, E5600, E2800, E5700, EF600 e EF300, desde que todos os pacotes SMcli estejam instalados.



== Funções

Para executar esse comando em um storage array E4000, E2800, E5700, EF600 ou EF300, você deve ter a função Storage Admin ou Storage Monitor.



== Sintaxe

[source, cli]
----
show storageArray iscsiNegotiationDefaults
----


== Parâmetros

Nenhum.



== Notas

As informações retornadas incluem as configurações padrão da bandeja do controlador (ou seja, as configurações que são o ponto de partida para negociação) e as configurações ativas atuais.



== Nível mínimo de firmware

7,10
