---
permalink: commands-a-z/show-storagearray-trustedcertificate-summary.html 
sidebar: sidebar 
keywords: show, installed, trusted, ca, certificates, summary 
summary: O comando show storageArray trusteCertificate summary exibe o resumo de certificados de CA instalados confiáveis do array. Este comando é útil para usar antes de executar o comando delete storageArray truckCertificate para que você conheça os nomes de alias dos certificados a serem excluídos. 
---
= Mostrar o resumo dos certificados de CA confiáveis instalados
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
O `show storageArray trustedCertificate summary` comando exibe o resumo dos certificados de CA instalados confiáveis da matriz. Este comando é útil para usar antes de executar o `delete storageArray trustedCertificate` comando para que você conheça os nomes de alias dos certificados a serem excluídos.



== Arrays compatíveis

Este comando se aplica a um storage array individual de armazenamento E2800, E5700, EF600 ou EF300. Ele não opera em matrizes de armazenamento E2700 ou E5600.



== Funções

Para executar esse comando em um storage array E2800, E5700, EF600 ou EF300, você deve ter a função Security Admin.



== Sintaxe

[listing, subs="+macros"]
----

show storageArray trustedCertificate [all | allUserInstalled|
 aliases=pass:quotes[("_alias1_" ... "_aliasN_")]] summary
----


== Parâmetros

[cols="2*"]
|===
| Parâmetro | Descrição 


 a| 
`all`
 a| 
Permite especificar a recuperação de todos os certificados, incluindo certificados pré-instalados e instalados pelo utilizador.



 a| 
`allUserInstalled`
 a| 
Permite especificar a recuperação de todos os certificados instalados pelo utilizador. Esta é a opção padrão.



 a| 
`aliases`
 a| 
Permite que o usuário especifique qual certificado confiável pré-instalado ou instalado pelo usuário para recuperar por alias. Inclua todos os aliases entre parênteses. Se você inserir mais de um alias, separe-os com um espaço.

|===


== Exemplos

A saída da amostra pode ser diferente da ilustrada abaixo.

[listing, subs="+macros"]
----

SMcli -n Array1 -c "show storageArray trustedCertificate allUserInstalled summary;"
============================
Trusted Certificates
============================
Alias:        19527b38-8d26-44e5-8c7f-5bf2ca9db7cf
Type:         Pre-installed | User installed
Subject DN:   CN=Corp Issuing CA 1
Issuer DN:    CN=Corp Root CA
pass:quotes[Start:        _date_]
pass:quotes[Expire:       _date_]
---------------------
Alias:        myAliasName
Type:         Pre-installed | User installed
Subject DN:   CN=Corp Issuing CA 1
Issuer DN:    CN=Corp Root CA
pass:quotes[Start:        _date_]
pass:quotes[Expire:       _date_]

SMcli completed successfully.
----


== Nível mínimo de firmware

8,40
