---
permalink: commands-a-z/smcli-autosupportschedule-show.html 
sidebar: sidebar 
keywords: display, autosupport, message, collection, schedule 
summary: O comando SMcli -AutoSupportSchedule show mostra a programação para coleta e processamento de mensagens AutoSupport diárias e semanais. 
---
= Exibir agendamento de coleta de mensagens do AutoSupport
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
O `SMcli -autoSupportSchedule show` comando mostra a programação para coleta e processamento de mensagens AutoSupport diárias e semanais.



== Arrays compatíveis

Esse comando se aplica a todos os storages E2700 e E5600 no domínio de gerenciamento de uma só vez. Isso não se aplica a storage arrays E2800 ou E5700.



== Contexto

[NOTE]
====
Este comando é um comando SMcli, não um comando script. Você deve executar este comando a partir de uma linha de comando. Não é possível executar este comando a partir do editor de scripts no software de gerenciamento de armazenamento.

====
Observe o seguinte no que diz respeito ao agendamento da coleção do pacote de suporte automático:

* Se o AutoSupport estiver ativado, o software de gerenciamento enviará mensagens diárias do AutoSupport e mensagens semanais do AutoSupport.
* O software de gerenciamento seleciona aleatoriamente uma hora do dia para mensagens diárias e semanais e um dia da semana para mensagens semanais.
* O software de gerenciamento faz todas as tentativas para garantir que nenhum dos dois storages de armazenamento dentro de um domínio de gerenciamento envie mensagens AutoSupport agendadas ao mesmo tempo.
* Usando o `SMcli -autoSupportSchedule reset` comando, você pode especificar um intervalo (granularidade no nível de hora) dos horários preferidos para enviar mensagens diárias e semanais para os storages de armazenamento em seu domínio de gerenciamento. Para o agendamento de mensagens semanais, use o comando para selecionar dias preferenciais da semana.




== Sintaxe

[listing]
----
SMcli -autoSupportSchedule show
----


== Parâmetros

Nenhum.



== Nível mínimo de firmware

8,25



== Exemplo

A saída mostra os intervalos de tempo preferidos, seguidos pelo horário diário e semanal.

[NOTE]
====
Se você não selecionar intervalos de tempo preferenciais para ambos os horários e dias preferidos da semana, esse comando mostrará a programação diária e semanal escolhida aleatoriamente pelo software de gerenciamento de armazenamento.

====
[listing]
----
SMcli -autoSupportSchedule show
The AutoSupport daily schedule preferred time range is from 12:00 AM to 01:00 AM.
The AutoSupport weekly schedule preferred time range is from 10:00 PM to 11:00 PM on Thursday, Saturday.

Name           Daily Schedule         Weekly Schedule
Accounting     12:55 AM               10:08 PM on Thursdays
Finance        12:02 AM               10:30 PM on Saturdays

SMcli completed successfully.
----