---
permalink: commands-a-z/start-storagearray-controllerhealthimage-controller.html 
sidebar: sidebar 
keywords: start, storage, array, controller, health, image 
summary: O comando start storageArray controllerHealthImage controller produz uma imagem de integridade do controlador de storage em arrays de armazenamento que suportam o recurso de imagem de integridade do controlador. 
---
= Inicie a imagem de integridade do controlador do storage array
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
O `start storageArray controllerHealthImage controller` comando produz uma imagem de integridade do controlador de storage array em storages que suportam o recurso de imagem de integridade do controlador.



== Arrays compatíveis

Este comando se aplica a qualquer storage array individual, incluindo os arrays E4000, E2700, E5600, E2800, E5700, EF600 e EF300, desde que todos os pacotes SMcli estejam instalados.



== Funções

Para executar esse comando em um storage array E4000, E2800, E5700, EF600 ou EF300, você deve ter a função Administrador de armazenamento.



== Contexto

[NOTE]
====
Com a versão de firmware 8,20, o `coreDump` parâmetro é substituído pelo `controllerHealthImage` parâmetro.

====
[NOTE]
====
Utilizar este comando apenas sob a direção do suporte técnico.

====
Se o storage array não suportar o recurso de imagem de integridade do controlador, o comando retornará um erro.



== Sintaxe

[source, cli]
----
start storageArray controllerHealthImage controller [(a|b)]
----


== Parâmetros

[cols="2*"]
|===
| Parâmetro | Descrição 


 a| 
`controller`
 a| 
Este parâmetro especifica o controlador a partir do qual produzir a imagem de integridade do controlador. Os identificadores válidos do controlador são `a` ou `b`, onde `a` está o controlador no slot A, e `b` é o controlador no slot B. feche o identificador do controlador entre colchetes ([ ]). Se você não especificar um controlador, o software de gerenciamento de armazenamento retornará um erro de sintaxe.

|===


== Notas

Este comando força o controlador selecionado a despejar seus dados de núcleo para armazenar em cache. Use o `save storageArray controllerHealthImage` comando para salvar uma cópia dos dados de cache em um arquivo host.



== Nível mínimo de firmware

7,83

8,20 substitui o `coreDump` parâmetro pelo `controllerHealthImage` parâmetro.
