---
permalink: commands-a-z/start-storagearray-autosupport-deliverytest.html 
sidebar: sidebar 
keywords: test, autosupport, delivery, set, individual, E2800, E5700, arrays 
summary: O comando start storageArray AutoSupport deliveryTest envia uma mensagem de coleta de pacotes AutoSupport de exemplo para que você possa testar a conexão com o sistema de suporte técnico de destino usando os parâmetros de entrega especificados. 
---
= Testar as definições de entrega do AutoSupport
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
O `start storageArray autoSupport deliveryTest` comando envia uma mensagem de coleção de pacotes AutoSupport de exemplo para que você possa testar a conexão com o sistema de suporte técnico de destino usando os parâmetros de entrega especificados.



== Arrays compatíveis

Esse comando se aplica a um storage array individual de armazenamento E4000, E2800, E5700, EF600 ou EF300. Ele não opera em matrizes de armazenamento E2700 ou E5600.



== Funções

Para executar esse comando em um storage array E4000, E2800, E5700, EF600 ou EF300, você deve ter a função Administrador de armazenamento ou Administrador de suporte.



== Sintaxe

[source, cli, subs="+macros"]
----
start storageArray autoSupport deliveryTest pass:quotes[[replyToEmail="_address_"]]
----


== Parâmetros

[cols="2*"]
|===
| Parâmetro | Descrição 


 a| 
`replyToEmail`
 a| 
Permite que o usuário especifique o endereço de e-mail de resposta para a mensagem de teste do AutoSupport. Só é utilizado/necessário quando o método de entrega está definido como e-mail.

|===


=== Exemplos

[listing]
----

SMcli -n Array1 -c "start storageArray autoSupport deliveryTest;"

SMcli -n Array1 -c "start storageArray autoSupport deliveryTest replyToEmail=\"user@company.com\";"

The sample AutoSupport message was successfully sent to the ASUP gateway server.

SMcli completed successfully.
----


== Nível mínimo de firmware

8,40
