---
permalink: commands-a-z/start-asyncmirrorgroup-synchronize.html 
sidebar: sidebar 
keywords: start, asynchronous, mirror, synchronization 
summary: O comando start asyncMirrorGroup Synchronize inicia a sincronização assíncrona de espelhamento. 
---
= Inicie a sincronização assíncrona do espelhamento
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
O `start asyncMirrorGroup synchronize` comando inicia a sincronização assíncrona de espelhamento.



== Arrays compatíveis

Este comando se aplica a qualquer storage array individual, incluindo os arrays E4000, E2700, E5600, E2800, E5700, EF600 e EF300, desde que todos os pacotes SMcli sejam instalados.



== Funções

Para executar esse comando em um storage array E4000, E2800, E5700, EF600 ou EF300, você deve ter a função Administrador de armazenamento.



== Sintaxe

[source, cli, subs="+macros"]
----
start asyncMirrorGroup pass:quotes[["_asyncMirrorGroupName_"]] synchronize [deleteRecoveryPointIfNecessary]
----


== Parâmetro

[cols="2*"]
|===
| Parâmetro | Descrição 


 a| 
`asyncMirrorGroup`
 a| 
O nome do grupo de espelhos assíncronos para o qual você deseja iniciar a sincronização. Inclua o nome do grupo de espelhos assíncronos entre aspas duplas (" ") dentro de colchetes ([" "]).



 a| 
`deleteRecoveryPointIfNecessary`
 a| 
O parâmetro para excluir o ponto de recuperação se os dados de sincronização recuperáveis excederem o limite de tempo para recuperação. A idade do ponto de recuperação é medida a partir do momento em que os dados foram congelados no storage array primário.

|===


== Nível mínimo de firmware

7,84

8,10 adiciona o `deleteRecoveryPointIfNecessary` parâmetro.

O 11,80 adiciona suporte a array EF600 e EF300
