---
permalink: commands-a-z/start-volume-initialization.html 
sidebar: sidebar 
keywords: start, volume, initialization 
summary: O comando start volume initialize inicia a formatação de um volume em uma matriz de armazenamento. 
---
= Iniciar a inicialização do volume
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
O `start volume initialize` comando inicia a formatação de um volume em uma matriz de armazenamento.



== Arrays compatíveis

Este comando se aplica a qualquer storage array individual, incluindo os arrays E2700, E5600, E2800, E5700, EF600 e EF300, desde que todos os pacotes SMcli estejam instalados.



== Funções

Para executar esse comando em um storage array E2800, E5700, EF600 ou EF300, você deve ter a função Administrador do armazenamento.



== Contexto

[NOTE]
====
A formatação de um volume inicia uma operação de longa duração que você não pode parar.

====


== Sintaxe

[listing, subs="+macros"]
----
pass:quotes[start volume [_volumeName_]] initialize
----


== Parâmetro

[cols="2*"]
|===
| Parâmetro | Descrição 


 a| 
`volume`
 a| 
O nome de um volume que você deseja formatar. Coloque o nome do volume entre colchetes ([ ]). Se o nome do volume tiver carateres especiais ou números, você deve incluir o nome entre aspas duplas (" ") dentro de colchetes.

|===


== Nível mínimo de firmware

6,10
