---
permalink: commands-a-z/start-syncmirror-primary-synchronize.html 
sidebar: sidebar 
keywords: start, synchronous, mirror, synchronization 
summary: O comando Iniciar sincronização primária do SyncMirror inicia a sincronização de espelhamento síncrono. 
---
= Inicie a sincronização de espelhamento síncrono
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
O `start syncMirror primary synchronize` comando inicia a sincronização síncrona de espelhamento.



== Arrays compatíveis

Este comando se aplica a qualquer storage array individual, incluindo os arrays E4000, E2700, E5600, E2800 e E5700, desde que todos os pacotes SMcli estejam instalados.



== Funções

Para executar esse comando em um storage array E4000, E2800 ou E5700, você deve ter a função Storage Admin.



== Contexto

[NOTE]
====
Em versões anteriores deste comando, o identificador de funcionalidade era `remoteMirror`. Esse identificador de recurso não é mais válido e é substituído por `syncMirror`.

====


== Sintaxe

[source, cli, subs="+macros"]
----
pass:quotes[start syncMirror primary ["_volumeName_"]] synchronize
----


== Parâmetro

[cols="2*"]
|===
| Parâmetro | Descrição 


 a| 
`primary`
 a| 
O nome do volume principal para o qual você deseja iniciar a sincronização. Coloque o nome do volume primário entre aspas duplas (" ") dentro de colchetes ([ ]).

|===


== Nível mínimo de firmware

6,10
