---
permalink: commands-a-z/start-ssdcache-locate.html 
sidebar: sidebar 
keywords: start, ssd, cache, locate 
summary: 'O comando start ssdCache Locate identifica os discos de estado sólido (SSDs) que são agrupados logicamente para formar o cache SSD piscando as luzes indicadoras nos SSDs.' 
---
= Inicie o cache SSD Locate
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
O `start ssdCache locate` comando identifica os discos de estado sólido (SSDs) que são agrupados logicamente para formar o cache SSD piscando as luzes indicadoras nos SSDs.



== Arrays compatíveis

Este comando se aplica a qualquer storage array individual, incluindo os arrays E4000, E2700, E5600, E2800, E5700, EF600 e EF300, desde que todos os pacotes SMcli sejam instalados.



== Funções

Para executar esse comando em um storage array E4000, E2800, E5700, EF600 ou EF300, você deve ter a função Admin de suporte.



== Contexto

Use o `stop ssdCache locate` comando para desligar as luzes indicadoras nas unidades.



== Sintaxe

[source, cli, subs="+macros"]
----
start ssdCache pass:quotes[[_ssdCacheName_]] locate
----


== Parâmetros

[cols="2*"]
|===
| Parâmetro | Descrição 


 a| 
`ssdCache`
 a| 
O nome do cache SSD que você deseja localizar. Inclua o nome do cache SSD entre colchetes ([ ]). Se o nome do cache SSD contiver carateres especiais ou consistir apenas em números, você deve incluir o nome do cache SSD em aspas duplas (" ") dentro de colchetes.

|===


== Nível mínimo de firmware

7,84

O 11,80 adiciona suporte a array EF600 e EF300
