---
permalink: commands-a-z/stop-ssdcache-performancemodeling.html 
sidebar: sidebar 
keywords: stop, ssd, cache, performance, model 
summary: O comando stop ssdCache performanceModeling interrompe a operação de modelagem de desempenho e exibe os dados de modelagem de desempenho para o cache SSD. 
---
= Pare a modelagem de desempenho de cache SSD
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
O `stop ssdCache performanceModeling` comando interrompe a operação de modelagem de desempenho e exibe os dados de modelagem de desempenho para o cache SSD.



== Arrays compatíveis

Este comando se aplica a qualquer storage array individual, incluindo os arrays E2700, E5600, E2800, E5700, EF600 e EF300, desde que todos os pacotes SMcli estejam instalados.



== Funções

Para executar esse comando em um storage array E2800, E5700, EF600 ou EF300, você deve ter a função Administrador de suporte.



== Contexto

Antes de executar esse comando, você deve iniciar a operação de modelagem de desempenho com o `start ssdCache performanceModeling` comando. Opcionalmente, você pode salvar os dados em um arquivo.



== Sintaxe

[listing, subs="+macros"]
----

pass:quotes[stop ssdCache [_ssdCacheName_]] performanceModeling pass:quotes[[file="_filename_"]]
----


== Parâmetros

[cols="2*"]
|===
| Parâmetro | Descrição 


 a| 
`ssdCache`
 a| 
O nome do cache SSD para o qual você deseja parar de modelar o desempenho. Inclua o nome do cache SSD entre colchetes ([ ]). Se o nome do cache SSD tiver carateres ou números especiais, você deve incluir o nome do cache SSD em aspas duplas (" ") dentro de colchetes.



 a| 
`file`
 a| 
O caminho do arquivo e o nome do arquivo para o qual você deseja salvar os dados de modelagem de desempenho. Coloque o nome do ficheiro entre aspas duplas (" "). Por exemplo:

`file="C:\Program Files\CLI\logs\ssdcacheperf.csv"`

Você pode usar qualquer nome de arquivo, mas você deve usar a `.csv` extensão.

|===


== Notas

Este comando retorna as informações de modelagem de desempenho semelhantes a este exemplo. O tamanho do seu monitor determina como as informações são envoltas e afetará a forma como as informações são exibidas.

[listing]
----
SSD Cache Name: my_cache
Start time: 4/18/12 2:38:26  PM IST
Stop time: 4/18/12 2:38:45 PM IST
Duration : 00:00:19

SSD Cache Performance Modeling Data (Response Time):

                        SSD Reads            HDD Reads           HDD Writes
            Overall     Avg.                 Avg.                Avg.
Cache       Response    Response    % of    Response    % of    Response    % of
Capacity    Time        Time        I/Os    Time        I/Os    Time        I/Os
186 GB      0 ms        0 ms        0.0 %   0 ms        0.0 %   0 ms        0.0 %
372 GB      0 ms        0 ms        0.0 %   0 ms        0.0 %   0 ms        0.0 %
557 GB *    0 ms        0 ms        0.0 %   0 ms        0.0 %   0 ms        0.0 %
558 GB      0 ms        0 ms        0.0 %   0 ms        0.0 %   0 ms        0.0 %
744 GB      0 ms        0 ms        0.0 %   0 ms        0.0 %   0 ms        0.0 %
931 GB      0 ms        0 ms        0.0 %   0 ms        0.0 %   0 ms        0.0 %
1117 GB     0 ms        0 ms        0.0 %   0 ms        0.0 %   0 ms        0.0 %
1303 GB     0 ms        0 ms        0.0 %   0 ms        0.0 %   0 ms        0.0 %
1489 GB     0 ms        0 ms        0.0 %   0 ms        0.0 %   0 ms        0.0 %
1675 GB     0 ms        0 ms        0.0 %   0 ms        0.0 %   0 ms        0.0 %
1862 GB     0 ms        0 ms        0.0 %   0 ms        0.0 %   0 ms        0.0 %

* = Current SSD cache physical capacity.


SSD Cache Performance Modeling Data (Cache Hit %):

Cache Capacity    Cache Hit %
186 GB            0 %
372 GB            0 %
557 GB *          0 %
558 GB            0 %
744 GB            0 %
931 GB            0 %
1117 GB           0 %
1303 GB           0 %
1489 GB           0 %
1675 GB           0 %
1862 GB           0 %
* = Current SSD cache physical capacity.
----


== Nível mínimo de firmware

7,84

O 11,80 adiciona suporte a array EF600 e EF300
