---
permalink: commands-a-z/stop-volumecopy-target-source.html 
sidebar: sidebar 
keywords: stop, volume, copy 
summary: O comando stop volumeCopy target source pára uma operação de cópia de volume. Este comando é válido para pares de cópias de volume instantâneo. 
---
= Parar a cópia do volume
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
O `stop volumeCopy target source` comando pára uma operação de cópia de volume. Este comando é válido para pares de cópias de volume instantâneo.



== Arrays compatíveis

Este comando se aplica a qualquer storage array individual, incluindo os arrays E4000, E2700, E5600, E2800, E5700, EF600 e EF300, desde que todos os pacotes SMcli estejam instalados.



== Funções

Para executar esse comando em um storage array E4000, E2800, E5700, EF600 ou EF300, você deve ter a função Administrador de armazenamento.



== Sintaxe

[source, cli, subs="+macros"]
----
pass:quotes[stop volumeCopy target [_targetName_]] source pass:quotes[[_sourceName_]]
----


== Parâmetros

[cols="2*"]
|===
| Parâmetro | Descrição 


 a| 
`target`
 a| 
O nome do volume de destino para o qual você deseja interromper uma operação de cópia de volume. Coloque o nome do volume alvo entre colchetes ([ ]). Se o nome do volume de destino tiver carateres ou números especiais, você deve incluir o nome do volume de destino entre aspas duplas (" ") dentro de colchetes.



 a| 
`source`
 a| 
O nome do volume de origem para o qual pretende parar uma operação de cópia de volume. Inclua o nome do volume de origem entre colchetes ([ ]). Se o nome do volume de origem tiver carateres especiais ou números, você deve incluir o nome do volume de origem entre aspas duplas (" ") dentro de colchetes.

|===